import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var T3=function(a,b,c){if(null!=a&&null!=a.Se)a=a.Se(a,b,c);else{var d=T3[$APP.ja(null==a?null:a)];if(null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else if(d=T3._,null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else throw $APP.Xb("ITransientVector.-assoc-n!",a);}return a},U3=function(a,b,c){var d=$APP.Ge(a);if(c>=d)return-1;!(0<c)&&0>c&&(c+=d,c=0>c?0:c);for(;;)if(c<d){if($APP.x.h($APP.A.h(a,c),b))return c;c+=1}else return-1},V3=function(a,b,c){var d=$APP.Ge(a);if(0===d)return-1;0<c?(--d,c=d<c?d:c):c=0>
c?d+c:c;for(;;)if(0<=c){if($APP.x.h($APP.A.h(a,c),b))return c;--c}else return-1},W3=function(a,b){if($APP.cf(b))if($APP.Ee(a)&&$APP.Ee(b)&&$APP.Ge(a)!==$APP.Ge(b))a=!1;else a:for(a=$APP.u(a),b=$APP.u(b);;){if(null==a){a=null==b;break a}if(null!=b&&$APP.x.h($APP.v(a),$APP.v(b)))a=$APP.w(a),b=$APP.w(b);else{a=!1;break a}}else a=null;return $APP.ub(a)},X3=function(a,b){var c=a.ia(null);if(0===c)return b.v?b.v():b.call(null);for(var d=a.U(null,0),e=1;;)if(e<c){var f=a.U(null,e);d=b.h?b.h(d,f):b.call(null,
d,f);if($APP.te(d))return $APP.q(d);e+=1}else return d},Y3=function(a,b,c){var d=a.ia(null),e=c;for(c=0;;)if(c<d){var f=a.U(null,c);e=b.h?b.h(e,f):b.call(null,e,f);if($APP.te(e))return $APP.q(e);c+=1}else return e},Z3=function(a){return"number"===typeof a||"string"===typeof a||$APP.nf(a)||null==a},b4=function(a,b,c,d){var e=null!=d?d.g?d.g(a):d.call(null,a):null;return null==e?Z3(a)?a:$APP.Rb(a)?new $3(null,a,b,c,d,!0,null,null,null):$APP.Mb(a)?new a4(null,b,c,d,a,null):a:e},c4=function(a){return Z3(a)?
a:a instanceof $3?a.oa:a instanceof a4?a.C:a},cNa=function(a,b,c,d,e){var f=$APP.$h($APP.od(bNa));$APP.Ma(a,function(k,n){return f.Zb(null,$APP.kj.j(f.wa(null),b.g?b.g(n):b.call(null,n),$APP.l(e)?b4(k,b,c,d):k))});return $APP.qd($APP.q(f))},e4=function(a){a:for(var b=a.length,c=$APP.$b(a),d=0;;)if(d<b){var e=d;var f=a[d];f=d4.g?d4.g(f):d4.call(null,f);c[e]=f;d+=1}else break a;return $APP.Ii(c)},f4=function(a,b,c,d,e,f,k){k=f[k];f=b.g?b.g(k):b.call(null,k);a=a[k];b=e?b4(a,b,c,d):a;return new $APP.Af(f,
b,null)},dNa=function(a,b){return a instanceof $APP.F&&b===$APP.Xk||"string"===typeof a&&b===$APP.Mf},g4=function(a,b){return Z3(a)||!($APP.df(a)&&!(a instanceof $3)||$APP.ff(a)&&!(a instanceof a4))&&$APP.Ob($APP.l(b)?$APP.Rb(a)||$APP.Mb(a):b)},eNa=function(a,b,c,d,e,f){this.wb=!0;this.oa=a;this.ca=b;this.R=c;this.transform=d;this.La=e;this.wc=f;this.G=259;this.O=56},h4=function(a,b,c,d,e,f,k){this.oa=a;this.ca=b;this.R=c;this.transform=d;this.La=e;this.C=f;this.N=0;this.J=k},i4=function(a,b,c,d,
e,f,k,n){this.oa=a;this.ca=b;this.R=c;this.transform=d;this.La=e;this.C=f;this.N=k;this.H=n;this.G=2179858686;this.O=8192},$3=function(a,b,c,d,e,f,k,n,r){this.H=a;this.oa=b;this.ca=c;this.R=d;this.transform=e;this.La=f;this.Dc=k;this.wc=n;this.I=r;this.G=2164131599;this.O=139268},fNa=function(a,b,c,d){this.wb=!0;this.C=a;this.ca=b;this.R=c;this.transform=d;this.O=88;this.G=275},j4=function(a,b,c,d,e){this.ca=a;this.R=b;this.transform=c;this.C=d;this.N=0;this.J=e},k4=function(a,b,c,d,e,f){this.ca=
a;this.R=b;this.transform=c;this.C=d;this.N=e;this.H=f;this.G=2179858686;this.O=8192},a4=function(a,b,c,d,e,f){this.H=a;this.ca=b;this.R=c;this.transform=d;this.C=e;this.I=f;this.G=2315150111;this.O=141316},l4=function(a){return a instanceof $APP.F?a.ga:null},m4=function(a){return a instanceof $3},n4=function(a){return a.oa},gNa=new $APP.t("cljs-bean.core","-\x3ejs","cljs-bean.core/-\x3ejs",272545438,null),o4=new $APP.F(null,"key-\x3eprop","key-\x3eprop",-1028452531),hNa=new $APP.t(null,"bean?","bean?",
2057456095,null),iNa=new $APP.F(null,"recursive","recursive",718885872),jNa=new $APP.F(null,"prop-\x3ekey","prop-\x3ekey",-1297715246),kNa=new $APP.t("cljs-bean.core","bean?","cljs-bean.core/bean?",-413971875,null),lNa=new $APP.t("cljs-bean.core","bean","cljs-bean.core/bean",444589162,null),mNa=new $APP.t(null,"bean","bean",-1620239896,null),nNa=new $APP.F(null,"transform","transform",1381301764),oNa=new $APP.t(null,"-\x3eclj","-\x3eclj",-1549422014,null),pNa=new $APP.t("cljs-bean.core","object",
"cljs-bean.core/object",1153194626,null),qNa=new $APP.t("cljs-bean.core","-\x3eclj","cljs-bean.core/-\x3eclj",649375936,null),rNa=new $APP.t(null,"-\x3ejs","-\x3ejs",-1825590244,null);var p4={},bNa=$APP.th;$APP.g=eNa.prototype;$APP.g.qa=function(a,b){if(this.wb)return a=this.oa[this.R.g?this.R.g(b):this.R.call(null,b)],this.La?b4(a,this.ca,this.R,this.transform):a;throw Error("lookup after persistent!");};$APP.g.W=function(a,b,c){if(this.wb)return a=$APP.Ua(this.oa,this.R.g?this.R.g(b):this.R.call(null,b),c),this.La&&a!==c?b4(a,this.ca,this.R,this.transform):a;throw Error("lookup after persistent!");};
$APP.g.ia=function(){return null==this.wc?this.wc=$APP.Ge($APP.Oa(this.oa)):this.wc};$APP.g.yd=function(a,b){a:if($APP.l(this.wb))if($APP.Fi(b))a=this.pd(null,$APP.Cc(b),$APP.Dc(b));else if($APP.ff(b))a=this.pd(null,b.g?b.g(0):b.call(null,0),b.g?b.g(1):b.call(null,1));else for(a=$APP.u(b),b=this;;){var c=$APP.v(a);if($APP.l(c))a=$APP.w(a),b=$APP.rd(b,$APP.Cc(c),$APP.Dc(c));else{a=b;break a}}else throw Error("conj! after persistent!");return a};
$APP.g.ae=function(){if(this.wb)return this.wb=!1,new $3(null,this.oa,this.ca,this.R,this.transform,this.La,null,this.wc,null);throw Error("persistent! called twice");};$APP.g.pd=function(a,b,c){if(this.wb){if(!dNa(b,this.ca)||!g4(c,this.La))return $APP.rd($APP.od(cNa(this.oa,this.ca,this.R,this.transform,this.La)),b,c);this.oa[this.R.g?this.R.g(b):this.R.call(null,b)]=this.La?c4(c):c;this.wc=null;return this}throw Error("assoc! after persistent!");};
$APP.g.Df=function(a,b){if(this.wb)return delete this.oa[this.R.g?this.R.g(b):this.R.call(null,b)],this.wc=null,this;throw Error("dissoc! after persistent!");};$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length-1)].join(""));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.$b(b)))};
$APP.g.g=function(a){if(this.wb)return a=this.oa[this.R.g?this.R.g(a):this.R.call(null,a)],this.La?b4(a,this.ca,this.R,this.transform):a;throw Error("lookup after persistent!");};$APP.g.h=function(a,b){if(this.wb)return a=$APP.Ua(this.oa,this.R.g?this.R.g(a):this.R.call(null,a),b),this.La&&a!==b?b4(a,this.ca,this.R,this.transform):a;throw Error("lookup after persistent!");};h4.prototype.hasNext=function(){return this.N<this.J};
h4.prototype.next=function(){var a=f4(this.oa,this.ca,this.R,this.transform,this.La,this.C,this.N);this.N+=1;return a};$APP.g=i4.prototype;$APP.g.toString=function(){return $APP.Ld(this)};$APP.g.equiv=function(a){return this.P(null,a)};$APP.g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return U3(this,b,0);case 2:return U3(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return U3(this,b,0)};a.h=function(b,c){return U3(this,b,c)};return a}();
$APP.g.lastIndexOf=function(){function a(c){return V3(this,c,$APP.Ge(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V3(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V3(this,c,d)};return b}();$APP.g.U=function(a,b){a=b+this.N;if(0<=a&&a<this.C.length)return f4(this.oa,this.ca,this.R,this.transform,this.La,this.C,a);throw Error("Index out of bounds");};
$APP.g.Ra=function(a,b,c){a=b+this.N;return 0<=a&&a<this.C.length?f4(this.oa,this.ca,this.R,this.transform,this.La,this.C,a):c};$APP.g.X=function(a,b,c){return $APP.Sk(b,$APP.Vk,"("," ",")",c,this)};$APP.g.T=function(){return this.H};$APP.g.ja=function(){return new i4(this.oa,this.ca,this.R,this.transform,this.La,this.C,this.N,this.H)};$APP.g.Wa=function(){return this.N+1<this.C.length?new i4(this.oa,this.ca,this.R,this.transform,this.La,this.C,this.N+1,null):null};
$APP.g.ia=function(){var a=this.C.length-this.N;return 0>a?0:a};$APP.g.da=function(){return $APP.le(this)};$APP.g.P=function(a,b){return W3(this,b)};$APP.g.va=function(){return $APP.fe};$APP.g.Sa=function(a,b){return X3(this,b)};$APP.g.Qa=function(a,b,c){return Y3(this,b,c)};$APP.g.Ta=function(){return f4(this.oa,this.ca,this.R,this.transform,this.La,this.C,this.N)};$APP.g.Za=function(){return this.N+1<this.C.length?new i4(this.oa,this.ca,this.R,this.transform,this.La,this.C,this.N+1,null):$APP.fe};
$APP.g.fa=function(){return this};$APP.g.V=function(a,b){return b===this.H?this:new i4(this.oa,this.ca,this.R,this.transform,this.La,this.C,this.N,b)};$APP.g.na=function(a,b){return $APP.Rg(b,this)};$APP.g=$3.prototype;$APP.g.ld=$APP.Wd;$APP.g.Tc=function(a,b){a=$APP.Ua(this.oa,this.R.g?this.R.g(b):this.R.call(null,b),p4);return a===p4?null:new $APP.Af(b,this.La?b4(a,this.ca,this.R,this.transform):a,null)};$APP.g.toString=function(){return $APP.Ld(this)};
$APP.g.equiv=function(a){return this.P(null,a)};$APP.g.keys=function(){return $APP.ie($APP.fk(this))};$APP.g.entries=function(){return new $APP.$i($APP.u($APP.u(this)))};$APP.g.values=function(){return $APP.ie($APP.hk(this))};$APP.g.has=function(a){return $APP.zf(this,a)};$APP.g.get=function(a,b){return this.W(null,a,b)};
$APP.g.forEach=function(a){for(var b=$APP.u(this),c=null,d=0,e=0;;)if(e<d){var f=c.U(null,e),k=$APP.A.j(f,0,null);f=$APP.A.j(f,1,null);a.h?a.h(f,k):a.call(null,f,k);e+=1}else if(b=$APP.u(b))$APP.gf(b)?(c=$APP.yd(b),b=$APP.zd(b),k=c,d=$APP.Ge(c),c=k):(c=$APP.v(b),k=$APP.A.j(c,0,null),f=$APP.A.j(c,1,null),a.h?a.h(f,k):a.call(null,f,k),b=$APP.w(b),c=null,d=0),e=0;else return null};
$APP.g.qa=function(a,b){a=this.oa[this.R.g?this.R.g(b):this.R.call(null,b)];return this.La?b4(a,this.ca,this.R,this.transform):a};$APP.g.W=function(a,b,c){a=$APP.Ua(this.oa,this.R.g?this.R.g(b):this.R.call(null,b),c);return this.La&&a!==c?b4(a,this.ca,this.R,this.transform):a};
$APP.g.Bb=function(a,b,c){var d=this;try{var e=$APP.$h(c);$APP.Ma(d.oa,function(f,k){var n=e.Zb;var r=e.wa(null);k=d.ca.g?d.ca.g(k):d.ca.call(null,k);f=d.La?b4(f,d.ca,d.R,d.transform):f;r=b.j?b.j(r,k,f):b.call(null,r,k,f);n=n.call(e,null,r);if($APP.te(n))throw n;return null});return $APP.q(e)}catch(f){a=f;if($APP.te(a))return $APP.q(a);throw a;}};$APP.g.X=function(a,b,c){return $APP.Yk(this,$APP.Vk,b,c)};
$APP.g.Pa=function(){null==this.Dc&&(this.Dc=$APP.Oa(this.oa));return new h4(this.oa,this.ca,this.R,this.transform,this.La,this.Dc,this.ia(null))};$APP.g.T=function(){return this.H};$APP.g.ja=function(){return new $3(this.H,this.oa,this.ca,this.R,this.transform,this.La,this.Dc,this.wc,this.I)};$APP.g.ia=function(){return null==this.wc?(null==this.Dc&&(this.Dc=$APP.Oa(this.oa)),this.wc=this.Dc.length):this.wc};$APP.g.da=function(){var a=this.I;return null!=a?a:this.I=a=$APP.me(this)};
$APP.g.P=function(a,b){return $APP.Yi(this,b)};$APP.g.Ld=function(){return new eNa($APP.Va(this.oa),this.ca,this.R,this.transform,this.La,this.wc)};$APP.g.va=function(){return new $3(this.H,{},this.ca,this.R,this.transform,this.La,[],0,null)};$APP.g.Sa=function(a,b){return $APP.JA(this.fa(null),b)};$APP.g.Qa=function(a,b,c){return this.Bb(null,function(d,e,f){e=new $APP.Af(e,f,null);return b.h?b.h(d,e):b.call(null,d,e)},c)};
$APP.g.Lb=function(a,b){a=this.H;var c=$APP.Va(this.oa);delete c[this.R.g?this.R.g(b):this.R.call(null,b)];return new $3(a,c,this.ca,this.R,this.transform,this.La,null,null,null)};$APP.g.ra=function(a,b,c){if(dNa(b,this.ca)&&g4(c,this.La)){a=this.H;var d=$APP.Va(this.oa);d[this.R.g?this.R.g(b):this.R.call(null,b)]=this.La?c4(c):c;b=new $3(a,d,this.ca,this.R,this.transform,this.La,null,null,null)}else b=$APP.xc($APP.Ue(cNa(this.oa,this.ca,this.R,this.transform,this.La),this.H),b,c);return b};
$APP.g.vb=function(a,b){return this.W(null,b,p4)!==p4};$APP.g.fa=function(){null==this.Dc&&(this.Dc=$APP.Oa(this.oa));return 0<this.Dc.length?new i4(this.oa,this.ca,this.R,this.transform,this.La,this.Dc,0,null):null};$APP.g.V=function(a,b){return b===this.H?this:new $3(b,this.oa,this.ca,this.R,this.transform,this.La,this.Dc,this.wc,this.I)};
$APP.g.na=function(a,b){a:if($APP.ff(b))a=this.ra(null,$APP.Re(b,0),$APP.Re(b,1));else for(a=this,b=$APP.u(b);;){if(null==b)break a;var c=$APP.v(b);if($APP.ff(c))a=$APP.xc(a,$APP.Re(c,0),$APP.Re(c,1)),b=$APP.w(b);else throw Error("conj on a map takes map entries or seqables of map entries");}return a};
$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length-1)].join(""));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.$b(b)))};$APP.g.g=function(a){a=this.oa[this.R.g?this.R.g(a):this.R.call(null,a)];return this.La?b4(a,this.ca,this.R,this.transform):a};
$APP.g.h=function(a,b){a=$APP.Ua(this.oa,this.R.g?this.R.g(a):this.R.call(null,a),b);return this.La&&a!==b?b4(a,this.ca,this.R,this.transform):a};$APP.g=fNa.prototype;$APP.g.yd=function(a,b){if(this.wb)return g4(b,!0)?(this.C.push(c4(b)),this):$APP.pd($APP.od(e4(this.C)),b);throw Error("conj! after persistent!");};$APP.g.ae=function(){if(this.wb)return this.wb=!1,new a4(null,this.ca,this.R,this.transform,this.C,null);throw Error("persistent! called twice");};
$APP.g.pd=function(a,b,c){if("number"===typeof b)a=this.Se(null,b,c);else throw Error([$APP.m.g("TransientArrayVector"),"'s key for assoc! must be a number."].join(""));return a};
$APP.g.Se=function(a,b,c){if(this.wb){if(g4(c,!0)){if(0<=b&&b<this.C.length)return this.C[b]=c4(c),this;if(b===this.C.length)return this.yd(null,c);throw Error(["Index ",$APP.m.g(b)," out of bounds for TransientArrayVector of length",$APP.m.g(this.C.length)].join(""));}return T3($APP.od(e4(this.C)),b,c)}throw Error("assoc! after persistent!");};
$APP.g.ug=function(){if(this.wb){if(0===this.C.length)throw Error("Can't pop empty vector");this.C=this.C.slice(0,this.C.length-1);return this}throw Error("pop! after persistent!");};$APP.g.ia=function(){if(this.wb)return this.C.length;throw Error("count after persistent!");};$APP.g.U=function(a,b){if(this.wb)return b4(this.C[b],this.ca,this.R,this.transform);throw Error("nth after persistent!");};$APP.g.Ra=function(a,b,c){return 0<=b&&b<this.C.length?this.U(null,b):c};
$APP.g.qa=function(a,b){return this.W(null,b,null)};$APP.g.W=function(a,b,c){return"number"===typeof b?this.Ra(null,b,c):c};$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length-1)].join(""));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.$b(b)))};$APP.g.g=function(a){return this.qa(null,a)};
$APP.g.h=function(a,b){return this.W(null,a,b)};j4.prototype.hasNext=function(){return this.N<this.J};j4.prototype.next=function(){var a=b4(this.C[this.N],this.ca,this.R,this.transform);this.N+=1;return a};$APP.g=k4.prototype;$APP.g.toString=function(){return $APP.Ld(this)};$APP.g.equiv=function(a){return this.P(null,a)};
$APP.g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return U3(this,b,0);case 2:return U3(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return U3(this,b,0)};a.h=function(b,c){return U3(this,b,c)};return a}();
$APP.g.lastIndexOf=function(){function a(c){return V3(this,c,$APP.Ge(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V3(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V3(this,c,d)};return b}();$APP.g.U=function(a,b){a=b+this.N;if(0<=a&&a<this.C.length)return b4(this.C[a],this.ca,this.R,this.transform);throw Error("Index out of bounds");};
$APP.g.Ra=function(a,b,c){a=b+this.N;return 0<=a&&a<this.C.length?b4(this.C[a],this.ca,this.R,this.transform):c};$APP.g.X=function(a,b,c){return $APP.Sk(b,$APP.Vk,"("," ",")",c,this)};$APP.g.T=function(){return this.H};$APP.g.ja=function(){return new k4(this.ca,this.R,this.transform,this.C,this.N,this.H)};$APP.g.Wa=function(){return this.N+1<this.C.length?new k4(this.ca,this.R,this.transform,this.C,this.N+1,null):null};$APP.g.ia=function(){var a=this.C.length-this.N;return 0>a?0:a};$APP.g.da=function(){return $APP.le(this)};
$APP.g.P=function(a,b){return W3(this,b)};$APP.g.va=function(){return $APP.fe};$APP.g.Sa=function(a,b){return X3(this,b)};$APP.g.Qa=function(a,b,c){return Y3(this,b,c)};$APP.g.Ta=function(){return b4(this.C[this.N],this.ca,this.R,this.transform)};$APP.g.Za=function(){return this.N+1<this.C.length?new k4(this.ca,this.R,this.transform,this.C,this.N+1,null):$APP.fe};$APP.g.fa=function(){return this};$APP.g.V=function(a,b){return b===this.H?this:new k4(this.ca,this.R,this.transform,this.C,this.N,b)};
$APP.g.na=function(a,b){return $APP.Rg(b,this)};$APP.g=a4.prototype;$APP.g.ld=$APP.Wd;$APP.g.Tc=function(a,b){return 0<=b&&b<this.C.length?new $APP.Af(b,b4(this.C[b],this.ca,this.R,this.transform),null):null};$APP.g.toString=function(){return $APP.Ld(this)};$APP.g.equiv=function(a){return this.P(null,a)};
$APP.g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return U3(this,b,0);case 2:return U3(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return U3(this,b,0)};a.h=function(b,c){return U3(this,b,c)};return a}();
$APP.g.lastIndexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return V3(this,b,$APP.Ge(this));case 2:return V3(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return V3(this,b,$APP.Ge(this))};a.h=function(b,c){return V3(this,b,c)};return a}();$APP.g.qa=function(a,b){return this.W(null,b,null)};$APP.g.W=function(a,b,c){return"number"===typeof b?this.Ra(null,b,c):c};
$APP.g.Bb=function(a,b,c){a=0;for(var d=c;;)if(a<this.C.length){c=this.C.length;var e;a:for(e=0;;)if(e<c){var f=e+a,k=b4(this.C[e],this.ca,this.R,this.transform);d=b.j?b.j(d,f,k):b.call(null,d,f,k);if($APP.te(d)){e=d;break a}e+=1}else{e=d;break a}if($APP.te(e))return $APP.q(e);a+=c;d=e}else return d};$APP.g.U=function(a,b){if(0<=b&&b<this.C.length)return b4(this.C[b],this.ca,this.R,this.transform);throw Error(["No item ",$APP.m.g(b)," in vector of length ",$APP.m.g(this.C.length)].join(""));};
$APP.g.Ra=function(a,b,c){return 0<=b&&b<this.C.length?b4(this.C[b],this.ca,this.R,this.transform):c};$APP.g.X=function(a,b,c){return $APP.Sk(b,$APP.Vk,"["," ","]",c,this)};$APP.g.zc=function(a,b,c){if(0<=b&&b<this.C.length)return g4(c,!0)?(a=$APP.$b(this.C),a[b]=c4(c),new a4(this.H,this.ca,this.R,this.transform,a,null)):$APP.Jc(e4(this.C),b,c);if(b===this.C.length)return this.na(null,c);throw Error(["Index ",$APP.m.g(b)," out of bounds  [0,",$APP.m.g(this.C.length),"]"].join(""));};
$APP.g.Pa=function(){return new j4(this.ca,this.R,this.transform,this.C,this.C.length)};$APP.g.T=function(){return this.H};$APP.g.ja=function(){return new a4(this.H,this.ca,this.R,this.transform,this.C,this.I)};$APP.g.ia=function(){return this.C.length};$APP.g.nd=function(){return 0<this.C.length?this.U(null,this.C.length-1):null};
$APP.g.od=function(){if(0===this.C.length)throw Error("Can't pop empty vector");if(1===this.C.length)return this.va(null);var a=$APP.$b(this.C);return new a4(this.H,this.ca,this.R,this.transform,a.slice(0,a.length-1),null)};$APP.g.md=function(){return 0<this.C.length?new $APP.Ke(this,this.C.length-1,null):null};$APP.g.da=function(){var a=this.I;return null!=a?a:this.I=a=$APP.le(this)};
$APP.g.P=function(a,b){a:if(b instanceof a4)if(this.C.length===$APP.Ge(b))for(a=this.Pa(null),b=$APP.Id(b);;)if(a.hasNext()){var c=a.next(),d=b.next();if(!$APP.x.h(c,d)){a=!1;break a}}else{a=!0;break a}else a=!1;else a=W3(this,b);return a};$APP.g.Ld=function(){return new fNa($APP.$b(this.C),this.ca,this.R,this.transform)};$APP.g.va=function(){return new a4(this.H,this.ca,this.R,this.transform,[],null)};$APP.g.Sa=function(a,b){return X3(this,b)};$APP.g.Qa=function(a,b,c){return Y3(this,b,c)};
$APP.g.ra=function(a,b,c){if("number"===typeof b)a=this.zc(null,b,c);else throw Error("Vector's key for assoc must be a number.");return a};$APP.g.vb=function(a,b){return $APP.rf(b)?0<=b&&b<this.C.length:!1};$APP.g.fa=function(){return 0<this.C.length?new k4(this.ca,this.R,this.transform,this.C,0,null):null};$APP.g.V=function(a,b){return b===this.H?this:new a4(b,this.ca,this.R,this.transform,this.C,this.I)};
$APP.g.na=function(a,b){return g4(b,!0)?(a=$APP.$b(this.C),a[a.length]=c4(b),new a4(this.H,this.ca,this.R,this.transform,a,null)):$APP.lc(e4(this.C),b)};$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length-1)].join(""));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.$b(b)))};$APP.g.g=function(a){return this.U(null,a)};
$APP.g.h=function(a,b){return this.Ra(null,a,b)};$APP.g.xc=function(a,b){if($APP.ff(b)){a=$APP.Ge(this);var c=$APP.Ge(b);if(a<c)b=-1;else if(a>c)b=1;else if(0===a)b=0;else a:for(c=0;;){var d=$APP.Cf($APP.A.h(this,c),$APP.A.h(b,c));if(0===d&&c+1<a)c+=1;else{b=d;break a}}return b}throw Error(["Cannot compare ",$APP.m.g(this)," to ",$APP.m.g(b)].join(""));};
var q4=function q4(a){switch(arguments.length){case 0:return q4.v();case 1:return q4.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return q4.l(arguments[0],1<c.length?new $APP.ce(c.slice(1),0,null):null)}};q4.v=function(){return new $3(null,{},$APP.Xk,l4,null,!1,[],0,null)};q4.g=function(a){return new $3(null,a,$APP.Xk,l4,null,!1,null,null,null)};
q4.l=function(a,b){var c=$APP.vh(b);b=$APP.C.h(c,$APP.gC);var d=$APP.C.h(c,jNa),e=$APP.C.h(c,o4),f=$APP.C.h(c,nNa);c=$APP.C.h(c,iNa);return!1===b?new $3(null,a,$APP.Mf,$APP.Mf,f,$APP.ub(c),null,null,null):null!=d&&null!=e?new $3(null,a,d,e,f,$APP.ub(c),null,null,null):new $3(null,a,$APP.Xk,l4,f,$APP.ub(c),null,null,null)};q4.A=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};q4.o=1;
var d4=function d4(a){switch(arguments.length){case 1:return d4.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return d4.l(arguments[0],1<c.length?new $APP.ce(c.slice(1),0,null):null)}};d4.g=function(a){return b4(a,$APP.Xk,l4,null)};d4.l=function(a,b){var c=$APP.vh(b);b=$APP.C.h(c,$APP.gC);var d=$APP.C.h(c,jNa),e=$APP.C.h(c,o4);c=$APP.C.h(c,nNa);return!1===b?b4(a,$APP.Mf,$APP.Mf,c):null!=d&&null!=e?b4(a,d,e,c):b4(a,$APP.Xk,l4,c)};
d4.A=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};d4.o=1;var r4=function r4(a){switch(arguments.length){case 1:return r4.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return r4.l(arguments[0],1<c.length?new $APP.ce(c.slice(1),0,null):null)}};r4.g=function(a){return a instanceof $3?a.oa:a instanceof a4?a.C:$APP.dC.l(a,$APP.B([$APP.eC,l4]))};
r4.l=function(a,b){if(a instanceof $3)return a.oa;if(a instanceof a4)return a.C;b=$APP.vh(b);b=$APP.C.j(b,o4,l4);return $APP.dC.l(a,$APP.B([$APP.eC,b]))};r4.A=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};r4.o=1;var s4=$APP.mV.h($APP.tI,null),sNa=new $APP.h(null,5,[mNa,function(){var a=new $APP.ae(function(){return q4},lNa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.YC,$APP.AO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.$I],[$APP.tI,mNa,"cljs_bean/core.cljs",11,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,1,$APP.UQ,1,$APP.lQ,new $APP.G(null,2,5,$APP.I,[$APP.oi,new $APP.G(null,1,5,$APP.I,[$APP.WN],null)],null),$APP.Z,$APP.J($APP.oi,new $APP.G(null,1,5,$APP.I,[$APP.WN],null),new $APP.G(null,3,5,$APP.I,[$APP.WN,$APP.jm,$APP.JK],
null)),$APP.UI,$APP.J(null,null,null)],null),1,702,702,$APP.J($APP.oi,new $APP.G(null,1,5,$APP.I,[$APP.WN],null),new $APP.G(null,3,5,$APP.I,[$APP.WN,$APP.jm,$APP.JK],null)),"Takes a JavaScript object and returns a read-only implementation of the map\n  abstraction backed by the object.\n\n  By default, bean produces beans that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :recursive true to create a bean which recursively converts\n  JavaScript object values to beans and JavaScript arrays into vectors.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.\n\n  Calling (bean) produces an empty bean.",
$APP.l(q4)?q4.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,s4,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),hNa,function(){var a=new $APP.ae(function(){return m4},kNa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.YC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.$I],[$APP.tI,hNa,"cljs_bean/core.cljs",
12,1,735,735,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.WN],null)),"Returns true if x is a bean.",$APP.l(m4)?m4.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,s4,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),$APP.OM,function(){var a=new $APP.ae(function(){return n4},pNa,$APP.Rj([$APP.W,$APP.O,
$APP.ao,$APP.YC,$APP.hp,$APP.bo,$APP.yS,$APP.Yo,$APP.Z,$APP.M,$APP.$I],[$APP.tI,$APP.OM,"cljs_bean/core.cljs",17,1,740,740,$APP.TF,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.yN],null)),"Takes a bean and returns a JavaScript object.",$APP.l(n4)?n4.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,s4,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:
$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),rNa,function(){var a=new $APP.ae(function(){return r4},gNa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.YC,$APP.AO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.$I],[$APP.tI,rNa,"cljs_bean/core.cljs",11,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,1,$APP.UQ,1,$APP.lQ,new $APP.G(null,1,5,$APP.I,[new $APP.G(null,1,5,$APP.I,[$APP.WN],null)],null),$APP.Z,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.WN],null),new $APP.G(null,3,5,$APP.I,[$APP.WN,$APP.jm,$APP.JK],null)),$APP.UI,
$APP.J(null,null)],null),1,775,775,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.WN],null),new $APP.G(null,3,5,$APP.I,[$APP.WN,$APP.jm,$APP.JK],null)),"Recursively converts ClojureScript values to JavaScript.\n\n  Where possible, directly returns the backing objects and arrays for values\n  produced using -\x3eclj and bean.\n\n  Otherwise delegates to clj-\x3ejs to perform the conversion, converting keyword\n  keys using their qualified names. You can alternatively supply :key-\x3eprop with\n  a function that controls the mapping from keys to properties.",
$APP.l(r4)?r4.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,s4,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),oNa,function(){var a=new $APP.ae(function(){return d4},qNa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.YC,$APP.AO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.$I],[$APP.tI,oNa,"cljs_bean/core.cljs",
12,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,1,$APP.UQ,1,$APP.lQ,new $APP.G(null,1,5,$APP.I,[new $APP.G(null,1,5,$APP.I,[$APP.WN],null)],null),$APP.Z,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.WN],null),new $APP.G(null,3,5,$APP.I,[$APP.WN,$APP.jm,$APP.JK],null)),$APP.UI,$APP.J(null,null)],null),1,745,745,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.WN],null),new $APP.G(null,3,5,$APP.I,[$APP.WN,$APP.jm,$APP.JK],null)),"Recursively converts JavaScript values to ClojureScript.\n\n  JavaScript objects are converted to beans with keywords for keys.\n\n  JavaScript arrays are converted to read-only implementations of the vector\n  abstraction, backed by the supplied array.\n\n  By default, -\x3eclj produces values that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.",
$APP.l(d4)?d4.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,s4,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}()],null);$APP.zy(new $APP.h(null,1,[$APP.Ut,new $APP.h(null,1,[$APP.tI,sNa],null)],null));