import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var uHa,vHa,wHa,F1,H1,I1,xHa,yHa,zHa,AHa,J1,BHa,L1,M1,N1,P1,R1,S1,CHa,T1,U1,V1,W1,X1,$1,a2,b2,DHa,d2,EHa,e2,f2,FHa,GHa,JHa,i2,j2,KHa,LHa,MHa,NHa,PHa,QHa,RHa,THa,r2,s2,YHa,ZHa,$Ha,aIa,bIa,cIa,fIa,t2,gIa,hIa,iIa,u2,kIa,v2,mIa,nIa,oIa,pIa,qIa,rIa,sIa,vIa,x2,yIa,zIa,y2,CIa,z2,A2,B2,C2,D2,E2,F2,G2,H2,I2,J2,DIa,EIa,n2,K2,FIa,GIa,HIa,IIa,JIa,KIa,wIa,LIa,MIa,NIa,OIa,PIa,QIa,L2,M2,RIa,N2,SIa,TIa,UIa,VIa,c2,WIa,XHa,XIa,YIa,G1,O2,ZIa,P2,dIa,$Ia,Z1,aJa,bJa,cJa,m2,dJa,eJa,fJa,gJa,hJa,iJa,jJa,o2,kJa,lJa,mJa,nJa,
oJa,BIa,pJa,qJa,rJa,sJa,tJa,uJa,vJa,R2,wJa,xJa,yJa,zJa,S2,AJa,BJa,T2,CJa,DJa,EJa,U2,V2,FJa,GJa,AIa,HJa,IJa,JJa,KJa,LJa,MJa,W2,NJa,OJa,PJa,p2,QJa,RJa,SJa,TJa,VHa,UJa,VJa,WJa;uHa=function(a){return 2>$APP.Ge(a)?$APP.dn(a):[$APP.dn($APP.Ok.j(a,0,1)),$APP.Ok.h(a,1)].join("")};vHa=function(a){if("string"===typeof a)return a;a=$APP.xk(a);var b=$APP.hn.h(a,/-/),c=$APP.u(b);b=$APP.v(c);c=$APP.w(c);return $APP.l(E1.g?E1.g(b):E1.call(null,b))?a:$APP.Oh.j($APP.m,b,$APP.Wk.h(uHa,c))};
wHa=function(a){var b=function(){var c=function(){var d=$APP.Se(a);if(d){d=a.displayName;if($APP.l(d))return d;d=a.name;return"string"===typeof d&&$APP.u(d)?d:null}return d}();if($APP.l(c))return c;c=function(){var d=null!=a?a.O&4096||$APP.Wd===a.Qe?!0:!1:!1;return d?$APP.xk(a):d}();if($APP.l(c))return c;c=$APP.Ve(a);return $APP.df(c)?$APP.O.g(c):null}();return $APP.l(b)?$APP.bn($APP.m.g(b),"$","."):null};F1=function(a){return a instanceof $APP.F||a instanceof $APP.t};
H1=function(a){if($APP.df(a))try{var b=$APP.C.h(a,G1)}catch(c){b=null}else b=null;return b};I1=function(a){var b=G1.g($APP.Ve(a));if($APP.l(b))return b;b=H1($APP.A.j(a,1,null));if($APP.l(b))return b;b=$APP.A.j(a,0,null);switch(b instanceof $APP.F?b.ga:null){case "\x3e":case "f\x3e":return H1($APP.A.j(a,2,null));case "r\x3e":return a=$APP.A.j(a,2,null),null==a?null:a.key;default:return null}};xHa=function(a){return setTimeout(a,16)};yHa=function(a,b){return a.yg-b.yg};zHa=function(){return null};
AHa=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.v?d.v():d.call(null);c+=1}else return null};J1=function(a,b,c){b.push(c);return a.schedule()};BHa=function(){this.Xf=!1};L1=function(a){if($APP.l(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return K1.queue_render(a)};M1=function(a){if(null!=a&&null!=a.ck)a=a.id;else{var b=M1[$APP.ja(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=M1._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.Xb("Compiler.get-id",a);}return a};
N1=function(a,b,c){if(null!=a&&null!=a.fi)a=a.fi(a,b,c);else{var d=N1[$APP.ja(null==a?null:a)];if(null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else if(d=N1._,null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else throw $APP.Xb("Compiler.parse-tag",a);}return a};
$APP.O1=function(a,b){if(null!=a&&null!=a.di)a=a.di(a,b);else{var c=$APP.O1[$APP.ja(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=$APP.O1._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.Xb("Compiler.as-element",a);}return a};
P1=function(a,b,c,d,e){if(null!=a&&null!=a.ei)a=a.ei(a,b,c,d,e);else{var f=P1[$APP.ja(null==a?null:a)];if(null!=f)a=f.M?f.M(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=P1._,null!=f)a=f.M?f.M(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.Xb("Compiler.make-element",a);}return a};R1=function(){return null!=Q1};
S1=function(a,b){b.hg=null;a:{var c=Q1;Q1=b;try{var d=a.v?a.v():a.call(null);break a}finally{Q1=c}d=void 0}a=b.hg;b.Od=!1;a:{c=b.re;var e=null==a?0:a.length,f=e===(null==c?0:c.length);if(f)for(f=0;;){var k=f===e;if(k){c=k;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}else c=f}c||b._update_watching(a);return d};CHa=function(a){var b=Q1;if(null!=b){var c=b.hg;null==c?b.hg=[a]:c.push(a)}};T1=function(a,b,c){a.rb=$APP.kk.j(a.rb,b,c);return a.Rg=null};
U1=function(a,b){a.rb=$APP.Un.h(a.rb,b);return a.Rg=null};V1=function(a,b,c){var d=a.Rg;d=null==d?a.Rg=$APP.Lf(function(r,p,y){r.push(p);r.push(y);return r},[],a.rb):d;for(var e=d.length,f=0;;)if(f<e){var k=d[f],n=d[f+1];n.B?n.B(k,a,b,c):n.call(null,k,a,b,c);f=2+f}else return null};W1=function(a,b,c,d){$APP.hd(a,["#object[reagent.ratom.",$APP.m.g(c)," "].join(""));a:{c=Q1;Q1=null;try{var e=d;break a}finally{Q1=c}e=void 0}$APP.Vk(e,a,b);return $APP.hd(a,"]")};
X1=function(a,b,c,d){this.state=a;this.H=b;this.bg=c;this.rb=d;this.G=2154201088;this.O=114690};$1=function(a,b,c,d,e){var f=b.Lg;f=null==f?$APP.th:f;var k=f.h?f.h(c,null):f.call(null,c,null);if(null!=k)return $APP.q(k);if(null==Q1)return a.v?a.v():a.call(null);k=function(){function r(p){var y=$APP.Un.h(b.Lg,c);b.Lg=y;null!=d&&(d.kf=null);return null!=e?e.g?e.g(p):e.call(null,p):null}return Y1.j?Y1.j(a,Z1,r):Y1.call(null,a,Z1,r)}();var n=$APP.q(k);b.Lg=$APP.kk.j(f,c,k);null!=d&&(d.kf=k);return n};
a2=function(a,b){this.f=a;this.Ke=b;this.kf=null;this.G=2153807872;this.O=0};b2=function(a,b){return new a2(a,b)};DHa=function(a,b){var c=b2(a,b);a=function(){function d(){return c.wa(null)}return Y1.j?Y1.j(d,c2,!0):Y1.call(null,d,c2,!0)}();$APP.q(a);return a};d2=function(a,b){this.xb=a;this.path=b;this.rb=this.state=this.kf=null;this.G=2153807872;this.O=114690};EHa=function(a){a=a.destroy;return null==a?null:a.v?a.v():a.call(null)};e2=function(a){var b=Q1;return null==b?[]:$1($APP.bc,b,a,null,EHa)};
f2=function(a){if(null!=a&&null!=a.Mg)a=a.Mg(a);else{var b=f2[$APP.ja(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=f2._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.Xb("IDisposable.dispose!",a);}return a};FHa=function(a,b,c,d){return a._handle_change(b,c,d)};GHa=function(a){this.f=a;this.state=null;this.Od=!0;this.zh=!1;this.ig=this.jd=this.rb=this.re=null;this.G=2153807872;this.O=114690};
$APP.h2=function(){for(;;){var a=g2;if(null==a)return null;g2=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}};JHa=function(a,b){var c=HHa,d=IHa,e=S1(a,d);null!=d.re&&(IHa=Y1(null),d._set_opts(c),d.f=a,d.jd=function(){return L1.g?L1.g(b):L1.call(null,b)},b.cljsRatom=d);return e};
i2=function(a,b){var c=b.argv;if(null==c){c=$APP.I;a=a.constructor;a:for(var d=$APP.Oa(b),e=d.length,f=$APP.th,k=0;;)if(k<e){var n=d[k];f=$APP.kk.j(f,$APP.Xk.g(n),$APP.Ua(b,n));k+=1}else break a;b=new $APP.G(null,2,5,c,[a,f],null)}else b=c;return b};j2=function(a){var b;if(b=$APP.Se(a))a=null==a?null:a.prototype,b=null!=(null==a?null:a.Qd);return b};KHa=function(a){var b;if(b=$APP.Se(a))a=null==a?null:a.prototype,b=null!=(null==a?null:a.render);return b};
LHa=function(a,b){for(;;){var c=a.Qd,d=!0===a.Wi?c.call(a,a):function(){var e=i2(a,a.props);switch($APP.Ge(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.A.h(e,1));case 3:return c.call(a,$APP.A.h(e,1),$APP.A.h(e,2));case 4:return c.call(a,$APP.A.h(e,1),$APP.A.h(e,2),$APP.A.h(e,3));case 5:return c.call(a,$APP.A.h(e,1),$APP.A.h(e,2),$APP.A.h(e,3),$APP.A.h(e,4));default:return c.apply(a,$APP.bw.g(e).slice(1))}}();if($APP.ff(d))return $APP.O1(b,d);if($APP.qf(d))a.Qd=j2(d)?function(e,f,k,n,r){return function(){function p(z){var E=
null;if(0<arguments.length){E=0;for(var H=Array(arguments.length-0);E<H.length;)H[E]=arguments[E+0],++E;E=new $APP.ce(H,0,null)}return y.call(this,E)}function y(z){return $APP.O1(f,$APP.Oh.j($APP.jA,r,z))}p.o=0;p.A=function(z){z=$APP.u(z);return y(z)};p.l=y;return p}()}(a,b,c,null,d):d;else return d}};MHa=function(a,b){var c=k2;k2=a;try{return LHa(a,b)}finally{k2=c}};
NHa=function(a,b){switch(a instanceof $APP.F?a.ga:null){case "getDefaultProps":throw Error("getDefaultProps not supported");case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;null!=f&&(c=$APP.A.j(f,1,null),c=$APP.df(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.Yi;d=null!=d?d:c.Yi=l2.g(null);return $APP.Sh(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,i2(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,
this,i2(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,this,i2(this,c))};case "shouldComponentUpdate":return function(c){if($APP.l(!1))return!1;var d=this.props.argv,e=c.argv,f=null==d||null==e;if(null==b){if(f)return f;try{return $APP.jk.h(d,e)}catch(k){return!1}}else return f?b.call(this,this,i2(this,this.props),i2(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,i2(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,
d){return b.call(this,this,i2(this,c),d)};case "componentDidUpdate":return function(c,d,e){return b.call(this,this,i2(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.Ua(this,"cljsRatom");null!=c&&f2(c);this.cljsIsDirty=!1;return null==b?null:b.call(this,this)};case "componentDidCatch":return function(c,
d){return b.call(this,this,c,d)};default:return null}};PHa=function(a){return $APP.Lf(function(b,c,d){return $APP.kk.j(b,$APP.Xk.g(OHa(c)),d)},$APP.th,a)};
QHa=function(a,b){var c=function(){var k=m2.g(a);return $APP.l(k)?k:n2.g(a)}(),d=null==m2.g(a),e=function(){var k=o2.g(a);if($APP.l(k))return k;k=wHa(c);return $APP.l(k)?k:$APP.m.g($APP.Tq.g("reagent"))}(),f=$APP.Lf(function(k,n,r){var p=$APP.kk.j,y=NHa(n,r);return p.call($APP.kk,k,n,$APP.l(y)?y:r)},$APP.th,a);return $APP.kk.l(f,o2,e,$APP.B([p2,d,m2,c,n2,function(){var k=this;if($APP.q2)return MHa(k,b);var n=$APP.Ua(k,"cljsRatom");k.cljsIsDirty=!1;return null==n?JHa(function(){return MHa(k,b)},k):
n._run(!1)}]))};RHa=function(a){return $APP.Lf(function(b,c,d){c=$APP.xk(c);b[c]=d;return b},{},a)};THa=function(a,b){return QHa($APP.Tn.l($APP.B([SHa,PHa(a)])),b)};
r2=function(a,b){function c(n,r,p){$APP.ny.nbb$internal$react.Component.call(this,n,r,p);$APP.l(k)&&(k.h?k.h(this,n):k.call(null,this,n));$APP.l(f)&&(this.state=f.g?f.g(this):f.call(null,this));this.yg=UHa+=1;return this}a=THa(a,b);b=RHa($APP.Oh.l($APP.Un,a,o2,VHa,$APP.Dw,$APP.B([n2,m2,WHa])));var d=RHa($APP.lk(a,WHa)),e=o2.g(a),f=VHa.g(a),k=$APP.Dw.g(a);$APP.$a(c.prototype,$APP.ny.nbb$internal$react.Component.prototype,b);$APP.l(n2.g(a))&&(c.prototype.render=n2.g(a));$APP.l(m2.g(a))&&(c.prototype.Qd=
m2.g(a));$APP.l(p2.g(a))&&(c.prototype.Wi=p2.g(a));$APP.$a(c,$APP.ny.nbb$internal$react.Component,d);$APP.l(e)&&(c.displayName=e,c.Ef=e,c.Vi=function(n){return $APP.hd(n,e)},Object.defineProperty(c,"name",{value:e,writable:!1}));c.ph=!0;return c.prototype.constructor=c};s2=function(a,b,c){a=M1(a);return b[a]=c};YHa=function(a,b){var c=$APP.Ua(a,M1(b));null==c?j2(a)?a=s2(b,a,a):(c=$APP.Ve(a),c=$APP.kk.j(c,XHa,a),c=r2(c,b),a=s2(b,a,c)):a=c;return a};
ZHa=function(a,b){for(;;){var c=b.Qd,d=b.argv,e=$APP.Oh.h(c,d);if($APP.ff(e))return $APP.O1(a,e);if($APP.qf(e))b.Qd=j2(e)?function(f,k,n,r,p,y){return function(){function z(H){var P=null;if(0<arguments.length){P=0;for(var V=Array(arguments.length-0);P<V.length;)V[P]=arguments[P+0],++P;P=new $APP.ce(V,0,null)}return E.call(this,P)}function E(H){return $APP.O1(f,$APP.Oh.j($APP.jA,y,H))}z.o=0;z.A=function(H){H=$APP.u(H);return E(H)};z.l=E;return z}()}(a,b,c,null,d,e):e;else return e}};
$Ha=function(a,b){var c=k2;k2=b;try{return ZHa(a,b)}finally{k2=c}};
aIa=function(a,b){if($APP.q2)return $Ha(a,b);var c=b.argv,d=b.Qd;b=$APP.ny.nbb$internal$react.useState(0);$APP.A.j(b,0,null);var e=$APP.A.j(b,1,null),f=$APP.ny.nbb$internal$react.useRef();$APP.l(f.current)||function(){var n={forceUpdate:function(){return e.g?e.g($APP.qe):e.call(null,$APP.qe)}};n.yg=UHa+=1;n.constructor=d;n.Qd=d;return f.current=n}();var k=f.current;b=$APP.Ua(k,"cljsRatom");$APP.ny.nbb$internal$react.useEffect(function(){return function(){var n=$APP.Ua(k,"cljsRatom");return null==
n?null:f2(n)}},[]);k.argv=c;k.cljsIsDirty=!1;return null==b?JHa(function(){return $Ha(a,k)},k):b._run(!1)};bIa=function(a,b){a=a.argv;b=b.argv;try{return $APP.x.h(a,b)}catch(c){return!1}};cIa=function(a,b){function c(e){return aIa(a,e)}var d=$APP.Ua(b,M1(a));if($APP.l(d))return d;d=wHa(b);c.displayName=d;Object.defineProperty(c,"name",{value:d,writable:!1});d=$APP.ny.nbb$internal$react.memo(c,bIa);s2(a,b,d);return d};
fIa=function(a,b,c,d){var e=$APP.vh($APP.th);e=$APP.C.h(e,dIa);if(a===document.activeElement&&$APP.zf(eIa,a.type)&&"string"===typeof b&&"string"===typeof c){var f=a.value;if($APP.jk.h(f,c))return K1.add_after_render(function(){return t2.g?t2.g(d):t2.call(null,d)});c=$APP.Ge(f)-a.selectionStart;c=$APP.Ge(b)-c;d.Ff=b;a.value=b;$APP.Se(e)&&(e.g?e.g(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.Ff=b;a.value=b;return $APP.Se(e)?e.g?e.g(b):e.call(null,b):null};
t2=function(a){if($APP.l(a.xg)){a.sh=!1;var b=a.Xi,c=a.Ff,d=a.Dg;return $APP.jk.h(b,c)?fIa(d,b,c,a):null}return null};gIa=function(a,b,c){a.Ff=c.target.value;$APP.l(a.sh)||(a.sh=!0,K1.add_after_render(function(){return t2(a)}));return b.g?b.g(c):b.call(null,c)};
hIa=function(a){var b=k2;if($APP.l(function(){var f=null!=a;return f?(f=a.hasOwnProperty("onChange"),$APP.l(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=null==c?"":c;var d=a.onChange,e=a.ref;$APP.l(b.xg)||(b.xg=!0,b.Ff=c);$APP.l(b.gi)||(b.gi=$APP.Se(e)?function(f){b.Dg=f;return e.g?e.g(f):e.call(null,f)}:$APP.l($APP.l(e)?e.hasOwnProperty("current"):e)?function(f){b.Dg=f;return e.current=f}:function(f){return b.Dg=f});b.Xi=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return gIa(b,
d,f)};a.ref=b.gi}};iIa=function(a){this.tag=a;this.className=this.id=null};u2=function(a,b){return a.hasOwnProperty(b)?$APP.Ua(a,b):null};kIa=function(a,b,c){if(F1(b)){var d=u2(jIa,$APP.xk(b));null==d?(d=vHa(b),b=$APP.xk(b),b=jIa[b]=d):b=d}c=v2.g?v2.g(c):v2.call(null,c);a[b]=c;return a};
v2=function(a){return"object"!==$APP.ja(a)?a:F1(a)?$APP.xk(a):$APP.df(a)?$APP.Lf(kIa,{},a):$APP.Ze(a)?$APP.dC(a):$APP.qf(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.ce(f,0,null)}return c.call(this,e)}function c(d){return $APP.Oh.h(a,d)}b.o=0;b.A=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}():$APP.dC(a)};
mIa=function(a,b,c){if(F1(b)){var d=u2(lIa,$APP.xk(b));null==d?(d=vHa(b),b=$APP.xk(b),b=lIa[b]=d):b=d}c=v2(c);a[b]=c;return a};
nIa=function(a){return"object"!==$APP.ja(a)?a:F1(a)?$APP.xk(a):$APP.df(a)?$APP.Lf(mIa,{},a):$APP.Ze(a)?$APP.dC(a):$APP.qf(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.ce(f,0,null)}return c.call(this,e)}function c(d){return $APP.Oh.h(a,d)}b.o=0;b.A=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}():$APP.dC(a)};
oIa=function(a,b,c,d,e){switch($APP.Ge(b)-e){case 0:return $APP.ny.nbb$internal$react.createElement(c,d);case 1:return $APP.ny.nbb$internal$react.createElement(c,d,$APP.O1(a,$APP.A.j(b,e,null)));default:return $APP.ny.nbb$internal$react.createElement.apply(null,$APP.Lf(function(f,k,n){k>=e&&f.push($APP.O1(a,n));return f},[c,d],b))}};pIa=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.cj=d};
qIa=function(a,b,c){a=YHa(a,c);c={};c.argv=b;b=I1(b);null!=b&&(c.key=b);return $APP.ny.nbb$internal$react.createElement(a,c)};rIa=function(a,b,c,d){var e={};e.Qd=a;e.argv=$APP.gn.h(b,c);b=I1(b);null!=b&&(e.key=b);return $APP.ny.nbb$internal$react.createElement(cIa(d,a),e)};sIa=function(a,b,c){return KHa(a)?qIa(a,b,c):rIa(a,b,1,c)};
vIa=function(a,b){a=u2(tIa,b);if(null==a){var c=$APP.w($APP.Kk(uIa,$APP.xk(b)));a=$APP.A.j(c,0,null);var d=$APP.A.j(c,1,null);c=$APP.A.j(c,2,null);c=null==c?null:$APP.bn(c,/\./," ");var e=$APP.jk.h(-1,a.indexOf("-"));a=new pIa(a,d,c,e);return tIa[b]=a}return a};
x2=function(a,b,c,d){var e=a.tag,f=$APP.A.j(b,c,null),k=null==f||$APP.df(f),n=function(){var y=k?f:null;var z=$APP.kv.g(y);z=$APP.l(z)?$APP.kk.j(y,$APP.kv,w2.g(z)):y;var E=a.id;y=a.className;E=null!=E&&null==$APP.Pt.g(z)?$APP.kk.j(z,$APP.Pt,E):z;if($APP.l(y)){var H=$APP.kk.j,P=w2.h,V=$APP.kv.g(z);z=$APP.l(V)?V:wIa.g(z);y=H.call($APP.kk,E,$APP.kv,P.call(w2,y,z))}else y=E;y=$APP.l(a.cj)?nIa(y):v2(y);return $APP.l(y)?y:{}}();c+=k?1:0;a:switch(e){case "input":case "textarea":var r=!0;break a;default:r=
!1}if(r){r=H1(f);var p=function(){var y=d.dk;if($APP.l(y))return y;y=r2(xIa,d);return d.dk=y}();return $APP.O1(d,$APP.Ue(new $APP.G(null,6,5,$APP.I,[p,b,e,n,c,d],null),$APP.Tn.l($APP.B([$APP.l(r)?new $APP.h(null,1,[G1,r],null):null,$APP.Ve(b)]))))}r=H1($APP.Ve(b));null!=r&&(n.key=r);return P1(d,b,e,n,c)};yIa=function(a,b){return $APP.bw.g($APP.Wk.h(function(c){return $APP.O1(b,c)},a))};
zIa=function(a,b,c){null==b&&console.error("vec-to-elem",$APP.tl.l($APP.B([a])));var d=$APP.A.j(a,0,null);switch(d instanceof $APP.F?d.ga:null){case "\x3e":return c=$APP.A.j(a,1,null),x2(new pIa(c,null,null,null),a,2,b);case "r\x3e":c=$APP.A.j(a,1,null);d=$APP.A.j(a,2,null);d=$APP.l(d)?d:{};var e=H1($APP.Ve(a));null!=e&&(d.key=e);return P1(b,a,c,d,3);case "f\x3e":return rIa($APP.A.j(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.A.j(a,1,null),c=null==d||$APP.df(d),d=v2(c?d:null),d=$APP.l(d)?d:{},
c=1+(c?1:0),e=I1(a),null!=e&&(d.key=e),P1(b,a,$APP.ny.nbb$internal$react.Fragment,d,c);default:if(F1(d)||"string"===typeof d)a:for(;;)switch(c=$APP.A.j(a,0,null),d=$APP.xk(c),e=d.indexOf("\x3e"),e){case -1:b=x2(N1(b,d,c),a,1,b);break a;case 0:b=null;break a;default:a=$APP.Ue(new $APP.G(null,2,5,$APP.I,[$APP.Ok.j(d,0,e),$APP.kk.j($APP.Ue(a,null),0,$APP.Ok.h(d,e+1))],null),$APP.Ve(a))}else b=d instanceof iIa?x2(d,a,1,b):c.j?c.j(d,a,b):c.call(null,d,a,b);return b}};
y2=function(a,b,c,d,e){this.oc=a;this.id=b;this.vh=c;this.Rf=d;this.Oj=e;this.G=393216;this.O=0};CIa=function(a){var b=$APP.Tq.g("reagent-compiler"),c=$APP.l(AIa.g(a))?sIa:qIa,d=$APP.C.j(a,BIa,vIa);return new y2(a,b,c,d,$APP.th)};z2=function(a){return new iIa(a)};A2=function(a){return f2(a)};B2=function(a,b){return new d2(a,b)};C2=function(a){return CIa(a)};D2=function(){return Q1};E2=function(a){return a.generation};F2=function(a){return a.ratomGeneration};G2=function(a,b){return a.generation=b.ratomGeneration};
H2=function(a,b){return a.destroy=b};I2=function(a){return a.destroy};J2=function(){return!1};DIa=new $APP.t(null,"-generation","-generation",627658965,null);EIa=new $APP.t("reagent.ratom","track!","reagent.ratom/track!",1183599982,null);n2=new $APP.F(null,"render","render",-1408033454);K2=new $APP.t(null,"on-set","on-set",1499578057,null);FIa=new $APP.t("reagent.core","adapt-react-class","reagent.core/adapt-react-class",1789410154,null);
GIa=new $APP.t("reagent.ratom","make-reaction","reagent.ratom/make-reaction",272608527,null);HIa=new $APP.t(null,"dispose!","dispose!",-395693497,null);IIa=new $APP.t("reagent.ratom","-destroy","reagent.ratom/-destroy",-1284026419,null);JIa=new $APP.t("reagent.core","create-compiler","reagent.core/create-compiler",491047088,null);KIa=new $APP.F(null,"componentWillUnmount","componentWillUnmount",1573788814);wIa=new $APP.F(null,"className","className",-1983287057);
LIa=new $APP.t(null,"-tracking?","-tracking?",-1106885352,null);MIa=new $APP.t(null,"with-let","with-let",-1310113408,null);NIa=new $APP.t(null,"with-let-values","with-let-values",1929572375,null);OIa=new $APP.t(null,"create-class","create-class",-665911586,null);PIa=new $APP.F(null,"childContextTypes","childContextTypes",578717991);QIa=new $APP.t("reagent.core","atom","reagent.core/atom",1748890217,null);L2=new $APP.t(null,"class2","class2",-1266396392,null);
M2=new $APP.t(null,"class1","class1",-1905977651,null);RIa=new $APP.t("reagent.core","cursor","reagent.core/cursor",-1137097804,null);N2=new $APP.t(null,"auto-run","auto-run",-696035332,null);SIa=new $APP.t(null,"-set-ratom-generation!","-set-ratom-generation!",-1545989828,null);TIa=new $APP.t("sci.configs.reagent.reagent","-ratom-context","sci.configs.reagent.reagent/-ratom-context",270989566,null);
UIa=new $APP.t("sci.configs.reagent.reagent","-destroy","sci.configs.reagent.reagent/-destroy",-1999711192,null);VIa=new $APP.t(null,"-destroy","-destroy",-557272508,null);c2=new $APP.F(null,"auto-run","auto-run",1958400437);WIa=new $APP.t(null,"track-console","track-console",17070495,null);XHa=new $APP.F(null,"reagent-render","reagent-render",-985383853);XIa=new $APP.F(null,"contextTypes","contextTypes",-2023853910);YIa=new $APP.t(null,"create-compiler","create-compiler",1059333141,null);
G1=new $APP.F(null,"key","key",-1516042587);O2=new $APP.t(null,"props","props",2093813254,null);ZIa=new $APP.t(null,"reaction","reaction",2131401315,null);P2=new $APP.F(null,"on-set","on-set",-140953470);dIa=new $APP.F(null,"on-write","on-write",31519475);$Ia=new $APP.t(null,"reactive?","reactive?",1213887990,null);Z1=new $APP.F(null,"on-dispose","on-dispose",2105306360);$APP.Q2=new $APP.t(null,"compiler","compiler",1372604796,null);
aJa=new $APP.t("reagent.ratom","-destroy!","reagent.ratom/-destroy!",-337873850,null);bJa=new $APP.t(null,"-destroy!","-destroy!",143253949,null);cJa=new $APP.t("sci.configs.reagent.reagent","error","sci.configs.reagent.reagent/error",1433174531,null);m2=new $APP.F(null,"reagentRender","reagentRender",-358306383);dJa=new $APP.t("reagent.core","reactify-component","reagent.core/reactify-component",-385504376,null);eJa=new $APP.t(null,"cursor","cursor",-1642498285,null);
fJa=new $APP.t(null,"make-reaction","make-reaction",1935680112,null);gJa=new $APP.F(null,"contextType","contextType",1033066077);hJa=new $APP.t("reagent.core","dispose!","reagent.core/dispose!",239740642,null);iJa=new $APP.F(null,"component-did-update","component-did-update",-1468549173);jJa=new $APP.t(null,"src","src",-10544524,null);o2=new $APP.F(null,"displayName","displayName",-809144601);
kJa=new $APP.t("sci.configs.reagent.reagent","-generation","sci.configs.reagent.reagent/-generation",-1754580423,null);lJa=new $APP.F(null,"display-name","display-name",694513143);mJa=new $APP.t("sci.configs.reagent.reagent","reaction","sci.configs.reagent.reagent/reaction",-1324858361,null);nJa=new $APP.t(null,"others","others",-569561186,null);oJa=new $APP.F(null,"getDerivedStateFromProps","getDerivedStateFromProps",-991834739);BIa=new $APP.F(null,"parse-tag","parse-tag",1427313738);
pJa=new $APP.t("sci.configs.reagent.reagent","-ratom-generation","sci.configs.reagent.reagent/-ratom-generation",662254794,null);qJa=new $APP.t(null,"destroy","destroy",796871122,null);rJa=new $APP.F(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);sJa=new $APP.t("reagent.core","track!","reagent.core/track!",-954652078,null);tJa=new $APP.t("reagent.core","as-element","reagent.core/as-element",-1369748434,null);
uJa=new $APP.t(null,"-ratom-generation","-ratom-generation",-176468250,null);vJa=new $APP.t("reagent.core","create-class","reagent.core/create-class",-1100017147,null);R2=new $APP.t(null,"adapt-react-class","adapt-react-class",1221068673,null);wJa=new $APP.t("reagent.ratom","make-track","reagent.ratom/make-track",267038680,null);xJa=new $APP.t(null,"track","track",1836319014,null);yJa=new $APP.t(null,".hasOwnProperty",".hasOwnProperty",-1264659034,null);
zJa=new $APP.t("sci.configs.reagent.reagent","-tracking?","sci.configs.reagent.reagent/-tracking?",201600244,null);S2=new $APP.t(null,"reagent.debug","reagent.debug",1010511129,null);AJa=new $APP.t(null,"reactify-component","reactify-component",-882526483,null);BJa=new $APP.t("js","console","js/console",-1426368245,null);T2=new $APP.t(null,"sci.configs.reagent.reagent","sci.configs.reagent.reagent",94604865,null);
CJa=new $APP.t("sci.configs.reagent.reagent","-destroy!","sci.configs.reagent.reagent/-destroy!",-561262631,null);DJa=new $APP.F(null,"no-cache","no-cache",1588056370);EJa=new $APP.t("cljs.core","zero?","cljs.core/zero?",-341242858,null);U2=new $APP.t(null,"track!","track!",-516308489,null);V2=new $APP.t(null,"destroy__37521__auto__","destroy__37521__auto__",605566396,null);FJa=new $APP.t(null,".error",".error",1756007195,null);
GJa=new $APP.t("reagent.debug","-tracking?","reagent.debug/-tracking?",409956583,null);AIa=new $APP.F(null,"function-components","function-components",1492814963);HJa=new $APP.t("reagent.ratom","reactive?","reagent.ratom/reactive?",-358553475,null);IJa=new $APP.t(null,"as-element","as-element",-2139409597,null);JJa=new $APP.t(null,"make-track","make-track",-1388299455,null);KJa=new $APP.t("reagent.ratom","atom","reagent.ratom/atom",-391081187,null);
LJa=new $APP.t("reagent.debug","track-console","reagent.debug/track-console",-1553126476,null);MJa=new $APP.t("reagent.core","create-element","reagent.core/create-element",-1888667366,null);W2=new $APP.t(null,"on-dispose","on-dispose",-549129409,null);NJa=new $APP.F(null,"component-will-unmount","component-will-unmount",-2058314698);OJa=new $APP.t("reagent.ratom","with-let-values","reagent.ratom/with-let-values",-575838306,null);PJa=new $APP.t(null,"-ratom-context","-ratom-context",1646839514,null);
p2=new $APP.F(null,"cljsLegacyRender","cljsLegacyRender",-1527295613);QJa=new $APP.t("sci.configs.reagent.reagent","-set-ratom-generation!","sci.configs.reagent.reagent/-set-ratom-generation!",-35374248,null);RJa=new $APP.t("sci.configs.reagent.reagent","with-let","sci.configs.reagent.reagent/with-let",65759084,null);SJa=new $APP.t("reagent.core","class-names","reagent.core/class-names",-1902681251,null);TJa=new $APP.t(null,"class-names","class-names",-1397320704,null);
VHa=new $APP.F(null,"getInitialState","getInitialState",1541760916);UJa=new $APP.t("reagent.core","track","reagent.core/track",1263921785,null);VJa=new $APP.F(null,"getDerivedStateFromError","getDerivedStateFromError",166658477);WJa=new $APP.t(null,"create-element","create-element",1833774591,null);var XJa=$APP.xl.g(null),X2=function(){var a={};a.warn=function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.ce(f,0,null)}return c.call(this,e)}function c(d){return $APP.yl.l(XJa,$APP.Rn,new $APP.G(null,1,5,$APP.I,[$APP.Ura],null),$APP.Ng,$APP.B([$APP.Oh.h($APP.m,d)]))}b.o=0;b.A=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}();a.error=function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=
Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.ce(f,0,null)}return c.call(this,e)}function c(d){return $APP.yl.l(XJa,$APP.Rn,new $APP.G(null,1,5,$APP.I,[$APP.sq],null),$APP.Ng,$APP.B([$APP.Oh.h($APP.m,d)]))}b.o=0;b.A=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}();return a}();var YJa,E1,w2;YJa="undefined"!==typeof window&&null!=window.document;$APP.q2=!1;E1=new $APP.nk(null,new $APP.h(null,2,["aria",null,"data",null],null),null);w2=function w2(a){switch(arguments.length){case 0:return w2.v();case 1:return w2.g(arguments[0]);case 2:return w2.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return w2.l(arguments[0],arguments[1],2<c.length?new $APP.ce(c.slice(2),0,null):null)}};w2.v=function(){return null};
w2.g=function(a){return $APP.Ze(a)?(a=$APP.aq.h(function(b){return $APP.l(b)?F1(b)?$APP.xk(b):b:null},a),$APP.u(a)?$APP.Tp.h(" ",a):null):F1(a)?$APP.xk(a):a};w2.h=function(a,b){return $APP.l(a)?$APP.l(b)?[$APP.m.g(w2.g(a))," ",$APP.m.g(w2.g(b))].join(""):w2.g(a):w2.g(b)};w2.l=function(a,b,c){return $APP.If.j(w2,w2.h(a,b),c)};w2.A=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};w2.o=2;var UHa=0,Y2=YJa?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.l(b))return b;b=a.webkitRequestAnimationFrame;if($APP.l(b))return b;b=a.mozRequestAnimationFrame;if($APP.l(b))return b;b=a.msRequestAnimationFrame;return $APP.l(b)?b:xHa}().bind(a)}():xHa;$APP.g=BHa.prototype;$APP.g.flush_after_render=function(){var a=this.tf;if(null==a)return null;this.tf=null;return AHa(a)};
$APP.g.queue_render=function(a){null==this.componentQueue&&(this.componentQueue=[]);return J1(this,this.componentQueue,a)};$APP.g.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.Xf)return null;this.Xf=!0;return Y2.g?Y2.g(a):Y2.call(null,a)};$APP.g.flush_before_flush=function(){var a=this.wf;if(null==a)return null;this.wf=null;return AHa(a)};$APP.g.flush_queues=function(){this.flush_before_flush();zHa();this.flush_render();return this.flush_after_render()};
$APP.g.run_queues=function(){this.Xf=!1;return this.flush_queues()};$APP.g.add_before_flush=function(a){null==this.wf&&(this.wf=[]);return J1(this,this.wf,a)};$APP.g.add_after_render=function(a){null==this.tf&&(this.tf=[]);return J1(this,this.tf,a)};$APP.g.flush_render=function(){var a=this.componentQueue;if(null==a)return null;this.componentQueue=null;a:{a.sort(yHa);for(var b=a.length,c=0;;)if(c<b){var d=a[c];!0===d.cljsIsDirty&&d.forceUpdate();c+=1}else break a}return null};var K1=new BHa;var Q1;$APP.xl.g(0);var g2=null;$APP.g=X1.prototype;$APP.g.X=function(a,b,c){return W1(b,c,"RAtom",new $APP.h(null,1,[$APP.Nx,this.wa(null)],null))};$APP.g.T=function(){return this.H};$APP.g.da=function(){return $APP.ta(this)};$APP.g.P=function(a,b){return this===b};$APP.g.ec=function(a,b){a=this.state;this.state=b;null!=this.rb&&V1(this,a,b);return b};$APP.g.zf=function(a,b){return this.ec(null,b.g?b.g(this.state):b.call(null,this.state))};
$APP.g.Af=function(a,b,c){return this.ec(null,b.h?b.h(this.state,c):b.call(null,this.state,c))};$APP.g.Bf=function(a,b,c,d){return this.ec(null,b.j?b.j(this.state,c,d):b.call(null,this.state,c,d))};$APP.g.Cf=function(a,b,c,d,e){return this.ec(null,$APP.Oh.M(b,this.state,c,d,e))};$APP.g.Te=function(a,b){V1(this,a,b)};$APP.g.ye=function(a,b,c){return T1(this,b,c)};$APP.g.ze=function(a,b){return U1(this,b)};$APP.g.V=function(a,b){return new X1(this.state,b,this.bg,this.rb)};
$APP.g.wa=function(){CHa(this);return this.state};var l2=function l2(a){switch(arguments.length){case 1:return l2.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return l2.l(arguments[0],1<c.length?new $APP.ce(c.slice(1),0,null):null)}};l2.g=function(a){return new X1(a,null,null,null)};l2.l=function(a,b){var c=$APP.vh(b);b=$APP.C.h(c,$APP.yb);c=$APP.C.h(c,$APP.eha);return new X1(a,b,c,null)};
l2.A=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};l2.o=1;a2.prototype.wa=function(){var a=this,b=a.kf;return null==b?$1(function(){return $APP.Oh.h(a.f,a.Ke)},a.f,a.Ke,this,null):$APP.q(b)};a2.prototype.P=function(a,b){return b instanceof a2&&$APP.x.h(this.f,b.f)&&$APP.x.h(this.Ke,b.Ke)};a2.prototype.da=function(){return $APP.Xd(new $APP.G(null,2,5,$APP.I,[this.f,this.Ke],null))};
a2.prototype.X=function(a,b,c){return W1(b,c,"Track",new $APP.h(null,2,[$APP.Nx,this.wa(null),$APP.KR,this.f],null))};var Z2=function Z2(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Z2.l(arguments[0],1<c.length?new $APP.ce(c.slice(1),0,null):null)};Z2.l=function(a,b){return DHa(a,b)};Z2.o=1;Z2.A=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};$APP.g=d2.prototype;
$APP.g._peek=function(){var a=Q1;Q1=null;try{return this.wa(null)}finally{Q1=a}};$APP.g._set_state=function(a,b){if(a===b)return null;this.state=b;return null!=this.rb?V1(this,a,b):null};$APP.g.X=function(a,b,c){return W1(b,c,"RCursor",new $APP.h(null,2,[$APP.Nx,this.wa(null),$APP.sv,this.path],null))};$APP.g.da=function(){return $APP.Xd(new $APP.G(null,2,5,$APP.I,[this.xb,this.path],null))};$APP.g.P=function(a,b){return b instanceof d2&&$APP.x.h(this.path,b.path)&&$APP.x.h(this.xb,b.xb)};
$APP.g.ec=function(a,b){this._set_state(this.state,b);(null!=this.xb?this.xb.G&32768||$APP.Wd===this.xb.Yd||(this.xb.G?0:$APP.Vb($APP.Kc,this.xb)):$APP.Vb($APP.Kc,this.xb))?$APP.x.h(this.path,$APP.oi)?$APP.Sh(this.xb,b):$APP.yl.B(this.xb,$APP.Vt,this.path,b):this.xb.h?this.xb.h(this.path,b):this.xb.call(null,this.path,b);return b};$APP.g.zf=function(a,b){a=this.ec;var c=this._peek();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};
$APP.g.Af=function(a,b,c){a=this.ec;var d=this._peek();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.Bf=function(a,b,c,d){a=this.ec;var e=this._peek();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};$APP.g.Cf=function(a,b,c,d,e){return this.ec(null,$APP.Oh.M(b,this._peek(),c,d,e))};$APP.g.Te=function(a,b){V1(this,a,b)};$APP.g.ye=function(a,b,c){return T1(this,b,c)};$APP.g.ze=function(a,b){return U1(this,b)};
$APP.g.wa=function(){var a=this,b=this,c=a.state,d=function(){var e=a.kf;return null==e?$1((null!=a.xb?a.xb.G&32768||$APP.Wd===a.xb.Yd||(a.xb.G?0:$APP.Vb($APP.Kc,a.xb)):$APP.Vb($APP.Kc,a.xb))?function(){return $APP.ys.h($APP.q(a.xb),a.path)}:function(){return a.xb.g?a.xb.g(a.path):a.xb.call(null,a.path)},a.xb,a.path,b,null):$APP.q(e)}();b._set_state(c,d);return d};$APP.g=GHa.prototype;$APP.g._peek_at=function(){var a=Q1;Q1=null;try{return this.wa(null)}finally{Q1=a}};
$APP.g._handle_change=function(a,b,c){return b===c||this.Od?null:null==this.jd?(this.Od=!0,null==g2&&(g2=[],!1===K1.Xf&&K1.schedule()),g2.push(this)):!0===this.jd?this._run(!1):this.jd.g?this.jd.g(this):this.jd.call(null,this)};
$APP.g._update_watching=function(a){var b=$APP.vk(a),c=$APP.vk(this.re);this.re=a;a=$APP.u($APP.qT.h(b,c));for(var d=null,e=0,f=0;;)if(f<e){var k=d.U(null,f);$APP.ld(k,this,FHa);f+=1}else if(a=$APP.u(a))d=a,$APP.gf(d)?(a=$APP.yd(d),f=$APP.zd(d),d=a,e=$APP.Ge(a),a=f):(a=$APP.v(d),$APP.ld(a,this,FHa),a=$APP.w(d),d=null,e=0),f=0;else break;b=$APP.u($APP.qT.h(c,b));c=null;for(e=d=0;;)if(e<d)a=c.U(null,e),$APP.md(a,this),e+=1;else if(b=$APP.u(b))c=b,$APP.gf(c)?(b=$APP.yd(c),d=$APP.zd(c),c=b,a=$APP.Ge(b),
b=d,d=a):(a=$APP.v(c),$APP.md(a,this),b=$APP.w(c),c=null,d=0),e=0;else return null};$APP.g._queued_run=function(){return this.Od&&null!=this.re?this._run(!0):null};$APP.g._try_capture=function(a){try{return this.ig=null,S1(a,this)}catch(b){return this.ig=this.state=a=b,this.Od=!1}};$APP.g._run=function(a){var b=this.state;a=$APP.l(a)?this._try_capture(this.f):S1(this.f,this);this.zh||(this.state=a,null==this.rb||$APP.x.h(b,a)||V1(this,b,a));return a};
$APP.g._set_opts=function(a){var b=$APP.vh(a);a=$APP.C.h(b,c2);var c=$APP.C.h(b,P2),d=$APP.C.h(b,Z1);b=$APP.C.h(b,DJa);null!=a&&(this.jd=a);null!=c&&(this.Vj=c);null!=d&&(this.Bh=d);return null!=b?this.zh=b:null};$APP.g.X=function(a,b,c){return W1(b,c,"Reaction",new $APP.h(null,1,[$APP.Nx,this.wa(null)],null))};$APP.g.da=function(){return $APP.ta(this)};$APP.g.P=function(a,b){return this===b};
$APP.g.Mg=function(){var a=this.state,b=this.re;this.jd=this.state=this.re=null;this.Od=!0;b=$APP.u($APP.vk(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.U(null,e);$APP.md(f,this);e+=1}else if(b=$APP.u(b))c=b,$APP.gf(c)?(b=$APP.yd(c),e=$APP.zd(c),c=b,d=$APP.Ge(b),b=e):(b=$APP.v(c),$APP.md(b,this),b=$APP.w(c),c=null,d=0),e=0;else break;null!=this.Bh&&this.Bh(a);a=this.Vk;if(null==a)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.g?d.g(this):d.call(null,this),c+=1;else return null};
$APP.g.ec=function(a,b){a=this.state;this.state=b;this.Vj(a,b);V1(this,a,b);return b};$APP.g.zf=function(a,b){a=this.ec;var c=this._peek_at();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};$APP.g.Af=function(a,b,c){a=this.ec;var d=this._peek_at();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.Bf=function(a,b,c,d){a=this.ec;var e=this._peek_at();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.g.Cf=function(a,b,c,d,e){return this.ec(null,$APP.Oh.M(b,this._peek_at(),c,d,e))};$APP.g.Te=function(a,b){V1(this,a,b)};$APP.g.ye=function(a,b,c){return T1(this,b,c)};$APP.g.ze=function(a,b){a=$APP.Ye(this.rb);U1(this,b);return!a&&$APP.Ye(this.rb)&&null==this.jd?this.Mg(null):null};
$APP.g.wa=function(){var a=this.ig;if(null!=a)throw a;(a=null==Q1)&&($APP.h2.v?$APP.h2.v():$APP.h2.call(null));a&&null==this.jd?this.Od&&(a=this.state,this.state=this.f.v?this.f.v():this.f.call(null),null==this.rb||$APP.x.h(a,this.state)||V1(this,a,this.state)):(CHa(this),this.Od&&this._run(!1));return this.state};zHa=$APP.h2;var Y1=function Y1(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Y1.l(arguments[0],1<c.length?new $APP.ce(c.slice(1),0,null):null)};
Y1.l=function(a,b){var c=$APP.vh(b);b=$APP.C.h(c,c2);var d=$APP.C.h(c,P2);c=$APP.C.h(c,Z1);a=new GHa(a);a._set_opts(new $APP.h(null,3,[c2,b,P2,d,Z1,c],null));return a};Y1.o=1;Y1.A=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var IHa=Y1(null);var k2,HHa=new $APP.h(null,1,[DJa,!0],null),SHa=new $APP.h(null,2,[rJa,null,KIa,null],null),OHa=function(a){var b=$APP.xl.g($APP.th);return function(c){var d=$APP.C.h($APP.q(b),c);if(null!=d)return d;d=a.g?a.g(c):a.call(null,c);$APP.yl.B(b,$APP.kk,c,d);return d}}(function(a){if("string"===typeof a)return a;a=$APP.xk(a);a=$APP.bn(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.hn.h(a,/-/);var b=$APP.u(a);a=$APP.v(b);b=$APP.w(b);return $APP.Oh.j($APP.m,a,$APP.Wk.h(uHa,b))}),WHa=new $APP.G(null,5,5,$APP.I,
[PIa,XIa,gJa,oJa,VJa],null);var eIa=new $APP.nk(null,new $APP.h(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),xIa=new $APP.h(null,4,[lJa,"ReagentInput",iJa,t2,NJa,function(a){return a.xg=null},XHa,function(a,b,c,d,e){hIa(c);return P1(e,a,b,c,d)}],null);var uIa=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,jIa={"class":"className","for":"htmlFor",charset:"charSet"},lIa={},tIa={};$APP.g=y2.prototype;$APP.g.V=function(a,b){return new y2(this.oc,this.id,this.vh,this.Rf,b)};$APP.g.T=function(){return this.Oj};$APP.g.ck=function(){return this.id};$APP.g.fi=function(a,b,c){return this.Rf.j?this.Rf.j(this,b,c):this.Rf.call(null,this,b,c)};
$APP.g.di=function(a,b){return"object"!==$APP.ja(b)?b:$APP.ff(b)?zIa(b,this,this.vh):$APP.of(b)?yIa(b,this):F1(b)?$APP.xk(b):(null!=b?b.G&2147483648||$APP.Wd===b.sa||(b.G?0:$APP.Vb($APP.id,b)):$APP.Vb($APP.id,b))?$APP.tl.l($APP.B([b])):b};$APP.g.ei=function(a,b,c,d,e){return oIa(this,b,c,d,e)};$APP.$2=CIa($APP.th);var a3=function a3(a){switch(arguments.length){case 1:return a3.g(arguments[0]);case 2:return a3.h(arguments[0],arguments[1]);case 3:return a3.j(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return a3.l(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.ce(c.slice(3),0,null):null)}};a3.g=function(a){return a3.h(a,null)};a3.h=function(a,b){return $APP.ny.nbb$internal$react.createElement(a,b)};
a3.j=function(a,b,c){return $APP.ny.nbb$internal$react.createElement(a,b,c)};a3.l=function(a,b,c,d){return $APP.Oh.M($APP.ny.nbb$internal$react.createElement,a,b,c,d)};a3.A=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);var d=$APP.w(c);c=$APP.v(d);d=$APP.w(d);return this.l(b,a,c,d)};a3.o=3;var b3=function b3(a){switch(arguments.length){case 1:return b3.g(arguments[0]);case 2:return b3.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};
b3.g=function(a){return $APP.O1($APP.$2,a)};b3.h=function(a,b){return $APP.O1(b,a)};b3.o=2;var c3=function c3(a){switch(arguments.length){case 1:return c3.g(arguments[0]);case 2:return c3.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};c3.g=function(a){return c3.h(a,$APP.$2)};c3.h=function(a,b){return KHa(a)?a:YHa(a,b)};c3.o=2;
var d3=function d3(a){switch(arguments.length){case 1:return d3.g(arguments[0]);case 2:return d3.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};d3.g=function(a){return r2(a,$APP.$2)};d3.h=function(a,b){return r2(a,b)};d3.o=2;
var e3=function e3(a){switch(arguments.length){case 0:return e3.v();case 1:return e3.g(arguments[0]);case 2:return e3.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return e3.l(arguments[0],arguments[1],2<c.length?new $APP.ce(c.slice(2),0,null):null)}};e3.v=function(){return null};e3.g=function(a){return w2.g(a)};e3.h=function(a,b){return w2.h(a,b)};e3.l=function(a,b,c){return $APP.Oh.B(w2,a,b,c)};
e3.A=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};e3.o=2;var f3=function f3(a){switch(arguments.length){case 1:return f3.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return f3.l(arguments[0],1<c.length?new $APP.ce(c.slice(1),0,null):null)}};f3.g=function(a){return l2.g(a)};f3.l=function(a,b){return $APP.Oh.j(l2,a,b)};f3.A=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};f3.o=1;
var g3=function g3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return g3.l(arguments[0],1<c.length?new $APP.ce(c.slice(1),0,null):null)};g3.l=function(a,b){return b2(a,b)};g3.o=1;g3.A=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var h3=function h3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return h3.l(arguments[0],1<c.length?new $APP.ce(c.slice(1),0,null):null)};h3.l=function(a,b){return DHa(a,b)};
h3.o=1;h3.A=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var i3=function i3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return i3.l(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.ce(c.slice(3),0,null):null)};
i3.l=function(a,b,c,d){var e=$APP.Tq.g("with-let");a=$APP.Xk.g(e);var f=$APP.Tq.g("init");c=$APP.hj.h(new $APP.G(null,2,5,$APP.I,[f,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,EJa,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,$APP.ZN,null,1,null),new $APP.D(null,e,null,1,null)))),null,1,null))))],null),$APP.ay.h(function(r,p){if($APP.Nh(r))return p;r=$APP.yg(r,2);return $APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.pm,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,
$APP.NM,null,1,null),new $APP.D(null,f,null,1,null),$APP.B([new $APP.D(null,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,$APP.DQ,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,yJa,null,1,null),new $APP.D(null,e,null,1,null),$APP.B([new $APP.D(null,r,null,1,null)])))),null,1,null)))),null,1,null)])))),null,1,null),$APP.B([new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.Tpa,null,1,null),new $APP.D(null,e,null,1,null),$APP.B([new $APP.D(null,r,null,1,null),new $APP.D(null,
p,null,1,null)])))),null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.Gja,null,1,null),new $APP.D(null,e,null,1,null),$APP.B([new $APP.D(null,r,null,1,null)])))),null,1,null)]))))},c));var k=function(){var r=$APP.Pe(d);return $APP.of(r)&&$APP.x.h($APP.mm,$APP.v(r))?new $APP.G(null,2,5,$APP.I,[$APP.wk(d),$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.Hy,null,1,null),new $APP.D(null,$APP.Ii($APP.Y.g($APP.u($APP.K.v()))),null,1,null),$APP.B([$APP.ge(r)]))))],null):new $APP.G(null,
2,5,$APP.I,[d,null],null)}();b=$APP.A.j(k,0,null);k=$APP.A.j(k,1,null);k=$APP.l(k)?new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.cu,null,1,null),new $APP.D(null,$APP.Ii($APP.Y.g($APP.u($APP.K.h(new $APP.D(null,V2,null,1,null),new $APP.D(null,k,null,1,null))))),null,1,null),$APP.B([new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.pm,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.g(new $APP.D(null,HJa,null,1,null)))),null,1,null),$APP.B([new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,
$APP.ZC,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,$APP.NK,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,IIa,null,1,null),new $APP.D(null,e,null,1,null)))),null,1,null)))),null,1,null),$APP.B([new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,aJa,null,1,null),new $APP.D(null,e,null,1,null),$APP.B([new $APP.D(null,V2,null,1,null)])))),null,1,null)])))),null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.g(new $APP.D(null,V2,null,1,null)))),
null,1,null)])))),null,1,null)])))),null,1,null):null;var n=$APP.Tq.g("res");return $APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.cu,null,1,null),new $APP.D(null,$APP.Ii($APP.Y.g($APP.u($APP.K.h(new $APP.D(null,e,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,OJa,null,1,null),new $APP.D(null,a,null,1,null)))),null,1,null))))),null,1,null),$APP.B([new $APP.D(null,null,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.cu,null,1,null),new $APP.D(null,$APP.hj.h(c,
new $APP.G(null,2,5,$APP.I,[n,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,$APP.om,null,1,null),b)))],null)),null,1,null),$APP.B([k,new $APP.D(null,n,null,1,null)])))),null,1,null)]))))};i3.o=3;i3.A=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);var d=$APP.w(c);c=$APP.v(d);d=$APP.w(d);return this.l(b,a,c,d)};var j3=function j3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return j3.l(0<c.length?new $APP.ce(c.slice(0),0,null):null)};
j3.l=function(a){return $APP.Y.g($APP.u($APP.K.h(new $APP.D(null,GIa,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.Hy,null,1,null),new $APP.D(null,$APP.Ii($APP.Y.g($APP.u($APP.K.v()))),null,1,null),$APP.B([a])))),null,1,null))))};j3.o=0;j3.A=function(a){return this.l($APP.u(a))};
var k3=$APP.mV.h($APP.SL,null),ZJa=$APP.Rj([OIa,xJa,MIa,$APP.QC,TJa,ZIa,IJa,AJa,WJa,HIa,eJa,U2,YIa,R2],[function(){var a=new $APP.ae(function(){return d3},vJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,OIa,"reagent/core.cljs",19,new $APP.h(null,6,[$APP.AD,!1,$APP.tw,2,$APP.SQ,2,$APP.hQ,new $APP.G(null,2,5,$APP.I,[new $APP.G(null,1,5,$APP.I,[$APP.oC],null),new $APP.G(null,2,5,$APP.I,[$APP.oC,$APP.Q2],null)],null),$APP.Z,$APP.J(new $APP.G(null,
1,5,$APP.I,[$APP.oC],null),new $APP.G(null,2,5,$APP.I,[$APP.oC,$APP.Q2],null)),$APP.QI,$APP.J(null,null)],null),1,68,68,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.oC],null),new $APP.G(null,2,5,$APP.I,[$APP.oC,$APP.Q2],null)),"Creates JS class based on provided Clojure map, for example:\n\n  ```cljs\n  {;; Constructor\n   :constructor (fn [this props])\n   :get-initial-state (fn [this])\n   ;; Static methods\n   :get-derived-state-from-props (fn [props state] partial-state)\n   :get-derived-state-from-error (fn [error] partial-state)\n   ;; Methods\n   :get-snapshot-before-update (fn [this old-argv new-argv] snapshot)\n   :should-component-update (fn [this old-argv new-argv])\n   :component-did-mount (fn [this])\n   :component-did-update (fn [this old-argv old-state snapshot])\n   :component-will-unmount (fn [this])\n   :component-did-catch (fn [this error info])\n   :reagent-render (fn [args....])\n   ;; Or alternatively:\n   :render (fn [this])\n   ;; Deprecated methods:\n   :UNSAFE_component-will-receive-props (fn [this new-argv])\n   :UNSAFE_component-will-update (fn [this new-argv new-state])\n   :UNSAFE_component-will-mount (fn [this])}\n  ```\n\n  Everything is optional, except either :reagent-render or :render.\n\n  Map keys should use `React.Component` method names (https://reactjs.org/docs/react-component.html),\n  and can be provided in snake-case or camelCase.\n\n  State can be initialized using constructor, which matches React.Component class,\n  or using getInitialState which matches old React createClass function and is\n  now implemented by Reagent for compatibility.\n\n  State can usually be anything, e.g. Cljs object. But if using getDerivedState\n  methods, the state has to be plain JS object as React implementation uses\n  Object.assign to merge partial state into the current state.\n\n  React built-in static methods or properties are automatically defined as statics.",
$APP.l(d3)?d3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return g3},UJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,xJa,"reagent/core.cljs",
12,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,1,$APP.SQ,1,$APP.hQ,new $APP.G(null,1,5,$APP.I,[$APP.J($APP.yN,$APP.CG)],null),$APP.Z,$APP.J(new $APP.G(null,3,5,$APP.I,[$APP.yN,$APP.jm,$APP.CG],null)),$APP.QI,$APP.J(null)],null),1,218,218,$APP.J(new $APP.G(null,3,5,$APP.I,[$APP.yN,$APP.jm,$APP.CG],null)),"Takes a function and optional arguments, and returns a derefable\n  containing the output of that function. If the function derefs\n  Reagent atoms (or track, etc), the value will be updated whenever\n  the atom changes.\n\n  In other words, `@(track foo bar)` will produce the same result\n  as `(foo bar)`, but foo will only be called again when the atoms it\n  depends on changes, and will only trigger updates of components when\n  its result changes.\n\n  track is lazy, i.e the function is only evaluated on deref.",
$APP.l(g3)?g3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return i3},RJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.st,$APP.yS,$APP.Z,$APP.M,$APP.WI],[T2,MIa,"sci/configs/reagent/reagent.cljs",
23,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,1,$APP.SQ,1,$APP.hQ,$APP.J($APP.J($APP.FC,$APP.UE)),$APP.Z,$APP.J(new $APP.G(null,3,5,$APP.I,[$APP.FC,$APP.jm,$APP.UE],null)),$APP.QI,$APP.J(null)],null),1,10,!0,10,$APP.J(new $APP.G(null,3,5,$APP.I,[$APP.FC,$APP.jm,$APP.UE],null)),null,$APP.l(i3)?i3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=
$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return f3},QIa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,$APP.QC,"reagent/core.cljs",11,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,1,$APP.SQ,1,$APP.hQ,new $APP.G(null,1,5,$APP.I,[new $APP.G(null,1,5,$APP.I,[$APP.RN],null)],null),$APP.Z,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.RN],null),new $APP.G(null,3,5,$APP.I,[$APP.RN,
$APP.jm,$APP.YD],null)),$APP.QI,$APP.J(null,null)],null),1,211,211,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.RN],null),new $APP.G(null,3,5,$APP.I,[$APP.RN,$APP.jm,$APP.YD],null)),"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.l(f3)?f3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?
$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return e3},SJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,TJa,"reagent/core.cljs",18,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,2,$APP.SQ,2,$APP.hQ,new $APP.G(null,3,5,$APP.I,[$APP.oi,new $APP.G(null,1,5,$APP.I,[$APP.pH],null),new $APP.G(null,2,5,$APP.I,[M2,L2],null)],null),$APP.Z,
$APP.J($APP.oi,new $APP.G(null,1,5,$APP.I,[$APP.pH],null),new $APP.G(null,2,5,$APP.I,[M2,L2],null),new $APP.G(null,4,5,$APP.I,[M2,L2,$APP.jm,nJa],null)),$APP.QI,$APP.J(null,null,null,null)],null),1,179,179,$APP.J($APP.oi,new $APP.G(null,1,5,$APP.I,[$APP.pH],null),new $APP.G(null,2,5,$APP.I,[M2,L2],null),new $APP.G(null,4,5,$APP.I,[M2,L2,$APP.jm,nJa],null)),"Function which normalizes and combines class values to a string\n\n  Reagent allows classes to be defined as:\n  - Strings\n  - Named objects (Symbols or Keywords)\n  - Collections of previous types",
$APP.l(e3)?e3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return j3},mJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.st,$APP.yS,$APP.Z,$APP.M,$APP.WI],[T2,ZIa,"sci/configs/reagent/reagent.cljs",
23,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,-2,$APP.SQ,-2,$APP.hQ,$APP.J($APP.fe),$APP.Z,$APP.J($APP.oi),$APP.QI,$APP.J(null)],null),1,62,!0,62,$APP.J($APP.oi),null,$APP.l(j3)?j3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=
new $APP.ae(function(){return b3},tJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,IJa,"reagent/core.cljs",17,new $APP.h(null,6,[$APP.AD,!1,$APP.tw,2,$APP.SQ,2,$APP.hQ,new $APP.G(null,2,5,$APP.I,[new $APP.G(null,1,5,$APP.I,[$APP.IM],null),new $APP.G(null,2,5,$APP.I,[$APP.IM,$APP.Q2],null)],null),$APP.Z,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.IM],null),new $APP.G(null,2,5,$APP.I,[$APP.IM,$APP.Q2],null)),$APP.QI,$APP.J(null,null)],null),1,46,
46,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.IM],null),new $APP.G(null,2,5,$APP.I,[$APP.IM,$APP.Q2],null)),"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.l(b3)?b3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,
b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return c3},dJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,AJa,"reagent/core.cljs",25,new $APP.h(null,6,[$APP.AD,!1,$APP.tw,2,$APP.SQ,2,$APP.hQ,new $APP.G(null,2,5,$APP.I,[new $APP.G(null,1,5,$APP.I,[$APP.xN],null),new $APP.G(null,2,5,$APP.I,[$APP.xN,$APP.Q2],null)],null),$APP.Z,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.xN],null),new $APP.G(null,2,5,$APP.I,[$APP.xN,$APP.Q2],null)),
$APP.QI,$APP.J(null,null)],null),1,59,59,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.xN],null),new $APP.G(null,2,5,$APP.I,[$APP.xN,$APP.Q2],null)),"Returns an adapter for a Reagent component, that may be used from\n  React, for example in JSX. A single argument, props, is passed to\n  the component, converted to a map.",$APP.l(c3)?c3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?
$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return a3},MJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,WJa,"reagent/core.cljs",21,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,3,$APP.SQ,3,$APP.hQ,new $APP.G(null,3,5,$APP.I,[new $APP.G(null,1,5,$APP.I,[$APP.YH],null),new $APP.G(null,2,5,$APP.I,[$APP.YH,O2],null),new $APP.G(null,
3,5,$APP.I,[$APP.YH,O2,$APP.kN],null)],null),$APP.Z,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.YH],null),new $APP.G(null,2,5,$APP.I,[$APP.YH,O2],null),new $APP.G(null,3,5,$APP.I,[$APP.YH,O2,$APP.kN],null),new $APP.G(null,5,5,$APP.I,[$APP.YH,O2,$APP.kN,$APP.jm,$APP.xK],null)),$APP.QI,$APP.J(null,null,null,null)],null),1,17,17,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.YH],null),new $APP.G(null,2,5,$APP.I,[$APP.YH,O2],null),new $APP.G(null,3,5,$APP.I,[$APP.YH,O2,$APP.kN],null),new $APP.G(null,5,5,$APP.I,
[$APP.YH,O2,$APP.kN,$APP.jm,$APP.xK],null)),'Create a native React element, by calling React.createElement directly.\n\n  That means the second argument must be a javascript object (or nil), and\n  that any Reagent hiccup forms must be processed with as-element. For example\n  like this:\n\n  ```cljs\n  (r/create-element "div" #js{:className "foo"}\n    "Hi " (r/as-element [:strong "world!"])\n  ```\n\n  which is equivalent to\n\n  ```cljs\n  [:div.foo "Hi" [:strong "world!"]]\n  ```',$APP.l(a3)?
a3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return A2},hJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,HIa,"reagent/core.cljs",15,1,242,242,
$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.RN],null)),"Stop the result of track! from updating.",$APP.l(A2)?A2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return B2},RIa,$APP.Rj([$APP.W,$APP.O,$APP.ao,
$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,eJa,"reagent/core.cljs",13,1,272,272,$APP.J(new $APP.G(null,2,5,$APP.I,[jJa,$APP.Nsa],null)),"Provide a cursor into a Reagent atom.\n\n  Behaves like a Reagent atom but focuses updates and derefs to\n  the specified path within the wrapped Reagent atom. e.g.,\n\n  ```cljs\n  (let [c (cursor ra [:nested :content])]\n    ... @c ;; equivalent to (get-in @ra [:nested :content])\n    ... (reset! c 42) ;; equivalent to (swap! ra assoc-in [:nested :content] 42)\n    ... (swap! c inc) ;; equivalence to (swap! ra update-in [:nested :content] inc)\n    )\n  ```\n\n  The first parameter can also be a function, that should look\n  something like this:\n\n  ```cljs\n  (defn set-get\n    ([k] (get-in @state k))\n    ([k v] (swap! state assoc-in k v)))\n  ```\n\n  The function will be called with one argument – the path passed to\n  cursor – when the cursor is deref'ed, and two arguments (path and\n  new value) when the cursor is modified.\n\n  Given that set-get function, (and that state is a Reagent atom, or\n  another cursor) these cursors are equivalent:\n  `(cursor state [:foo])` and `(cursor set-get [:foo])`.\n\n  Note that a cursor is lazy: its value will not change until it is\n  used. This may be noticed with add-watch.",
$APP.l(B2)?B2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return h3},sJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,U2,"reagent/core.cljs",
13,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,1,$APP.SQ,1,$APP.hQ,new $APP.G(null,1,5,$APP.I,[$APP.J($APP.yN,$APP.CG)],null),$APP.Z,$APP.J(new $APP.G(null,3,5,$APP.I,[$APP.yN,$APP.jm,$APP.CG],null)),$APP.QI,$APP.J(null)],null),1,234,234,$APP.J(new $APP.G(null,3,5,$APP.I,[$APP.yN,$APP.jm,$APP.CG],null)),"An eager version of track. The function passed is called\n  immediately, and continues to be called when needed, until stopped\n  with dispose!.",$APP.l(h3)?h3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?
null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return C2},JIa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,YIa,"reagent/core.cljs",22,1,353,353,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.DK],null)),"Creates Compiler object with given `opts`,\n  this can be passed to `render`, `as-element` and other functions to control\n  how they turn the Reagent-style Hiccup into React components and elements.",
$APP.l(C2)?C2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return z2},FIa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,R2,"reagent/core.cljs",24,
1,52,52,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.xN],null)),"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.l(z2)?z2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,
b,d)}()]),l3=$APP.mV.h($APP.EQ,null),$Ja=$APP.Rj([NIa,$APP.QC,JJa,VIa,SIa,$Ia,bJa,fJa,PJa,DIa,U2,uJa],[function(){var a=new $APP.ae(function(){return e2},OJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.EQ,NIa,"reagent/ratom.cljs",22,1,329,329,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.lL],null)),null,$APP.l(e2)?e2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,l3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],
null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return l2},KJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.EQ,$APP.QC,"reagent/ratom.cljs",11,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,1,$APP.SQ,1,$APP.hQ,new $APP.G(null,1,5,$APP.I,[new $APP.G(null,1,5,$APP.I,[$APP.RN],null)],null),$APP.Z,$APP.J(new $APP.G(null,
1,5,$APP.I,[$APP.RN],null),new $APP.G(null,3,5,$APP.I,[$APP.RN,$APP.jm,new $APP.h(null,1,[$APP.SE,new $APP.G(null,2,5,$APP.I,[$APP.vD,$APP.AO],null)],null)],null)),$APP.QI,$APP.J(null,null)],null),1,172,172,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.RN],null),new $APP.G(null,3,5,$APP.I,[$APP.RN,$APP.jm,new $APP.h(null,1,[$APP.SE,new $APP.G(null,2,5,$APP.I,[$APP.vD,$APP.AO],null)],null)],null)),"Like clojure.core/atom, except that it keeps track of derefs.",$APP.l(l2)?l2.D:null])),b=$APP.q(a),c=$APP.Ve(a);
a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return b2},wJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.EQ,JJa,"reagent/ratom.cljs",17,1,228,228,$APP.J(new $APP.G(null,2,5,$APP.I,[$APP.yN,
$APP.CG],null)),null,$APP.l(b2)?b2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return I2},UIa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[T2,VIa,"sci/configs/reagent/reagent.cljs",
15,1,106,106,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.Ue($APP.PN,new $APP.h(null,1,[$APP.Yo,$APP.SF],null))],null)),null,$APP.l(I2)?I2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,l3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return G2},QJa,$APP.Rj([$APP.W,
$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[T2,SIa,"sci/configs/reagent/reagent.cljs",29,1,98,98,$APP.J(new $APP.G(null,2,5,$APP.I,[$APP.Ue($APP.PN,new $APP.h(null,1,[$APP.Yo,$APP.SF],null)),$APP.Ue($APP.xN,new $APP.h(null,1,[$APP.Yo,$APP.SF],null))],null)),null,$APP.l(G2)?G2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,l3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,
d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return R1},HJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Yo,$APP.Z,$APP.M,$APP.WI],[$APP.EQ,$Ia,"reagent/ratom.cljs",25,1,17,17,$APP.TL,$APP.J($APP.oi),null,R1?R1.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,l3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?
$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return H2},CJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[T2,bJa,"sci/configs/reagent/reagent.cljs",16,1,102,102,$APP.J(new $APP.G(null,2,5,$APP.I,[$APP.Ue($APP.PN,new $APP.h(null,1,[$APP.Yo,$APP.SF],null)),qJa],null)),null,$APP.l(H2)?H2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:
$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,l3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return Y1},GIa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.EQ,fJa,"reagent/ratom.cljs",20,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,1,$APP.SQ,1,$APP.hQ,new $APP.G(null,
1,5,$APP.I,[$APP.J($APP.yN,new $APP.h(null,1,[$APP.SE,new $APP.G(null,3,5,$APP.I,[N2,K2,W2],null)],null))],null),$APP.Z,$APP.J(new $APP.G(null,3,5,$APP.I,[$APP.yN,$APP.jm,new $APP.h(null,1,[$APP.SE,new $APP.G(null,3,5,$APP.I,[N2,K2,W2],null)],null)],null)),$APP.QI,$APP.J(null)],null),1,517,517,$APP.J(new $APP.G(null,3,5,$APP.I,[$APP.yN,$APP.jm,new $APP.h(null,1,[$APP.SE,new $APP.G(null,3,5,$APP.I,[N2,K2,W2],null)],null)],null)),null,$APP.l(Y1)?Y1.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?
null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return D2},TIa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[T2,PJa,"sci/configs/reagent/reagent.cljs",21,1,85,85,$APP.J($APP.oi),"Read-only access to the ratom context.",
$APP.l(D2)?D2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,l3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return E2},kJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[T2,DIa,"sci/configs/reagent/reagent.cljs",
18,1,90,90,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.Ue($APP.RN,new $APP.h(null,1,[$APP.Yo,$APP.SF],null))],null)),null,$APP.l(E2)?E2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,l3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return Z2},EIa,$APP.Rj([$APP.W,
$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.EQ,U2,"reagent/ratom.cljs",13,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,1,$APP.SQ,1,$APP.hQ,new $APP.G(null,1,5,$APP.I,[$APP.J($APP.yN,$APP.CG)],null),$APP.Z,$APP.J(new $APP.G(null,3,5,$APP.I,[$APP.yN,$APP.jm,$APP.CG],null)),$APP.QI,$APP.J(null)],null),1,242,242,$APP.J(new $APP.G(null,3,5,$APP.I,[$APP.yN,$APP.jm,$APP.CG],null)),null,$APP.l(Z2)?Z2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=
new $APP.h(null,4,[$APP.W,k3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return F2},pJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[T2,uJa,"sci/configs/reagent/reagent.cljs",24,1,94,94,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.Ue($APP.RN,new $APP.h(null,1,
[$APP.Yo,$APP.SF],null))],null)),null,$APP.l(F2)?F2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,l3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}()]),m3=$APP.mV.h(S2,null),n3=function n3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return n3.l(arguments[0],
arguments[1],2<c.length?new $APP.ce(c.slice(2),0,null):null)};
n3.l=function(a,b,c){return $APP.l(!0)?$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.ZC,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,$APP.pI,null,1,null),new $APP.D(null,BJa,null,1,null)))),null,1,null),$APP.B([new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,FJa,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.pm,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.g(new $APP.D(null,GJa,null,1,null)))),null,1,null),$APP.B([new $APP.D(null,
LJa,null,1,null),new $APP.D(null,BJa,null,1,null)])))),null,1,null),$APP.B([new $APP.D(null,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,$APP.Cy,null,1,null),c))),null,1,null)])))),null,1,null)])))):null};n3.o=2;n3.A=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};
var aKa=new $APP.h(null,3,[$APP.VK,function(){var a=new $APP.ae(function(){return n3},cJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.st,$APP.yS,$APP.Z,$APP.M,$APP.WI],[T2,$APP.VK,"sci/configs/reagent/reagent.cljs",20,new $APP.h(null,6,[$APP.AD,!0,$APP.tw,0,$APP.SQ,0,$APP.hQ,$APP.J($APP.J($APP.QJ)),$APP.Z,$APP.J(new $APP.G(null,2,5,$APP.I,[$APP.jm,$APP.QJ],null)),$APP.QI,$APP.J(null)],null),1,132,!0,132,$APP.J(new $APP.G(null,2,5,$APP.I,[$APP.jm,$APP.QJ],null)),"Print with console.error.",
$APP.l(n3)?n3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,m3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),LIa,function(){var a=new $APP.ae(function(){return J2},zJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[T2,LIa,"sci/configs/reagent/reagent.cljs",
17,1,129,129,$APP.J($APP.oi),null,$APP.l(J2)?J2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,m3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),WIa,function(){var a=new $APP.ae(function(){return X2},LJa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],
[S2,WIa,"reagent/debug.cljs",23,1,10,10,$APP.fe,null,$APP.l(X2)?X2.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,m3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}()],null);$APP.zy(new $APP.h(null,1,[$APP.Ut,new $APP.h(null,3,[$APP.SL,$APP.kk.j(ZJa,R2,function(){var a=$APP.mV.g($APP.SL),b=new $APP.ae(function(){return z2},FIa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.SL,R2,"reagent/core.cljs",24,1,52,52,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.xN],null)),"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.l(z2)?z2.D:null])),c=$APP.q(b),
d=$APP.Ve(b);b=$APP.l(null)?null:$APP.O.g(d);a=new $APP.h(null,4,[$APP.W,a,$APP.O,b,$APP.Z,$APP.Z.g(d),$APP.M,$APP.M.g(d)],null);return $APP.l($APP.gu.g(d))?$APP.gV.j(b,c,a):$APP.l(function(){var e=$APP.st.g(d);return $APP.l(e)?e:$APP.It.g(d)}())?$APP.hV.j(b,c,a):$APP.Mx.j(b,c,a)}()),$APP.EQ,$Ja,S2,aKa],null)],null));