import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_impl_main.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_path from"node:path";
var ZMa=function(a){a=$APP.dl.g(a);var b=$APP.Yg(a)?$APP.dl.h($APP.m.g(a),"-main"):a,c=$APP.Ug(b);return $APP.bn("(require '$1) (apply $2 *command-line-args*)",/\$(\d)/,function(d){d=$APP.Le(d);switch(d){case "1":return c;case "2":return b;default:throw Error(["No matching clause: ",$APP.m.g(d)].join(""));}})},$Ma=function(a){var b=$APP.dl.g(a),c=$APP.Ug(b);return $APP.bn("\n(require '[babashka.cli])\n(require '$1)\n(let [the-var (resolve '$2)\n      the-var-meta (meta the-var)\n      ns (:ns (meta the-var))\n      ns-meta (meta ns)\n      cli-opts (babashka.cli/merge-opts (:org.babashka/cli ns-meta)\n                                        (:org.babashka/cli the-var-meta))\n      opts (babashka.cli/parse-opts *command-line-args* cli-opts)]\n  (the-var opts))\n",/\$(\d)/,
function(d){d=$APP.Le(d);switch(d){case "1":return c;case "2":return b;default:throw Error(["No matching clause: ",$APP.m.g(d)].join(""));}})},aNa=function(a){for(var b=$APP.th,c=a;;)if($APP.l(c)){var d=$APP.v(c);a=$APP.w(c);switch(d){case "--help":case "-h":return $APP.kk.j(b,$APP.JF,!0);case "--version":case "-v":return $APP.kk.j(b,$APP.dKa,!0);case "-e":b=$APP.kk.j(b,$APP.Ur,$APP.v(a));c=a=$APP.w(a);continue;case "-m":case "--main":return $APP.kk.l(b,$APP.Ur,ZMa($APP.v(a)),$APP.B([$APP.Bp,$APP.w(a)]));
case "-x":case "--exec":return $APP.kk.l(b,$APP.Ur,$Ma($APP.v(a)),$APP.B([$APP.Bp,$APP.w(a)]));case "-cp":case "--classpath":b=$APP.kk.j(b,$APP.AX,$APP.v(a));c=a=$APP.w(a);continue;case "--config":b=$APP.kk.j(b,$APP.uE,$APP.v(a));c=a=$APP.w(a);continue;case "--debug":b=$APP.kk.j(b,$APP.cy,!0);c=a;continue;case "nrepl-server":b=$APP.kk.j(b,$APP.o3,!0);c=a;continue;case "socket-repl":b=$APP.kk.j(b,$APP.p3,!0);c=a;continue;case ":port":case "--port":b=$APP.kk.j(b,$APP.vK,$APP.v(a));c=a=$APP.w(a);continue;
case ":host":case "--host":b=$APP.kk.j(b,$APP.PR,$APP.v(a));c=a=$APP.w(a);continue;case "repl":b=$APP.kk.j(b,$APP.cKa,!0);c=a;continue;case "bundle":return $APP.kk.j(b,$APP.qO,$APP.kq.h(a,new $APP.h(null,1,[$APP.fr,new $APP.h(null,2,[$APP.eKa,$APP.dsa,$APP.fKa,$APP.JF],null)],null)));default:if($APP.Ob($APP.Ur.g(c)))return $APP.kk.l(b,$APP.bKa,d,$APP.B([$APP.Bp,$APP.w(c)]));throw $APP.eo.h(["Unrecognized options:",$APP.m.g(c)].join(""),$APP.th);}}else return b};if($APP.l(esm_import$node_process.on))esm_import$node_process.on("unhandledRejection",function(a){console.error($APP.hm(a));return process.exitCode=1});(function(){var a=$APP.u(function(){var k=globalThis.nbb_args;return $APP.l(k)?k:esm_import$node_process.argv}());$APP.v(a);a=$APP.w(a);$APP.v(a);a=$APP.w(a);var b=aNa(a);$APP.Sh($APP.gKa,b);var c=$APP.bKa.g(b),d=$APP.Ur.g(b);a=$APP.AX.g(b);$APP.l(a)&&$APP.Hs(a);a=$APP.o3.g(b);var e=function(){var k=$APP.cKa.g(b);if($APP.l(k))return k;k=$APP.p3.g(b);return $APP.l(k)?k:$APP.Ye($APP.Un.l(b,$APP.AX,$APP.B([$APP.cy,$APP.uE])))}(),f=$APP.qO.g(b);$APP.l($APP.JF.g(b))&&($APP.VB.l($APP.B([$APP.gb("nbb"),
"version:",$APP.Ky()])),$APP.VB.l($APP.B(["\nHelp:\n\n -h / --help: print this help text and exit.\n -v / --version: print the current version of nbb.\n\nGlobal options:\n\n --debug: print additional debug info.\n -cp / --classpath: set the classpath.\n\nEvaluation:\n\n -e: execute expression\n -m / --main: execute main function\n -x / --exec: execute function using babashka.cli\n\nREPL:\n\n repl: start console REPL.\n nrepl-server: start nrepl server. [1,2]\n socket-repl: start socket repl server. [1]\n\n 1: Provide :port \x3cport\x3e to specify port\n 2: Provide :host \x3chost\x3e to specify host\n\nTooling:\n\n  bundle: produce single JS file for usage with bundlers.\n"])),
esm_import$node_process.exit(0));$APP.l($APP.dKa.g(b))&&($APP.VB.l($APP.B([["nbb v",$APP.Ky()].join("")])),esm_import$node_process.exit(0));return $APP.l($APP.l(c)?c:$APP.l(d)?d:$APP.l(a)?a:$APP.l(e)?e:f)?($APP.iV.h($APP.kya,$APP.Qh($APP.Bp.g(b))),Promise.resolve($APP.tX($APP.l(e)?esm_import$node_path.resolve("script.cljs"):c,b)).then(function(){return($APP.l(c)?$APP.BX.g(c):$APP.l(d)?$APP.CX.g(d):$APP.l($APP.o3.g(b))?shadow_esm_import("./nbb_nrepl_server.js").then(function(){var k=$APP.C.h($APP.C.h($APP.Ut.g($APP.q($APP.Ot.g($APP.fy()))),
$APP.gD),$APP.zX);return k.g?k.g(b):k.call(null,b)}):$APP.l($APP.l(e)?$APP.p3.g(b):e)?shadow_esm_import("./nbb_repl.js").then(function(){var k=new $APP.h(null,1,[$APP.vK,$APP.vK.g(b)],null),n=$APP.C.h($APP.C.h($APP.Ut.g($APP.q($APP.Ot.g($APP.fy()))),$APP.pC),$APP.xX);return n.g?n.g(k):n.call(null,k)}):$APP.l($APP.qO.g(b))?shadow_esm_import("./nbb_bundler.js"):$APP.l(e)?shadow_esm_import("./nbb_repl.js").then(function(){var k=$APP.C.h($APP.C.h($APP.Ut.g($APP.q($APP.Ot.g($APP.fy()))),$APP.pC),$APP.yX);
return k.v?k.v():k.call(null)}):null).then(function(k){$APP.l($APP.l(d)?null!=k:d)&&$APP.by.l($APP.B([k]));return k}).catch(function(k){$APP.Nfa(k,b);$APP.l($APP.cy.g(b))&&console.error(k);throw Error($APP.hm(k));})})):console.error("Usage: nbb \x3cscript\x3e or nbb -e \x3cexpr\x3e.")})();