import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var tza=function(a,b){b&=63;if(0==b)return a;var c=a.Ja;return 32>b?$APP.va(a.ab>>>b|c<<32-b,c>>>b):32==b?$APP.va(c,0):$APP.va(c>>>b-32,0)},KV=function(a){if(null!=a&&null!=a.ja)a=a.ja(a);else{var b=KV[$APP.ja(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=KV._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.Xb("ICloneable.-clone",a);}return a},LV=function(a,b){if("-"==a.charAt(0))return $APP.xa(LV(a.substring(1),b));var c=parseInt(a,b||10);if(9007199254740991>=c)return new $APP.ua(c%
4294967296|0,c/4294967296|0);if(0==a.length)throw Error("number format error: empty string");if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character: '+a);b=b||10;if(2>b||36<b)throw Error("radix out of range: "+b);c=$APP.Aa(Math.pow(b,8));for(var d=$APP.ya,e=0;e<a.length;e+=8){var f=Math.min(8,a.length-e),k=parseInt(a.substring(e,e+f),b);8>f?(f=$APP.Aa(Math.pow(b,f)),d=d.multiply(f).add($APP.Aa(k))):(d=d.multiply(c),d=d.add($APP.Aa(k)))}return d},MV=function(){return Math.round(15*
Math.random()).toString(16)},uza=function(a,b){if(3<a.length){if(b)return!0;b=a.charAt(1);return"~"===a.charAt(0)?":"===b||"$"===b||"#"===b:!1}return!1},vza=function(a){var b=Math.floor(a/44);a=String.fromCharCode(a%44+48);return 0===b?"^"+a:"^"+String.fromCharCode(b+48)+a},NV=function(){this.Fi=this.Ye=this.sb=0;this.cache={}},OV=function(){this.sb=0;this.cache=[]},QV=function(a,b){if(null==a)return null==b;if(a===b)return!0;if("object"===typeof a){if(PV(a)){if(PV(b)&&a.length===b.length){for(var c=
0;c<a.length;c++)if(!QV(a[c],b[c]))return!1;return!0}return!1}if(a.Ic)return a.Ic(b);if(null!=b&&"object"===typeof b){if(b.Ic)return b.Ic(a);c=0;var d=RV(b).length,e;for(e in a)if(a.hasOwnProperty(e)&&(c++,!b.hasOwnProperty(e)||!QV(a[e],b[e])))return!1;return c===d}}return!1},SV=function(a,b){return a^b+2654435769+(a<<6)+(a>>2)},UV=function(a){var b=0;if(null!=a.forEach)a.forEach(function(k,n){b=(b+(TV(n)^TV(k)))%4503599627370496});else for(var c=RV(a),d=0;d<c.length;d++){var e=c[d],f=a[e];b=(b+(TV(e)^
TV(f)))%4503599627370496}return b},wza=function(a){var b=0;if(PV(a))for(var c=0;c<a.length;c++)b=SV(b,TV(a[c]));else a.forEach&&a.forEach(function(d){b=SV(b,TV(d))});return b},TV=function(a){if(null==a)return 0;switch(typeof a){case "number":return a;case "boolean":return!0===a?1:0;case "string":var b=VV[a];if(null!=b)a=b;else{for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;WV++;256<=WV&&(VV={},WV=1);a=VV[a]=b}return a;case "function":return b=a.transit$hashCode$,b||(b=xza,"undefined"!=
typeof Object.defineProperty?Object.defineProperty(a,"transit$hashCode$",{value:b,enumerable:!1}):a.transit$hashCode$=b,xza++),b;default:return a instanceof Date?a.valueOf():PV(a)?wza(a):a.Vc?a.Vc():UV(a)}},XV=function(a,b){this.tag=a;this.rep=b;this.Xa=-1},YV=function(a,b){return new XV(a,b)},Aza=function(a){if("number"===typeof a||a instanceof $APP.ua)return a;a=LV(a,10);return 0<a.compare(yza)||0>a.compare(zza)?a:$APP.Ba(a)},ZV=function(a){this.Ab=a;this.Xa=-1},$V=function(a){this.Ab=a;this.Xa=
-1},aW=function(a,b,c){var d="";c=c||b+1;for(var e=8*(7-b),f=(new $APP.ua(255,0)).shiftLeft(e);b<c;b++,e-=8,f=tza(f,8)){var k=tza(a.and(f),e).toString(16);1==k.length&&(k="0"+k);d+=k}return d},bW=function(a,b){this.high=a;this.low=b;this.Xa=-1},cW=function(a,b){this.entries=a;this.type=b||0;this.sb=0},dW=function(a,b){this.map=a;this.type=b||0;this.keys=this.map.ge();this.sb=0;this.Ud=null;this.Id=0},gW=function(a,b){if(a instanceof eW&&(b instanceof fW||b instanceof eW)){if(a.size!==b.size)return!1;
for(var c in a.map)for(var d=a.map[c],e=0;e<d.length;e+=2)if(!QV(d[e+1],b.get(d[e])))return!1;return!0}if(a instanceof fW&&(b instanceof fW||b instanceof eW)){if(a.size!==b.size)return!1;a=a.$a;for(e=0;e<a.length;e+=2)if(!QV(a[e+1],b.get(a[e])))return!1;return!0}if(null!=b&&"object"===typeof b&&(e=RV(b),c=e.length,a.size===c)){for(d=0;d<c;d++){var f=e[d];if(!a.has(f)||!QV(b[f],a.get(f)))return!1}return!0}return!1},hW=function(a){return null==a?"null":"array"===$APP.ja(a)?"["+a.toString()+"]":"string"===
$APP.ja(a)?'"'+a+'"':a.toString()},Bza=function(a){var b=0,c="TransitMap {";a.forEach(function(d,e){c+=hW(e)+" \x3d\x3e "+hW(d);b<a.size-1&&(c+=", ");b++});return c+"}"},Cza=function(a){var b=0,c="TransitSet {";a.forEach(function(d){c+=hW(d);b<a.size-1&&(c+=", ");b++});return c+"}"},fW=function(a){this.$a=a;this.Ya=null;this.Xa=-1;this.size=a.length/2;this.Sg=0},Dza=function(a){if(a.Ya)throw Error("Invalid operation, already converted");if(8>a.size)return!1;a.Sg++;return 32<a.Sg?(a.Ya=iW(a.$a,!1,
!0),a.$a=[],!0):!1},eW=function(a,b,c){this.map=b||{};this.te=a||[];this.size=c||0;this.Xa=-1},iW=function(a,b,c){a=a||[];b=!1===b?b:!0;if((!0!==c||!c)&&64>=a.length){if(b){var d=a;a=[];for(b=0;b<d.length;b+=2){var e=!1;for(c=0;c<a.length;c+=2)if(QV(a[c],d[b])){a[c+1]=d[b+1];e=!0;break}e||(a.push(d[b]),a.push(d[b+1]))}}return new fW(a)}d={};e=[];var f=0;for(b=0;b<a.length;b+=2){c=TV(a[b]);var k=d[c];if(null==k)e.push(c),d[c]=[a[b],a[b+1]],f++;else{var n=!0;for(c=0;c<k.length;c+=2)if(QV(k[c],a[b])){k[c+
1]=a[b+1];n=!1;break}n&&(k.push(a[b]),k.push(a[b+1]),f++)}}return new eW(e,d,f)},jW=function(a){this.map=a;this.size=a.size},Eza=function(a){a=a||[];for(var b={},c=[],d=0,e=0;e<a.length;e++){var f=TV(a[e]),k=b[f];if(null==k)c.push(f),b[f]=[a[e],a[e]],d++;else{f=!0;for(var n=0;n<k.length;n+=2)if(QV(k[n],a[e])){f=!1;break}f&&(k.push(a[e]),k.push(a[e]),d++)}}return new jW(new eW(c,b,d))},kW=function(a){this.dc=a},lW=function(a){this.options=a||{};this.Hb={};for(var b in this.Ve.Hb)this.Hb[b]=this.Ve.Hb[b];
for(b in this.options.handlers){a:{switch(b){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":a=!0;break a}a=!1}if(a)throw Error('Cannot override handler for ground type "'+b+'"');this.Hb[b]=this.options.handlers[b]}this.Sf=null!=this.options.preferStrings?this.options.preferStrings:this.Ve.Sf;this.Hg=null!=this.options.preferBuffers?this.options.preferBuffers:this.Ve.Hg;this.Ag=this.options.defaultHandler||this.Ve.Ag;this.Nc=this.options.mapBuilder;this.ue=this.options.arrayBuilder},
Fza=function(a,b,c,d,e){if(e){var f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return f}f=c&&c.sb;if(2===b.length&&"string"===typeof b[0]&&(e=a.decode(b[0],c,!1,!1))&&e instanceof kW)return b=b[1],f=a.Hb[e.dc],null!=f?f=f(a.decode(b,c,d,!0),a):YV(e.dc,a.decode(b,c,d,!1));c&&f!=c.sb&&(c.sb=f);if(a.ue){if(32>=b.length&&a.ue.fromArray){f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return a.ue.fromArray(f,b)}f=a.ue.init(b);for(e=0;e<b.length;e++)f=a.ue.add(f,a.decode(b[e],c,d,
!1),b);return a.ue.finalize(f,b)}f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return f},Gza=function(a,b){if("~"===b.charAt(0)){var c=b.charAt(1);if("~"===c||"^"===c||"`"===c)return b.substring(1);if("#"===c)return new kW(b.substring(2));var d=a.Hb[c];return null==d?a.Ag(c,b.substring(2)):d(b.substring(2),a)}return b},Hza=function(a){this.dj=new lW(a)},mW=function(a,b){this.zk=a;this.options=b||{};this.cache=this.options.cache?this.options.cache:new OV},Jza=function(a){if(null==a)return"null";
if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var b=a[nW];null==b&&("undefined"!=typeof Object.defineProperty?(b=++Iza,Object.defineProperty(a,nW,{value:b,enumerable:!1})):a[nW]=b=++Iza);return b},oW=function(a,b){a=a.toString();for(var c=a.length;c<b;c++)a="0"+a;return a},pW=function(){},qW=function(){},rW=function(){},sW=function(){},tW=function(){},uW=function(){},vW=function(){},wW=function(){},xW=
function(){},yW=function(){},zW=function(){},AW=function(){},BW=function(){},CW=function(){},DW=function(){},EW=function(){},FW=function(){},GW=function(){},HW=function(){this.Hb={};this.set(null,new pW);this.set(String,new qW);this.set(Number,new rW);this.set($APP.ua,new sW);this.set(Boolean,new tW);this.set(Array,new uW);this.set(Object,new vW);this.set(Date,new xW);this.set(bW,new yW);this.set(ZV,new zW);this.set($V,new AW);this.set(XV,new BW);this.set(jW,new CW);this.set(fW,new DW);this.set(eW,
new EW);"undefined"!=typeof $APP.ny.Buffer&&this.set($APP.ny.Buffer,new FW);"undefined"!=typeof Uint8Array&&this.set(Uint8Array,new GW)},Kza=function(a){this.oc=a||{};this.Sf=null!=this.oc.preferStrings?this.oc.preferStrings:!0;this.Ah=this.oc.objectBuilder||null;this.transform=this.oc.transform||null;this.Hb=new HW;if(a=this.oc.handlers){if(PV(a)||!a.forEach)throw Error('transit writer "handlers" option must be a map');var b=this;a.forEach(function(c,d){if(void 0!==d)b.Hb.set(d,c);else throw Error("Cannot create handler for JavaScript undefined");
})}this.Ze=this.oc.handlerForForeign;this.ag=this.oc.unpack||function(c){return c instanceof fW&&null===c.Ya?c.$a:!1};this.pf=this.oc&&this.oc.verbose||!1},IW=function(a,b){var c=a.Hb.get(null==b?null:b.constructor);return null!=c?c:(b=b&&b.transitTag)?a.Hb.get(b):null},JW=function(a,b,c,d,e){a=a+b+c;return e?e.write(a,d):a},Lza=function(a,b,c){var d=[];if(PV(b))for(var e=0;e<b.length;e++)d.push(KW(a,b[e],!1,c));else b.forEach(function(f){d.push(KW(a,f,!1,c))});return d},LW=function(a,b){return"string"!==
typeof b?(a=IW(a,b))&&1===a.tag(b).length:!0},Mza=function(a,b){var c=a.ag(b),d=!0;if(c){for(b=0;b<c.length&&(d=LW(a,c[b]),d);b+=2);return d}if(b.keys){c=b.keys();var e=null;if(c.next){for(e=c.next();!e.done;){d=LW(a,e.value);if(!d)break;e=c.next()}return d}}if(b.forEach)return b.forEach(function(f,k){d=d&&LW(a,k)}),d;throw Error("Cannot walk keys of object type "+(null==b?null:b.constructor).name);},Nza=function(a){if(a.constructor.transit$isObject)return!0;var b=a.constructor.toString();b=b.substr(9);
b=b.substr(0,b.indexOf("("));b="Object"==b;"undefined"!=typeof Object.defineProperty?Object.defineProperty(a.constructor,"transit$isObject",{value:b,enumerable:!1}):a.constructor.transit$isObject=b;return b},Oza=function(a,b,c){var d=null,e=null,f=null;d=null;var k=0;if(b.constructor===Object||null!=b.forEach||a.Ze&&Nza(b)){if(a.pf){if(null!=b.forEach)if(Mza(a,b)){var n={};b.forEach(function(r,p){n[KW(a,p,!0,!1)]=KW(a,r,!1,c)})}else{d=a.ag(b);e=[];f=JW("~#","cmap","",!0,c);if(d)for(;k<d.length;k+=
2)e.push(KW(a,d[k],!1,!1)),e.push(KW(a,d[k+1],!1,c));else b.forEach(function(r,p){e.push(KW(a,p,!1,!1));e.push(KW(a,r,!1,c))});n={};n[f]=e}else for(d=RV(b),n={};k<d.length;k++)n[KW(a,d[k],!0,!1)]=KW(a,b[d[k]],!1,c);return n}if(null!=b.forEach){if(Mza(a,b)){d=a.ag(b);n=["^ "];if(d)for(;k<d.length;k+=2)n.push(KW(a,d[k],!0,c)),n.push(KW(a,d[k+1],!1,c));else b.forEach(function(r,p){n.push(KW(a,p,!0,c));n.push(KW(a,r,!1,c))});return n}d=a.ag(b);e=[];f=JW("~#","cmap","",!0,c);if(d)for(;k<d.length;k+=2)e.push(KW(a,
d[k],!1,c)),e.push(KW(a,d[k+1],!1,c));else b.forEach(function(r,p){e.push(KW(a,p,!1,c));e.push(KW(a,r,!1,c))});return[f,e]}n=["^ "];for(d=RV(b);k<d.length;k++)n.push(KW(a,d[k],!0,c)),n.push(KW(a,b[d[k]],!1,c));return n}if(null!=a.Ah)return a.Ah(b,function(r){return KW(a,r,!0,c)},function(r){return KW(a,r,!1,c)});k=(null==b?null:b.constructor).name;d=Error("Cannot write "+k);d.data={oa:b,type:k};throw d;},KW=function(a,b,c,d){null!==a.transform&&(b=a.transform(b));var e=IW(a,b)||(a.Ze?a.Ze(b,a.Hb):
null),f=e?e.tag(b):null,k=e?e.rep(b):null;if(null!=e&&null!=f)switch(f){case "_":return c?JW("~","_","",c,d):null;case "s":return 0<k.length?(a=k.charAt(0),a="~"===a||"^"===a||"`"===a?"~"+k:k):a=k,JW("","",a,c,d);case "?":return c?JW("~","?",k.toString()[0],c,d):k;case "i":return Infinity===k?JW("~","z","INF",c,d):-Infinity===k?JW("~","z","-INF",c,d):isNaN(k)?JW("~","z","NaN",c,d):c||"string"===typeof k||k instanceof $APP.ua?JW("~","i",k.toString(),c,d):k;case "d":return c?JW(k.Fk,"d",k,c,d):k;case "b":return JW("~",
"b",k,c,d);case "'":return a.pf?(c={},b=JW("~#","'","",!0,d),c[b]=KW(a,k,!1,d),d=c):d=[JW("~#","'","",!0,d),KW(a,k,!1,d)],d;case "array":return Lza(a,k,d);case "map":return Oza(a,k,d);default:a:{if(1===f.length){if("string"===typeof k){d=JW("~",f,k,c,d);break a}if(c||a.Sf){(a=a.pf&&e.getVerboseHandler())?(f=a.tag(b),k=a.stringRep(b,a)):k=e.stringRep(b,e);if(null!==k){d=JW("~",f,k,c,d);break a}d=Error('Tag "'+f+'" cannot be encoded as string');d.data={tag:f,rep:k,oa:b};throw d;}}c=f;b=k;a.pf?(e={},
e[JW("~#",c,"",!0,d)]=KW(a,b,!1,d),d=e):d=[JW("~#",c,"",!0,d),KW(a,b,!1,d)]}return d}else throw d=(null==b?null:b.constructor).name,a=Error("Cannot write "+d),a.data={oa:b,type:d},a;},MW=function(a,b){this.Ie=a;this.options=b||{};this.cache=!1===this.options.cache?null:this.options.cache?this.options.cache:new NV},Pza=function(a,b){if("json"===a||"json-verbose"===a||null==a)return a=new Hza(b),new mW(a,b);throw Error("Cannot create reader of type "+a);},Qza=function(a,b){if("json"===a||"json-verbose"===
a||null==a)return"json-verbose"===a&&(null==b&&(b={}),b.verbose=!0),a=new Kza(b),new MW(a,b);b=Error('Type must be "json"');b.data={type:a};throw b;},Rza=function(a,b){for(var c=$APP.u($APP.Oa(b)),d=null,e=0,f=0;;)if(f<e){var k=d.U(null,f);a[k]=$APP.Ua(b,k);f+=1}else if(c=$APP.u(c))d=c,$APP.gf(d)?(c=$APP.yd(d),f=$APP.zd(d),d=c,e=$APP.Ge(c),c=f):(c=$APP.v(d),a[c]=$APP.Ua(b,c),c=$APP.w(d),d=null,e=0),f=0;else break;return a},NW=function(){},OW=function(){},PW=function(a,b){return a.read(b)},QW=function(){},
RW=function(){},SW=function(){},TW=function(){},UW=function(){},VW=function(){},WW=function(){},Sza=function(a,b){this.value=a;this.H=b},XW=function(){},YW=function(a,b){return a.write(b)},ZW=function(a){return a},$W=function(a,b,c,d,e){this.$f=a;this.Uf=b;this.nf=c;this.qf=d;this.wj=e;this.G=393216;this.O=0},aX=function(a,b){return YV(a,b)},bX=function(a){return Aza(a)},cX=function(a){if(null!=a&&(a.G&131072||$APP.Wd===a.Zd)){var b=a.T(null);return null!=b?new Sza(a.V(null,null),b):a}return a};
$APP.ce.prototype.ja=$APP.ia(21,function(){return new $APP.ce(this.C,this.N,this.H)});$APP.Ke.prototype.ja=$APP.ia(20,function(){return new $APP.Ke(this.Ne,this.N,this.H)});$APP.D.prototype.ja=$APP.ia(19,function(){return new $APP.D(this.H,this.first,this.Db,this.count,this.I)});$APP.Lg.prototype.ja=$APP.ia(18,function(){return new $APP.Lg(this.H)});$APP.Qg.prototype.ja=$APP.ia(17,function(){return new $APP.Qg(this.H,this.first,this.Db,this.I)});
$APP.G.prototype.ja=$APP.ia(16,function(){return new $APP.G(this.H,this.J,this.shift,this.root,this.Kb,this.I)});$APP.Ni.prototype.ja=$APP.ia(15,function(){return new $APP.Ni(this.H,this.zb,this.start,this.end,this.I)});$APP.Vi.prototype.ja=$APP.ia(14,function(){return new $APP.Vi(this.H,this.count,this.bc,this.pc,this.I)});$APP.h.prototype.ja=$APP.ia(13,function(){return new $APP.h(this.H,this.J,this.C,this.I)});
$APP.Qj.prototype.ja=$APP.ia(12,function(){return new $APP.Qj(this.H,this.J,this.root,this.Fb,this.Ib,this.I)});$APP.ck.prototype.ja=$APP.ia(11,function(){return new $APP.ck(this.ac,this.Qc,this.J,this.H,this.I)});$APP.nk.prototype.ja=$APP.ia(10,function(){return new $APP.nk(this.H,this.Lc,this.I)});$APP.uk.prototype.ja=$APP.ia(9,function(){return new $APP.uk(this.H,this.uc,this.I)});$APP.Dk.prototype.ja=$APP.ia(8,function(){return new $APP.Dk(this.H,this.start,this.end,this.step,this.J,this.I)});
$APP.Ek.prototype.ja=$APP.ia(7,function(){return new $APP.Ek(this.H,this.start,this.end,this.step,this.Yb,this.Me,this.I)});$APP.on.prototype.ja=$APP.ia(6,function(){return new $APP.on(this.fd,this.form,this.K,this.F,this.I)});$APP.yr.prototype.ja=$APP.ia(5,function(){return new $APP.yr(this.vd,this.sd,this.K,this.F,this.I)});
$APP.xs.prototype.ja=$APP.ia(4,function(){return new $APP.xs(this.cb,this.deref,this.ob,this.pb,this.qb,this.quote,this.Na,this.Oa,this.kb,this.lb,this.mb,this.bb,this.gb,this.eb,this.source,this.nb,this.jb,this.hb,this.fb,this.ib,this.K,this.F,this.I)});$APP.Ps.prototype.ja=$APP.ia(3,function(){return new $APP.Ps(this.f,this.stack,this.K,this.F,this.I)});$APP.ev.prototype.ja=$APP.ia(2,function(){return new $APP.ev(this.Rd,this.type,this.Oa,this.Rb,this.Of)});
$APP.mw.prototype.ja=$APP.ia(1,function(){return new $APP.mw(this.tb,this.body,this.qc,this.vc,this.tc,this.rc,this.K,this.F,this.I)});$APP.ua.prototype.Xa=$APP.ia(0,function(){return this.ab^this.Ja});
var Tza=new $APP.t(null,"write-meta","write-meta",-1711397117,null),Uza=new $APP.t(null,"from-rep","from-rep",911750077,null),dX=new $APP.t(null,"str-rep-fn","str-rep-fn",-1179615016,null),Vza=new $APP.t(null,"ListHandler","ListHandler",-856350412,null),eX=new $APP.F(null,"handlers","handlers",79528781),Wza=new $APP.t("cognitect.transit","integer","cognitect.transit/integer",-1862495722,null),Xza=new $APP.t("cognitect.transit","write-meta","cognitect.transit/write-meta",-859929338,null),Yza=new $APP.F(null,
"arrayBuilder","arrayBuilder",1446317421),Zza=new $APP.F(null,"mapBuilder","mapBuilder",-278083754),$za=new $APP.F(null,"preferStrings","preferStrings",-1532249482),fX=new $APP.t(null,"tag-fn","tag-fn",242055482,null),gX=new $APP.t(null,"rep-fn","rep-fn",-1724891035,null),aAa=new $APP.t(null,"rep","rep",413710963,null),bAa=new $APP.t("cognitect.transit","ListHandler","cognitect.transit/ListHandler",397689651,null),cAa=new $APP.t(null,"tagged-value","tagged-value",-110559503,null),dAa=new $APP.t(null,
"write-handler","write-handler",-692059351,null),eAa=new $APP.F(null,"map-builder","map-builder",-1843343288),fAa=new $APP.t("cognitect.transit","reader","cognitect.transit/reader",1051062779,null),gAa=new $APP.F(null,"prefer-strings","prefer-strings",1254507185),hAa=new $APP.t("cognitect.transit","read-handler","cognitect.transit/read-handler",-523561611,null),iAa=new $APP.F(null,"array-builder","array-builder",1275998041),jAa=new $APP.t(null,"read-handler","read-handler",1426618230,null),kAa=new $APP.F(null,
"prefer-buffers","prefer-buffers",377042081),lAa=new $APP.t("cognitect.transit","write-handler","cognitect.transit/write-handler",-2147442390,null),mAa=new $APP.t("cognitect.transit","write","cognitect.transit/write",432992816,null),nAa=new $APP.t("cognitect.transit","writer","cognitect.transit/writer",-92501676,null),oAa=new $APP.t("cognitect.transit","read","cognitect.transit/read",-553970069,null),pAa=new $APP.t("cognitect.transit","tagged-value","cognitect.transit/tagged-value",1403542766,null),
qAa=new $APP.t(null,"w","w",1994700528,null),rAa=new $APP.F(null,"preferBuffers","preferBuffers",1843176451),hX=new $APP.t(null,"verbose-handler-fn","verbose-handler-fn",547340594,null),sAa=new $APP.t(null,"integer","integer",1035809817,null),tAa=new $APP.t(null,"write","write",-217117641,null);var RV="undefined"!=typeof Object.keys?function(a){return Object.keys(a)}:function(a){return $APP.Oa(a)},PV="undefined"!=typeof Array.isArray?function(a){return Array.isArray(a)}:function(a){return"array"===$APP.ja(a)};NV.prototype.write=function(a,b){return uza(a,b)?(4096===this.Fi?(this.clear(),this.Ye=0,this.cache={}):1936===this.sb&&this.clear(),b=this.cache[a],null==b?(this.cache[a]=[vza(this.sb),this.Ye],this.sb++,a):b[1]!=this.Ye?(b[1]=this.Ye,b[0]=vza(this.sb),this.sb++,a):b[0]):a};NV.prototype.clear=function(){this.sb=0;this.Ye++};OV.prototype.write=function(a){1936==this.sb&&(this.sb=0);this.cache[this.sb]=a;this.sb++;return a};
OV.prototype.read=function(a){return this.cache[2===a.length?a.charCodeAt(1)-48:44*(a.charCodeAt(1)-48)+(a.charCodeAt(2)-48)]};OV.prototype.clear=function(){this.sb=0};var xza=1,VV={},WV=0;var iX="undefined"!=typeof Symbol?Symbol.iterator:"@@iterator";XV.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};XV.prototype.equiv=function(a){return QV(this,a)};XV.prototype.equiv=XV.prototype.equiv;XV.prototype.Ic=function(a){return a instanceof XV?this.tag===a.tag&&QV(this.rep,a.rep):!1};XV.prototype.Vc=function(){-1===this.Xa&&(this.Xa=SV(TV(this.tag),TV(this.rep)));return this.Xa};var yza=LV("9007199254740991"),zza=LV("-9007199254740991");
$APP.ua.prototype.equiv=function(a){return QV(this,a)};$APP.ua.prototype.equiv=$APP.ua.prototype.equiv;$APP.ua.prototype.Ic=function(a){return a instanceof $APP.ua&&$APP.Da(this,a)};$APP.ua.prototype.Vc=function(){return this.ab};ZV.prototype.toString=function(){return":"+this.Ab};ZV.prototype.namespace=function(){var a=this.Ab.indexOf("/");return-1!=a?this.Ab.substring(0,a):null};ZV.prototype.name=function(){var a=this.Ab.indexOf("/");return-1!=a?this.Ab.substring(a+1,this.Ab.length):this.Ab};
ZV.prototype.equiv=function(a){return QV(this,a)};ZV.prototype.equiv=ZV.prototype.equiv;ZV.prototype.Ic=function(a){return a instanceof ZV&&this.Ab==a.Ab};ZV.prototype.Vc=function(){-1===this.Xa&&(this.Xa=TV(this.Ab));return this.Xa};$V.prototype.namespace=function(){var a=this.Ab.indexOf("/");return-1!=a?this.Ab.substring(0,a):null};$V.prototype.name=function(){var a=this.Ab.indexOf("/");return-1!=a?this.Ab.substring(a+1,this.Ab.length):this.Ab};$V.prototype.toString=function(){return this.Ab};
$V.prototype.equiv=function(a){return QV(this,a)};$V.prototype.equiv=$V.prototype.equiv;$V.prototype.Ic=function(a){return a instanceof $V&&this.Ab==a.Ab};$V.prototype.Vc=function(){-1===this.Xa&&(this.Xa=TV(this.Ab));return this.Xa};bW.prototype.toString=function(){var a=this.high,b=this.low;var c=aW(a,0,4)+"-";c+=aW(a,4,6)+"-";c+=aW(a,6,8)+"-";c+=aW(b,0,2)+"-";return c+=aW(b,2,8)};bW.prototype.equiv=function(a){return QV(this,a)};bW.prototype.equiv=bW.prototype.equiv;
bW.prototype.Ic=function(a){return a instanceof bW&&$APP.Da(this.high,a.high)&&$APP.Da(this.low,a.low)};bW.prototype.Vc=function(){-1===this.Xa&&(this.Xa=TV(this.toString()));return this.Xa};Date.prototype.Ic=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.Vc=function(){return this.valueOf()};
cW.prototype.next=function(){if(this.sb<this.entries.length){var a={value:0===this.type?this.entries[this.sb]:1===this.type?this.entries[this.sb+1]:[this.entries[this.sb],this.entries[this.sb+1]],done:!1};this.sb+=2;return a}return{value:null,done:!0}};cW.prototype.next=cW.prototype.next;cW.prototype[iX]=function(){return this};
dW.prototype.next=function(){if(this.sb<this.map.size){null!=this.Ud&&this.Id<this.Ud.length||(this.Ud=this.map.map[this.keys[this.sb]],this.Id=0);var a={value:0===this.type?this.Ud[this.Id]:1===this.type?this.Ud[this.Id+1]:[this.Ud[this.Id],this.Ud[this.Id+1]],done:!1};this.sb++;this.Id+=2;return a}return{value:null,done:!0}};dW.prototype.next=dW.prototype.next;dW.prototype[iX]=function(){return this};fW.prototype.toString=function(){return Bza(this)};fW.prototype.inspect=function(){return this.toString()};
fW.prototype.clear=function(){this.Xa=-1;this.Ya?this.Ya.clear():this.$a=[];this.size=0};fW.prototype.clear=fW.prototype.clear;fW.prototype.keys=function(){return this.Ya?this.Ya.keys():new cW(this.$a,0)};fW.prototype.keys=fW.prototype.keys;fW.prototype.je=function(){if(this.Ya)return this.Ya.je();for(var a=[],b=0,c=0;c<this.$a.length;b++,c+=2)a[b]=this.$a[c];return a};fW.prototype.keySet=fW.prototype.je;fW.prototype.entries=function(){return this.Ya?this.Ya.entries():new cW(this.$a,2)};
fW.prototype.entries=fW.prototype.entries;fW.prototype.values=function(){return this.Ya?this.Ya.values():new cW(this.$a,1)};fW.prototype.values=fW.prototype.values;fW.prototype.forEach=function(a){if(this.Ya)this.Ya.forEach(a);else for(var b=0;b<this.$a.length;b+=2)a(this.$a[b+1],this.$a[b])};fW.prototype.forEach=fW.prototype.forEach;
fW.prototype.get=function(a,b){if(this.Ya)return this.Ya.get(a);if(Dza(this))return this.get(a);for(var c=0;c<this.$a.length;c+=2)if(QV(this.$a[c],a))return this.$a[c+1];return b};fW.prototype.get=fW.prototype.get;fW.prototype.has=function(a){if(this.Ya)return this.Ya.has(a);if(Dza(this))return this.has(a);for(var b=0;b<this.$a.length;b+=2)if(QV(this.$a[b],a))return!0;return!1};fW.prototype.has=fW.prototype.has;
fW.prototype.set=function(a,b){this.Xa=-1;if(this.Ya)this.Ya.set(a,b),this.size=this.Ya.size;else{for(var c=0;c<this.$a.length;c+=2)if(QV(this.$a[c],a)){this.$a[c+1]=b;return}this.$a.push(a);this.$a.push(b);this.size++;32<this.size&&(this.Ya=iW(this.$a,!1,!0),this.$a=null)}};fW.prototype.set=fW.prototype.set;
fW.prototype["delete"]=function(a){this.Xa=-1;if(this.Ya)return a=this.Ya.delete(a),this.size=this.Ya.size,a;for(var b=0;b<this.$a.length;b+=2)if(QV(this.$a[b],a))return a=this.$a[b+1],this.$a.splice(b,2),this.size--,a};fW.prototype.clone=function(){var a=iW();this.forEach(function(b,c){a.set(c,b)});return a};fW.prototype.clone=fW.prototype.clone;fW.prototype[iX]=function(){return this.entries()};fW.prototype.Vc=function(){if(this.Ya)return this.Ya.Vc();-1===this.Xa&&(this.Xa=UV(this));return this.Xa};
fW.prototype.Ic=function(a){return this.Ya?gW(this.Ya,a):gW(this,a)};eW.prototype.toString=function(){return Bza(this)};eW.prototype.inspect=function(){return this.toString()};eW.prototype.clear=function(){this.Xa=-1;this.map={};this.te=[];this.size=0};eW.prototype.clear=eW.prototype.clear;eW.prototype.ge=function(){return null!=this.te?this.te:RV(this.map)};
eW.prototype["delete"]=function(a){this.Xa=-1;this.te=null;for(var b=TV(a),c=this.map[b],d=0;d<c.length;d+=2)if(QV(a,c[d]))return a=c[d+1],c.splice(d,2),0===c.length&&delete this.map[b],this.size--,a};eW.prototype.entries=function(){return new dW(this,2)};eW.prototype.entries=eW.prototype.entries;eW.prototype.forEach=function(a){for(var b=this.ge(),c=0;c<b.length;c++)for(var d=this.map[b[c]],e=0;e<d.length;e+=2)a(d[e+1],d[e],this)};eW.prototype.forEach=eW.prototype.forEach;
eW.prototype.get=function(a,b){var c=TV(a);c=this.map[c];if(null!=c)for(b=0;b<c.length;b+=2){if(QV(a,c[b]))return c[b+1]}else return b};eW.prototype.get=eW.prototype.get;eW.prototype.has=function(a){var b=TV(a);b=this.map[b];if(null!=b)for(var c=0;c<b.length;c+=2)if(QV(a,b[c]))return!0;return!1};eW.prototype.has=eW.prototype.has;eW.prototype.keys=function(){return new dW(this,0)};eW.prototype.keys=eW.prototype.keys;
eW.prototype.je=function(){for(var a=this.ge(),b=[],c=0;c<a.length;c++)for(var d=this.map[a[c]],e=0;e<d.length;e+=2)b.push(d[e]);return b};eW.prototype.keySet=eW.prototype.je;eW.prototype.set=function(a,b){this.Xa=-1;var c=TV(a),d=this.map[c];if(null==d)this.te&&this.te.push(c),this.map[c]=[a,b],this.size++;else{c=!0;for(var e=0;e<d.length;e+=2)if(QV(b,d[e])){c=!1;d[e]=b;break}c&&(d.push(a),d.push(b),this.size++)}};eW.prototype.set=eW.prototype.set;
eW.prototype.values=function(){return new dW(this,1)};eW.prototype.values=eW.prototype.values;eW.prototype.clone=function(){var a=iW();this.forEach(function(b,c){a.set(c,b)});return a};eW.prototype.clone=eW.prototype.clone;eW.prototype[iX]=function(){return this.entries()};eW.prototype.Vc=function(){-1===this.Xa&&(this.Xa=UV(this));return this.Xa};eW.prototype.Ic=function(a){return gW(this,a)};jW.prototype.toString=function(){return Cza(this)};jW.prototype.inspect=function(){return this.toString()};
jW.prototype.add=function(a){this.map.set(a,a);this.size=this.map.size};jW.prototype.add=jW.prototype.add;jW.prototype.clear=function(){this.map=new eW;this.size=0};jW.prototype.clear=jW.prototype.clear;jW.prototype["delete"]=function(a){a=this.map.delete(a);this.size=this.map.size;return a};jW.prototype.entries=function(){return this.map.entries()};jW.prototype.entries=jW.prototype.entries;jW.prototype.forEach=function(a){var b=this;this.map.forEach(function(c,d){a(d,b)})};jW.prototype.forEach=jW.prototype.forEach;
jW.prototype.has=function(a){return this.map.has(a)};jW.prototype.has=jW.prototype.has;jW.prototype.keys=function(){return this.map.keys()};jW.prototype.keys=jW.prototype.keys;jW.prototype.je=function(){return this.map.je()};jW.prototype.keySet=jW.prototype.je;jW.prototype.values=function(){return this.map.values()};jW.prototype.values=jW.prototype.values;jW.prototype.clone=function(){var a=Eza();this.forEach(function(b){a.add(b)});return a};jW.prototype.clone=jW.prototype.clone;
jW.prototype[iX]=function(){return this.values()};jW.prototype.Ic=function(a){if(a instanceof jW){if(this.size===a.size)return QV(this.map,a.map)}else return!1};jW.prototype.Vc=function(){return TV(this.map)};lW.prototype.Ve={Hb:{_:function(){return null},"?":function(a){return"t"===a},b:function(a,b){if(b&&!1===b.Hg||"undefined"==typeof $APP.ny.Buffer)if("undefined"!=typeof Uint8Array){if("undefined"!=typeof atob)var c=atob(a);else{a=String(a).replace(/=+$/,"");if(1==a.length%4)throw Error("'atob' failed: The string to be decoded is not correctly encoded.");b=0;for(var d,e=0,f="";d=a.charAt(e++);~d&&(c=b%4?64*c+d:d,b++%4)?f+=String.fromCharCode(255&c>>(-2*b&6)):0)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(d);
c=f}a=c.length;b=new Uint8Array(a);for(d=0;d<a;d++)b[d]=c.charCodeAt(d);c=b}else c=YV("b",a);else c=new $APP.ny.Buffer(a,"base64");return c},i:function(a){return Aza(a)},n:function(a){return YV("n",a)},d:function(a){return parseFloat(a)},f:function(a){return YV("f",a)},c:function(a){return a},":":function(a){return new ZV(a)},$:function(a){return new $V(a)},r:function(a){return YV("r",a)},z:function(a){a:switch(a){case "-INF":a=-Infinity;break a;case "INF":a=Infinity;break a;case "NaN":a=NaN;break a;
default:throw Error("Invalid special double value "+a);}return a},"'":function(a){return a},m:function(a){a="number"===typeof a?a:parseInt(a,10);return new Date(a)},t:function(a){return new Date(a)},u:function(a){a=a.replace(/-/g,"");var b,c;var d=b=0;for(c=24;8>d;d+=2,c-=8)b|=parseInt(a.substring(d,d+2),16)<<c;var e=0;d=8;for(c=24;16>d;d+=2,c-=8)e|=parseInt(a.substring(d,d+2),16)<<c;var f=$APP.va(e,b);b=0;d=16;for(c=24;24>d;d+=2,c-=8)b|=parseInt(a.substring(d,d+2),16)<<c;e=0;for(c=d=24;32>d;d+=2,
c-=8)e|=parseInt(a.substring(d,d+2),16)<<c;return new bW(f,$APP.va(e,b))},set:function(a){return Eza(a)},list:function(a){return YV("list",a)},link:function(a){return YV("link",a)},cmap:function(a){return iW(a,!1)}},Ag:function(a,b){return YV(a,b)},Sf:!0,Hg:!0};
lW.prototype.decode=function(a,b,c,d){if(null==a)return null;switch(typeof a){case "string":return uza(a,c)?(a=Gza(this,a),b&&b.write(a,c),b=a):b="^"===a.charAt(0)&&" "!==a.charAt(1)?b.read(a,c):Gza(this,a),b;case "object":if(PV(a))if("^ "===a[0])if(this.Nc)if(17>a.length&&this.Nc.fromArray){d=[];for(c=1;c<a.length;c+=2)d.push(this.decode(a[c],b,!0,!1)),d.push(this.decode(a[c+1],b,!1,!1));b=this.Nc.fromArray(d,a)}else{d=this.Nc.init(a);for(c=1;c<a.length;c+=2)d=this.Nc.add(d,this.decode(a[c],b,!0,
!1),this.decode(a[c+1],b,!1,!1),a);b=this.Nc.finalize(d,a)}else{d=[];for(c=1;c<a.length;c+=2)d.push(this.decode(a[c],b,!0,!1)),d.push(this.decode(a[c+1],b,!1,!1));b=iW(d,!1)}else b=Fza(this,a,b,c,d);else{c=RV(a);var e=c[0];if((d=1==c.length?this.decode(e,b,!1,!1):null)&&d instanceof kW)a=a[e],c=this.Hb[d.dc],b=null!=c?c(this.decode(a,b,!1,!0),this):YV(d.dc,this.decode(a,b,!1,!1));else if(this.Nc)if(16>c.length&&this.Nc.fromArray){var f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.decode(e,b,!0,!1)),
f.push(this.decode(a[e],b,!1,!1));b=this.Nc.fromArray(f,a)}else{f=this.Nc.init(a);for(d=0;d<c.length;d++)e=c[d],f=this.Nc.add(f,this.decode(e,b,!0,!1),this.decode(a[e],b,!1,!1),a);b=this.Nc.finalize(f,a)}else{f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.decode(e,b,!0,!1)),f.push(this.decode(a[e],b,!1,!1));b=iW(f,!1)}}return b}return a};lW.prototype.decode=lW.prototype.decode;mW.prototype.read=function(a){var b=this.cache;a=this.zk.dj.decode(JSON.parse(a),b);this.cache.clear();return a};mW.prototype.read=mW.prototype.read;var Iza=0,uAa=(8|3&Math.round(14*Math.random())).toString(16),nW="transit$guid$"+(MV()+MV()+MV()+MV()+MV()+MV()+MV()+MV()+"-"+MV()+MV()+MV()+MV()+"-4"+MV()+MV()+MV()+"-"+uAa+MV()+MV()+MV()+"-"+MV()+MV()+MV()+MV()+MV()+MV()+MV()+MV()+MV()+MV()+MV()+MV());pW.prototype.tag=function(){return"_"};pW.prototype.rep=function(){return null};pW.prototype.stringRep=function(){return"null"};qW.prototype.tag=function(){return"s"};qW.prototype.rep=function(a){return a};qW.prototype.stringRep=function(a){return a};
rW.prototype.tag=function(){return"i"};rW.prototype.rep=function(a){return a};rW.prototype.stringRep=function(a){return a.toString()};sW.prototype.tag=function(){return"i"};sW.prototype.rep=function(a){return a.toString()};sW.prototype.stringRep=function(a){return a.toString()};tW.prototype.tag=function(){return"?"};tW.prototype.rep=function(a){return a};tW.prototype.stringRep=function(a){return a.toString()};uW.prototype.tag=function(){return"array"};uW.prototype.rep=function(a){return a};
uW.prototype.stringRep=function(){return null};vW.prototype.tag=function(){return"map"};vW.prototype.rep=function(a){return a};vW.prototype.stringRep=function(){return null};wW.prototype.tag=function(){return"t"};wW.prototype.rep=function(a){return a.getUTCFullYear()+"-"+oW(a.getUTCMonth()+1,2)+"-"+oW(a.getUTCDate(),2)+"T"+oW(a.getUTCHours(),2)+":"+oW(a.getUTCMinutes(),2)+":"+oW(a.getUTCSeconds(),2)+"."+oW(a.getUTCMilliseconds(),3)+"Z"};wW.prototype.stringRep=function(a,b){return b.rep(a)};
xW.prototype.tag=function(){return"m"};xW.prototype.rep=function(a){return a.valueOf()};xW.prototype.stringRep=function(a){return a.valueOf().toString()};xW.prototype.getVerboseHandler=function(){return new wW};yW.prototype.tag=function(){return"u"};yW.prototype.rep=function(a){return a.toString()};yW.prototype.stringRep=function(a){return a.toString()};zW.prototype.tag=function(){return":"};zW.prototype.rep=function(a){return a.Ab};zW.prototype.stringRep=function(a,b){return b.rep(a)};
AW.prototype.tag=function(){return"$"};AW.prototype.rep=function(a){return a.Ab};AW.prototype.stringRep=function(a,b){return b.rep(a)};BW.prototype.tag=function(a){return a.tag};BW.prototype.rep=function(a){return a.rep};BW.prototype.stringRep=function(){return null};CW.prototype.tag=function(){return"set"};CW.prototype.rep=function(a){var b=[];a.forEach(function(c){b.push(c)});return YV("array",b)};CW.prototype.stringRep=function(){return null};DW.prototype.tag=function(){return"map"};
DW.prototype.rep=function(a){return a};DW.prototype.stringRep=function(){return null};EW.prototype.tag=function(){return"map"};EW.prototype.rep=function(a){return a};EW.prototype.stringRep=function(){return null};FW.prototype.tag=function(){return"b"};FW.prototype.rep=function(a){return a.toString("base64")};FW.prototype.stringRep=function(){return null};GW.prototype.tag=function(){return"b"};
GW.prototype.rep=function(a){for(var b,c=0,d=a.length,e="",f;c<d;)f=a.subarray(c,Math.min(c+32768,d)),e+=String.fromCharCode.apply(null,f),c+=32768;if("undefined"!=typeof btoa)b=btoa(e);else{a=String(e);d=0;e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d";for(f="";a.charAt(d|0)||(e="\x3d",d%1);f+=e.charAt(63&b>>8-d%1*8)){c=a.charCodeAt(d+=.75);if(255<c)throw Error("'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.");b=b<<8|c}b=f}return b};
GW.prototype.stringRep=function(){return null};HW.prototype.get=function(a){a="string"===typeof a?this.Hb[a]:this.Hb[Jza(a)];return null!=a?a:this.Hb["default"]};HW.prototype.get=HW.prototype.get;HW.prototype.set=function(a,b){var c;if(c="string"===typeof a)a:{switch(a){case "null":case "string":case "boolean":case "number":case "array":case "map":c=!1;break a}c=!0}c?this.Hb[a]=b:this.Hb[Jza(a)]=b};MW.prototype.tj=function(){return this.Ie};MW.prototype.marshaller=MW.prototype.tj;
MW.prototype.write=function(a,b){var c=b||{};b=c.asMapKey||!1;var d=this.Ie.pf?!1:this.cache;if(!1===c.marshalTop)a=KW(this.Ie,a,b,d);else{c=this.Ie;var e=JSON,f=e.stringify,k=KW;var n=IW(c,a)||(c.Ze?c.Ze(a,c.Hb):null);if(null!=n)a=1===n.tag(a).length?YV("'",a):a;else throw b=(null==a?null:a.constructor).name,d=Error("Cannot write "+b),d.data={oa:a,type:b},d;a=f.call(e,k(c,a,b,d))}null!=this.cache&&this.cache.clear();return a};MW.prototype.write=MW.prototype.write;
MW.prototype.register=function(a,b){this.Ie.Hb.set(a,b)};MW.prototype.register=MW.prototype.register;$APP.bm.prototype.P=function(a,b){return b instanceof $APP.bm?this.Cc===b.Cc:b instanceof bW?this.Cc===b.toString():!1};$APP.bm.prototype.kd=$APP.Wd;$APP.bm.prototype.xc=function(a,b){if(b instanceof $APP.bm||b instanceof bW)return $APP.Cf(this.toString(),b.toString());throw Error(["Cannot compare ",$APP.m.g(this)," to ",$APP.m.g(b)].join(""));};bW.prototype.kd=$APP.Wd;
bW.prototype.xc=function(a,b){if(b instanceof $APP.bm||b instanceof bW)return $APP.Cf(this.toString(),b.toString());throw Error(["Cannot compare ",$APP.m.g(this)," to ",$APP.m.g(b)].join(""));};$APP.ua.prototype.P=function(a,b){return this.equiv(b)};bW.prototype.P=function(a,b){return b instanceof $APP.bm?b.P(null,this):this.equiv(b)};XV.prototype.P=function(a,b){return this.equiv(b)};$APP.ua.prototype.lg=$APP.Wd;$APP.ua.prototype.da=function(){return TV(this)};bW.prototype.lg=$APP.Wd;
bW.prototype.da=function(){return $APP.Xd(this.toString())};XV.prototype.lg=$APP.Wd;XV.prototype.da=function(){return TV(this)};bW.prototype.vg=$APP.Wd;bW.prototype.sa=$APP.Wd;bW.prototype.X=function(a,b){return $APP.hd(b,['#uuid "',$APP.m.g(this.toString()),'"'].join(""))};NW.prototype.init=function(){return $APP.od($APP.th)};NW.prototype.add=function(a,b,c){return $APP.kj.j(a,b,c)};NW.prototype.finalize=function(a){return $APP.qd(a)};
NW.prototype.fromArray=function(a){return $APP.fj.j?$APP.fj.j(a,!0,!0):$APP.fj.call(null,a,!0,!0)};OW.prototype.init=function(){return $APP.od($APP.oi)};OW.prototype.add=function(a,b){return $APP.ni.h(a,b)};OW.prototype.finalize=function(a){return $APP.qd(a)};OW.prototype.fromArray=function(a){return $APP.Ei.h?$APP.Ei.h(a,!0):$APP.Ei.call(null,a,!0)};
var jX=function jX(a){switch(arguments.length){case 1:return jX.g(arguments[0]);case 2:return jX.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};jX.g=function(a){return jX.h(a,null)};
jX.h=function(a,b){return Pza($APP.xk(a),Rza({handlers:$APP.dC($APP.Tn.l($APP.B([new $APP.h(null,6,["$",function(c){return $APP.dl.g(c)},":",function(c){return $APP.Xk.g(c)},"set",function(c){return $APP.hj.h($APP.ok,c)},"list",function(c){return $APP.hj.h($APP.fe,c.reverse())},"cmap",function(c){for(var d=0,e=$APP.od($APP.th);;)if(d<c.length){var f=d+2;e=$APP.kj.j(e,c[d],c[d+1]);d=f}else return $APP.qd(e)},"with-meta",function(c){return $APP.Ue(c[0],c[1])}],null),$APP.Un.h(eX.g(b),$APP.fp)]))),defaultHandler:$APP.fp.g(eX.g(b)),
mapBuilder:new NW,arrayBuilder:new OW,preferStrings:!1,preferBuffers:!1},$APP.dC($APP.cx($APP.Un.h(b,eX),new $APP.h(null,4,[iAa,Yza,eAa,Zza,gAa,$za,kAa,rAa],null)))))};jX.o=2;QW.prototype.tag=function(){return":"};QW.prototype.rep=function(a){return a.ga};QW.prototype.stringRep=function(a){return a.ga};RW.prototype.tag=function(){return"$"};RW.prototype.rep=function(a){return a.dc};RW.prototype.stringRep=function(a){return a.dc};SW.prototype.tag=function(){return"list"};
SW.prototype.rep=function(a){var b=[];a=$APP.u(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.U(null,e);b.push(f);e+=1}else if(a=$APP.u(a))c=a,$APP.gf(c)?(a=$APP.yd(c),e=$APP.zd(c),c=a,d=$APP.Ge(a),a=e):(a=$APP.v(c),b.push(a),a=$APP.w(c),c=null,d=0),e=0;else break;return YV("array",b)};SW.prototype.stringRep=function(){return null};TW.prototype.tag=function(){return"map"};TW.prototype.rep=function(a){return a};TW.prototype.stringRep=function(){return null};UW.prototype.tag=function(){return"set"};
UW.prototype.rep=function(a){var b=[];a=$APP.u(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.U(null,e);b.push(f);e+=1}else if(a=$APP.u(a))c=a,$APP.gf(c)?(a=$APP.yd(c),e=$APP.zd(c),c=a,d=$APP.Ge(a),a=e):(a=$APP.v(c),b.push(a),a=$APP.w(c),c=null,d=0),e=0;else break;return YV("array",b)};UW.prototype.stringRep=function(){return null};VW.prototype.tag=function(){return"array"};
VW.prototype.rep=function(a){var b=[];a=$APP.u(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.U(null,e);b.push(f);e+=1}else if(a=$APP.u(a))c=a,$APP.gf(c)?(a=$APP.yd(c),e=$APP.zd(c),c=a,d=$APP.Ge(a),a=e):(a=$APP.v(c),b.push(a),a=$APP.w(c),c=null,d=0),e=0;else break;return b};VW.prototype.stringRep=function(){return null};WW.prototype.tag=function(){return"u"};WW.prototype.rep=function(a){return a.Cc};WW.prototype.stringRep=function(a){return this.rep(a)};XW.prototype.tag=function(){return"with-meta"};
XW.prototype.rep=function(a){return YV("array",[a.value,a.H])};XW.prototype.stringRep=function(){return null};var kX=function kX(a){switch(arguments.length){case 1:return kX.g(arguments[0]);case 2:return kX.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};kX.g=function(a){return kX.h(a,null)};
kX.h=function(a,b){var c=new SW,d=new TW,e=new UW,f=new VW,k=$APP.Tn.l($APP.B([$APP.Rj([$APP.Qj,$APP.Qg,$APP.h,$APP.Dj,$APP.Vi,$APP.ce,$APP.F,$APP.Yj,$APP.Lg,$APP.bh,$APP.Ni,$APP.Ui,$APP.Lj,$APP.gk,Sza,$APP.dj,$APP.G,$APP.D,$APP.Ke,$APP.nk,$APP.ck,$APP.ek,$APP.Ji,$APP.uk,$APP.gh,$APP.t,$APP.bm,$APP.Ek,$APP.Vj,$APP.Xj],[d,c,d,c,c,c,new QW,f,c,c,f,c,c,c,new XW,c,f,c,c,e,d,c,c,e,c,new RW,new WW,c,c,f]),"undefined"!==typeof $APP.DA&&"undefined"!==typeof $APP.EA&&"undefined"!==typeof $APP.ml?$APP.sh([$APP.ml,
c]):null,"undefined"!==typeof $APP.DA&&"undefined"!==typeof $APP.EA&&"undefined"!==typeof $APP.gi?$APP.sh([$APP.gi,c]):null,"undefined"!==typeof $APP.DA&&"undefined"!==typeof $APP.EA&&"undefined"!==typeof $APP.Af?$APP.sh([$APP.Af,f]):null,eX.g(b)]));return Qza($APP.xk(a),Rza({objectBuilder:function(n,r,p){return $APP.Lf(function(y,z,E){y.push(r.g?r.g(z):r.call(null,z),p.g?p.g(E):p.call(null,E));return y},["^ "],n)},handlers:function(){var n=KV(k);n.forEach=function(r){for(var p=$APP.u(this),y=null,
z=0,E=0;;)if(E<z){var H=y.U(null,E),P=$APP.A.j(H,0,null);H=$APP.A.j(H,1,null);$APP.x.h($APP.fp,P)?r.h?r.h(H,"default"):r.call(null,H,"default"):r.h?r.h(H,P):r.call(null,H,P);E+=1}else if(p=$APP.u(p))$APP.gf(p)?(y=$APP.yd(p),p=$APP.zd(p),P=y,z=$APP.Ge(y),y=P):(y=$APP.v(p),P=$APP.A.j(y,0,null),H=$APP.A.j(y,1,null),$APP.x.h($APP.fp,P)?r.h?r.h(H,"default"):r.call(null,H,"default"):r.h?r.h(H,P):r.call(null,H,P),p=$APP.w(p),y=null,z=0),E=0;else return null};return n}(),unpack:function(n){return n instanceof
$APP.h?n.C:!1}},$APP.dC($APP.Un.h(b,eX))))};kX.o=2;$APP.g=$W.prototype;$APP.g.V=function(a,b){return new $W(this.$f,this.Uf,this.nf,this.qf,b)};$APP.g.T=function(){return this.wj};$APP.g.tag=function(a){return this.$f.g?this.$f.g(a):this.$f.call(null,a)};$APP.g.rep=function(a){return this.Uf.g?this.Uf.g(a):this.Uf.call(null,a)};$APP.g.stringRep=function(a){return $APP.l(this.nf)?this.nf.g?this.nf.g(a):this.nf.call(null,a):null};
$APP.g.getVerboseHandler=function(){return $APP.l(this.qf)?this.qf.v?this.qf.v():this.qf.call(null):null};var lX=function lX(a){switch(arguments.length){case 2:return lX.h(arguments[0],arguments[1]);case 3:return lX.j(arguments[0],arguments[1],arguments[2]);case 4:return lX.B(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};lX.h=function(a,b){return lX.B(a,b,null,null)};lX.j=function(a,b,c){return lX.B(a,b,c,null)};
lX.B=function(a,b,c,d){return new $W($APP.Se(a)?a:$APP.Qh(a),$APP.Se(b)?b:$APP.Qh(b),$APP.Se(c)?c:$APP.Qh(c),$APP.Se(d)?d:$APP.Qh(d),$APP.th)};lX.o=4;var mX=$APP.mV.h($APP.mM,null),vAa=$APP.Rj([dAa,cAa,tAa,$APP.XE,Vza,Tza,sAa,jAa,$APP.wD,$APP.WC],[function(){var a=new $APP.ae(function(){return lX},lAa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.mM,dAa,"cognitect/transit.cljs",20,new $APP.h(null,6,[$APP.AD,!1,$APP.tw,4,$APP.SQ,4,$APP.hQ,new $APP.G(null,3,5,$APP.I,[new $APP.G(null,2,5,$APP.I,[fX,gX],null),new $APP.G(null,3,5,$APP.I,[fX,gX,dX],null),new $APP.G(null,4,5,$APP.I,[fX,gX,dX,hX],null)],
null),$APP.Z,$APP.J(new $APP.G(null,2,5,$APP.I,[fX,gX],null),new $APP.G(null,3,5,$APP.I,[fX,gX,dX],null),new $APP.G(null,4,5,$APP.I,[fX,gX,dX,hX],null)),$APP.QI,$APP.J(null,null,null)],null),1,309,309,$APP.J(new $APP.G(null,2,5,$APP.I,[fX,gX],null),new $APP.G(null,3,5,$APP.I,[fX,gX,dX],null),new $APP.G(null,4,5,$APP.I,[fX,gX,dX,hX],null)),"Creates a transit write handler whose tag, rep,\n   stringRep, and verboseWriteHandler methods\n   invoke the provided fns.",$APP.l(lX)?lX.D:null])),b=$APP.q(a),
c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,mX,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return aX},pAa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.mM,cAa,"cognitect/transit.cljs",19,1,332,332,$APP.J(new $APP.G(null,
2,5,$APP.I,[$APP.XL,aAa],null)),"Construct a tagged value. tag must be a string and rep can\n   be any transit encodeable value.",$APP.l(aX)?aX.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,mX,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return YW},
mAa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.mM,tAa,"cognitect/transit.cljs",12,1,294,294,$APP.J(new $APP.G(null,2,5,$APP.I,[qAa,$APP.KN],null)),"Encode an object into a transit string given a transit writer.",$APP.l(YW)?YW.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,mX,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);
return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return PW},oAa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.mM,$APP.XE,"cognitect/transit.cljs",11,1,146,146,$APP.J(new $APP.G(null,2,5,$APP.I,[$APP.LN,$APP.JL],null)),"Read a transit encoded string into ClojureScript values given a\n   transit reader.",$APP.l(PW)?PW.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=
new $APP.h(null,4,[$APP.W,mX,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return SW},bAa,new $APP.h(null,8,[$APP.W,$APP.mM,$APP.M,null,$APP.ao,"cognitect/transit.cljs",$APP.bo,164,$APP.hp,19,$APP.O,Vza,$APP.WI,$APP.l(SW)?SW.D:null,$APP.Z,$APP.fe],null)),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:
$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,mX,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return cX},Xza,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.mM,Tza,"cognitect/transit.cljs",17,1,432,432,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.RN],null)),"For :transform. Will write any metadata present on the value.",
$APP.l(cX)?cX.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,mX,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return bX},Wza,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.mM,sAa,"cognitect/transit.cljs",
14,1,343,343,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.ON],null)),"Construct a transit integer value. Returns JavaScript number if\n  in the 53bit integer range, a goog.math.Long instance if above. s\n  may be a string or a JavaScript number.",$APP.l(bX)?bX.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,mX,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?
e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return ZW},hAa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.mM,jAa,"cognitect/transit.cljs",19,1,299,299,$APP.J(new $APP.G(null,1,5,$APP.I,[Uza],null)),"Construct a read handler. Implemented as identity, exists primarily\n   for API compatiblity with transit-clj",$APP.l(ZW)?ZW.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,
4,[$APP.W,mX,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return jX},fAa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.mM,$APP.wD,"cognitect/transit.cljs",13,new $APP.h(null,6,[$APP.AD,!1,$APP.tw,2,$APP.SQ,2,$APP.hQ,new $APP.G(null,2,5,$APP.I,
[new $APP.G(null,1,5,$APP.I,[$APP.YH],null),new $APP.G(null,2,5,$APP.I,[$APP.YH,$APP.DK],null)],null),$APP.Z,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.YH],null),new $APP.G(null,2,5,$APP.I,[$APP.YH,$APP.DK],null)),$APP.QI,$APP.J(null,null)],null),1,106,106,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.YH],null),new $APP.G(null,2,5,$APP.I,[$APP.YH,$APP.DK],null)),"Return a transit reader. type may be either :json or :json-verbose.\n   opts may be a map optionally containing a :handlers entry. The value\n   of :handlers should be map from string tag to a decoder function of one\n   argument which returns the in-memory representation of the semantic transit\n   value. If a :default handler is provided, it will be used when no matching\n   read handler can be found.",
$APP.l(jX)?jX.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,mX,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),function(){var a=new $APP.ae(function(){return kX},nAa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.XC,$APP.uO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[$APP.mM,$APP.WC,"cognitect/transit.cljs",
13,new $APP.h(null,6,[$APP.AD,!1,$APP.tw,2,$APP.SQ,2,$APP.hQ,new $APP.G(null,2,5,$APP.I,[new $APP.G(null,1,5,$APP.I,[$APP.YH],null),new $APP.G(null,2,5,$APP.I,[$APP.YH,$APP.DK],null)],null),$APP.Z,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.YH],null),new $APP.G(null,2,5,$APP.I,[$APP.YH,$APP.DK],null)),$APP.QI,$APP.J(null,null)],null),1,212,212,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.YH],null),new $APP.G(null,2,5,$APP.I,[$APP.YH,$APP.DK],null)),"Return a transit writer. type maybe either :json or :json-verbose.\n  opts is a map with the following optional keys:\n\n    :handlers  - a map of type constructors to handler instances. Can optionally\n                 provide a :default write handler which will be used if no\n                 matching handler can be found.\n    :transform - a function of one argument returning a transformed value. Will\n                 be invoked on a value before it is written.",
$APP.l(kX)?kX.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,mX,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}()]);$APP.zy(new $APP.h(null,1,[$APP.Ut,new $APP.h(null,1,[$APP.mM,vAa],null)],null));