import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_module from"node:module";import*as esm_import$node_fs from"node:fs";import*as esm_import$import_meta_resolve from"import-meta-resolve";import*as esm_import$node_path from"node:path";import*as esm_import$node_url from"node:url";var JAa,KAa,EAa,rX,HAa,LAa,IAa,wX,vX;
$APP.DAa=function(a){a=$APP.ge(a);a=$APP.Mv.h($APP.Sg,a);a=$APP.Wp.h(function(d){return $APP.Lx($APP.fy(),d)},a);var b=$APP.q($APP.Xt),c=$APP.q($APP.Gt);return $APP.jy(a,new $APP.h(null,2,[$APP.W,b,$APP.ao,c],null))};$APP.FAa=function(a,b){return rX(EAa,a,b)};
$APP.tX=function(a,b){return Promise.resolve($APP.l($APP.q(GAa))?null:function(){var c=esm_import$node_path.resolve($APP.l(a)?a:"script.cljs"),d=$APP.l($APP.uE.g(b))?$APP.kk.j(b,$APP.uE,$APP.NS.g(esm_import$node_fs.readFileSync($APP.uE.g(b),"utf8"))):function(){var k;a:for(k=c;;){var n=esm_import$node_fs.existsSync(k);n=$APP.l(n)?esm_import$node_fs.lstatSync(k).isDirectory():n;if($APP.l(n)){n=esm_import$node_path.resolve(k,"nbb.edn");if($APP.l(esm_import$node_fs.existsSync(n))){k=n;break a}n=esm_import$node_path.dirname(k)}else n=
esm_import$node_path.dirname(k);if($APP.x.h(n,k)){k=null;break a}k=n}return $APP.l(k)?(n=$APP.NS.g(esm_import$node_fs.readFileSync(k,"utf8")),$APP.kk.l(b,$APP.uE,n,$APP.B([$APP.yQ,esm_import$node_path.dirname(k)]))):b}(),e=sX.g?sX.g(c):sX.call(null,c),f=$APP.m.g(esm_import$node_url.pathToFileURL(c));$APP.ny.require=e;$APP.yl.B($APP.my,$APP.kk,$APP.fq,e);$APP.yl.B($APP.my,$APP.kk,$APP.oy,function(k){return esm_import$import_meta_resolve.resolve(k,f)});$APP.Sh($APP.sV,d);return Promise.resolve(function(){var k=
function(){var E=$APP.Ob(HAa.g(d));return E?$APP.uE.g(d):E}();if($APP.l(k)){k=IAa.g(k);if($APP.l(k)){k=$APP.u(k);for(var n=null,r=0,p=0;;)if(p<r){var y=n.U(null,p);$APP.Ob(esm_import$node_path.isAbsolute(y))?$APP.Hs(function(){var E=$APP.yQ.g(d);return $APP.l(E)?esm_import$node_path.resolve(E,y):y}()):$APP.Hs(y);p+=1}else if(k=$APP.u(k)){n=k;if($APP.gf(n))k=$APP.yd(n),p=$APP.zd(n),n=k,r=$APP.Ge(k),k=p;else{var z=$APP.v(n);$APP.Ob(esm_import$node_path.isAbsolute(z))?$APP.Hs(function(){var E=$APP.yQ.g(d);
return $APP.l(E)?esm_import$node_path.resolve(E,z):z}()):$APP.Hs(z);k=$APP.w(n);n=null;r=0}p=0}else break}else $APP.Hs(esm_import$node_process.cwd());return shadow_esm_import("./nbb_deps.js")}return $APP.Hs(esm_import$node_process.cwd())}()).then(function(){return $APP.Sh(GAa,!0)})}())};$APP.uX=function(a,b){return $APP.px(a,b)};
JAa=function(a,b){b=$APP.Jx(a,$APP.bn("(keys (ns-map '%s))","%s",b));b=$APP.Wk.h(function(c){return["`",$APP.m.g(c)].join("")},b);b=["[",$APP.Tp.h(" ",b),"]"].join("");a=$APP.Jx(a,b);return $APP.Mv.h(function(c){return $APP.mn($APP.m.g(c),"nbb.internal")},a)};
KAa=function(a,b){var c=$APP.fy();b=$APP.hn.h(b,/\//);$APP.A.j(b,0,null);var d=$APP.A.j(b,1,null),e=$APP.Jx(c,$APP.tl.l($APP.B([$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.cu,null,1,null),new $APP.D(null,$APP.Ii($APP.Y.g($APP.u($APP.K.h(new $APP.D(null,vX,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,$APP.xH,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,$APP.zm,null,1,null),new $APP.D(null,a,null,1,null)))),null,1,null)))),null,1,null))))),null,1,
null),$APP.B([new $APP.D(null,$APP.Y.g($APP.u($APP.K.l(new $APP.D(null,$APP.lQ,null,1,null),new $APP.D(null,$APP.Y.g($APP.u($APP.K.h(new $APP.D(null,$APP.WJ,null,1,null),new $APP.D(null,vX,null,1,null)))),null,1,null),$APP.B([new $APP.D(null,vX,null,1,null)])))),null,1,null)]))))])));if($APP.l(e)&&(c=$APP.l(d)?function(){var n=$APP.Ia(d,"."),r=$APP.hn.h(d,/\./);n=n?r:$APP.wk(r);return new $APP.G(null,2,5,$APP.I,[[$APP.m.g(a),"/",$APP.u(n)?[$APP.Tp.h(".",n),"."].join(""):null].join(""),$APP.Oh.j($APP.Pa,
e,n)],null)}():new $APP.G(null,2,5,$APP.I,[[$APP.m.g(a),"/"].join(""),e],null),$APP.l(c))){var f=$APP.A.j(c,0,null),k=$APP.A.j(c,1,null);c=function(){for(var n=k,r=$APP.oi;;)if($APP.l(n)){var p=Object.getPrototypeOf(n);r=$APP.hj.h(r,Object.getOwnPropertyNames(n));n=p}else return r}();return $APP.Wk.h(function(n){return new $APP.G(null,2,5,$APP.I,[null,[$APP.m.g(f),$APP.m.g(n)].join("")],null)},c)}return null};
$APP.MAa=function(a){var b=$APP.vh(a);a=$APP.C.h(b,$APP.W);try{var c=$APP.fy(),d=$APP.l(a)?$APP.uX(c,$APP.dl.g(a)):null,e=$APP.sh([$APP.Xt,$APP.l(d)?d:$APP.q($APP.Xt)]);$APP.et(e);try{var f=function(){var ma=$APP.To.g(b);return $APP.l(ma)?ma:$APP.nM.g(b)}();if($APP.l(f)){var k=$APP.Ka(f,"/"),n=k?function(){var ma=$APP.hn.h(f,/\//);ma=null==ma?null:$APP.v(ma);return null==ma?null:$APP.dl.g(ma)}():null,r=JAa(c,$APP.Jx(c,"(ns-name *ns*)")),p=$APP.Wk.h(function(ma){return new $APP.G(null,3,5,$APP.I,[$APP.Ug(ma),
$APP.xk(ma),LAa],null)},r),y=$APP.Jx(c,"(let [m (ns-aliases *ns*)] (zipmap (keys m) (map ns-name (vals m))))"),z=$APP.yk($APP.hk(y),$APP.fk(y)),E=$APP.Dq.g($APP.ji.l(function(ma){var oa=$APP.C.h(y,ma);ma=$APP.Jx(c,$APP.bn("(keys (ns-publics '%s))","%s",oa));return $APP.Wk.h(function(ka){return new $APP.G(null,3,5,$APP.I,[$APP.m.g(oa),$APP.m.g(ka),wX],null)},ma)},$APP.B([$APP.fk(y)]))),H=$APP.Wk.h(function(ma){return new $APP.G(null,3,5,$APP.I,[$APP.m.g(ma),null,wX],null)},$APP.Jx(c,"(all-ns)")),P=
k?KAa(n,f):null,V=$APP.l(P)?null:k?function(){var ma=$APP.C.j(y,n,n),oa=$APP.Jx(c,$APP.bn("(and (find-ns '%s)\n                                                                                         (keys (ns-publics '%s)))","%s",ma));return $APP.Wk.h(function(ka){return new $APP.G(null,3,5,$APP.I,[$APP.m.g(ma),$APP.m.g(ka),wX],null)},oa)}():null,X=$APP.K.l(p,E,$APP.B([H,V])),aa=$APP.aq.h(function(ma){var oa=$APP.A.j(ma,0,null);var ka=$APP.A.j(ma,1,null);ma=$APP.A.j(ma,2,null);ma=$APP.x.h(LAa,ma)&&
$APP.Ka(ka,f)?new $APP.G(null,2,5,$APP.I,[oa,ka],null):null;$APP.l(ma)?oa=ma:$APP.l(oa)?(ma=[$APP.m.g($APP.C.h(z,$APP.dl.g(oa))),"/",$APP.m.g(ka)].join(""),ma=$APP.Ka(ma,f)?new $APP.G(null,2,5,$APP.I,[oa,ma],null):null,$APP.l(ma)?oa=ma:(ka=[$APP.m.g(oa),"/",$APP.m.g(ka)].join(""),oa=$APP.Ka(ka,f)?new $APP.G(null,2,5,$APP.I,[oa,ka],null):null)):oa=null;return oa},X),ca=$APP.K.h(aa,P),fa=$APP.Ii($APP.JB.g($APP.Wk.h(function(ma){var oa=$APP.A.j(ma,0,null);ma=$APP.A.j(ma,1,null);ma=new $APP.h(null,1,
["candidate",$APP.m.g(ma)],null);return $APP.l(oa)?$APP.kk.j(ma,"ns",$APP.m.g(oa)):ma},ca)));return new $APP.h(null,2,["completions",fa,"status",new $APP.G(null,1,5,$APP.I,["done"],null)],null)}return new $APP.h(null,1,["status",new $APP.G(null,1,5,$APP.I,["done"],null)],null)}finally{$APP.gt()}}catch(ma){return console.warn(ma),new $APP.h(null,2,["completions",$APP.oi,"status",new $APP.G(null,1,5,$APP.I,["done"],null)],null)}};EAa={};
rX=function rX(a,b,c){for(;;){if(b instanceof Promise)return b;if(EAa===a){if($APP.of(b))return $APP.xV(b,b,c,rX);a=$APP.ty(b,c)}else{b=Promise;var e=b.resolve;var f=$APP.dP.g(c);f=$APP.l(f)?f:$APP.Mf;c=new $APP.h(null,1,[$APP.W,$APP.W.g(c)],null);c=f.h?f.h(a,c):f.call(null,a,c);return e.call(b,c)}}};$APP.xX=new $APP.t(null,"socket-repl","socket-repl",-1615225633,null);$APP.yX=new $APP.t(null,"repl","repl",1605132860,null);HAa=new $APP.F(null,"disableConfig","disableConfig",844586790);
LAa=new $APP.F(null,"unqualified","unqualified",-98904653);IAa=new $APP.F(null,"paths","paths",-1807389588);wX=new $APP.F(null,"qualified","qualified",-2065109343);$APP.zX=new $APP.t(null,"start-server!","start-server!",203437330,null);$APP.AX=new $APP.F(null,"classpath","classpath",299521985);vX=new $APP.t(null,"resolved__34442__auto__","resolved__34442__auto__",-448361421,null);var sX,GAa;sX=function(){var a=esm_import$node_module.createRequire;return $APP.l(a)?a:function(){return function(){throw Error("createRequire is not defined, this is a no-op");}}}();GAa=$APP.xl.g(!1);$APP.BX=function BX(a){switch(arguments.length){case 1:return BX.g(arguments[0]);case 2:return BX.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};$APP.BX.g=function(a){return $APP.BX.h(a,null)};
$APP.BX.h=function(a,b){b=$APP.fC.l(b,$APP.B([$APP.gC,!0]));var c=esm_import$node_path.resolve(a);$APP.Sh($APP.sya,c);return $APP.tX(c,b).then(function(){return $APP.yy(c)})};$APP.BX.o=2;$APP.CX=function CX(a){switch(arguments.length){case 1:return CX.g(arguments[0]);case 2:return CX.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};$APP.CX.g=function(a){return $APP.CX.h(a,null)};
$APP.CX.h=function(a,b){b=$APP.fC.l(b,$APP.B([$APP.gC,!0]));return $APP.tX(null,b).then(function(){return $APP.wy(a)})};$APP.CX.o=2;export const loadFile=$APP.BX;export const loadString=$APP.CX;export const getClassPath=function(){return $APP.Gs()};export const addClassPath=function(a){return $APP.Hs(a)};export const version=function(){return $APP.Ky()};export const registerModule=function(a,b){b=$APP.Ufa($APP.Jm(b));return $APP.yl.B($APP.ly,$APP.kk,b,a)};export const printErrorReport=$APP.yV;