import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_goog_string.js";
import "./nbb_pprint.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_net from"node:net";import*as esm_import$node_fs from"node:fs";import*as esm_import$node_path from"node:path";
var eQa=function(a,b){a=a.indexOf(b);if(0>a)throw Error("out of input");return a},T5=function(a,b){if(a.length<b)throw Error("out of input");return a.slice(b)},U5=function(a,b){if(b>a.length)throw Error("out of input");return a.slice(0,b)},V5=function(a){return $APP.l($APP.cy.g($APP.q($APP.sV)))?console.debug($APP.Tp.h(" ",a)):null},gQa=function(a){return function(b,c){b=$APP.vh(b);var d=$APP.C.h(b,$APP.Pt),e=$APP.C.h(b,fQa);c=$APP.kk.j(c,"id",d);c=$APP.l(e)?$APP.kk.j(c,"session",e):c;return a.h?
a.h(b,c):a.call(null,b,c)}},iQa=function(){var a=hQa;return function(b,c){b=$APP.zp.j(b,W5,$APP.Xk);return a.h?a.h(b,c):a.call(null,b,c)}},kQa=function(){var a=jQa();return function(b,c){V5($APP.B(["request",b]));return a.h?a.h(b,c):a.call(null,b,c)}},lQa=function(a){return function(b,c){V5($APP.B(["response",c]));return a.h?a.h(b,c):a.call(null,b,c)}},jQa=function(){var a=iQa();return function(b,c){return a.h?a.h(b,c):a.call(null,b,c)}},mQa=function(a){return $APP.kk.j($APP.yk(new $APP.G(null,3,
5,$APP.I,["major","minor","incremental"],null),$APP.fC.g(a.split("."))),"version-string",a)},nQa=function(a,b,c){if($APP.l(a))if(a=X5.g?X5.g(a):X5.call(null,a),$APP.l(a)){b=$APP.vh(b);var d=$APP.C.h(b,$APP.TCa),e=$APP.C.h(b,$APP.e_),f=$APP.C.h(b,$APP.g_);b=$APP.Db;var k=$APP.Qk,n=$APP.uY;$APP.Db=e;$APP.Qk=f;$APP.uY=d;try{var r=new $APP.tb;d=$APP.Fb;e=$APP.Gb;$APP.Fb=!0;$APP.Gb=function(p){return r.append(p)};try{a.g?a.g(c):a.call(null,c)}finally{$APP.Gb=e,$APP.Fb=d}return $APP.m.g(r)}finally{$APP.uY=
n,$APP.Qk=k,$APP.Db=b}}else return V5($APP.B(["Pretty-Printing is only supported for clojure.core/prn and clojure.pprint/pprint."])),$APP.tl.l($APP.B([c]));else return $APP.tl.l($APP.B([c]))},oQa=function(a,b,c){$APP.iV.h($APP.RU,$APP.Qh(c));var d=$APP.St.g($APP.gm(c));d=$APP.l(d)?d:c.message;$APP.l(d)&&(d=new $APP.h(null,1,["err",[$APP.m.g(d),"\n"].join("")],null),a.h?a.h(b,d):a.call(null,b,d));c=new $APP.h(null,2,["ex",$APP.m.g(c),"ns",$APP.m.g($APP.q($APP.Xt))],null);return a.h?a.h(b,c):a.call(null,
b,c)},tQa=function(a,b){var c=$APP.vh(a),d=$APP.C.h(c,$APP.W);a=$APP.C.h(c,Y5);var e=$APP.C.h(c,$APP.ao);$APP.C.h(c,pQa);$APP.C.h(c,qQa);var f=$APP.Ds(a),k=function p(r){try{var y=function(){var E=$APP.W.g($APP.Le(r));if($APP.l(E))return E;E=$APP.q(Z5);return $APP.l(E)?E:d}(),z=$APP.Yfa(f,new $APP.h(null,3,[$APP.W,y,$APP.ao,e,$APP.fP,$APP.jA],null));return $APP.x.h($APP.kL,z)?Promise.resolve(r):$APP.FAa(z,new $APP.h(null,3,[$APP.W,y,$APP.ao,e,$APP.fP,$APP.jA],null)).then(function(E){var H=$APP.A.j(E,
0,null),P=$APP.A.j(E,1,null);P=$APP.W.g(P);$APP.Sh(Z5,P);$APP.iV.h($APP.QU,$APP.Qh($APP.q($APP.PU)));$APP.iV.h($APP.PU,$APP.Qh($APP.q($APP.OU)));$APP.iV.h($APP.OU,$APP.Qh(H));H=nQa(rQa.g(c),sQa.g(c),H);H=new $APP.h(null,2,["value",H,"ns",$APP.m.g(P)],null);b.h?b.h(c,H):b.call(null,c,H);return p(E)})}catch(E){return oQa(b,c,E),p(null)}};$APP.et($APP.sh([$APP.Xt,d,$APP.Gt,e,$APP.ET,$APP.q($APP.ET),$APP.JT,!0]));return function(){$APP.iV.h($APP.CT,$APP.Qh(function(r){r=new $APP.h(null,1,["out",r],null);
return b.h?b.h(c,r):b.call(null,c,r)}));return k(null).catch($APP.Vn.j(oQa,b,c)).finally(function(){var r=new $APP.h(null,2,["ns",$APP.m.g($APP.q(Z5)),"status",new $APP.G(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(c,r):b.call(null,c,r)})}().finally(function(){return $APP.gt()})},uQa=function(a,b){a=$APP.vh(a);var c=$APP.C.h(a,$APP.W),d=$APP.kk.j;c=$APP.l(c)?$APP.uX($APP.fy(),$APP.dl.g(c)):null;$APP.l(c)||(c=$APP.q(Z5),c=$APP.l(c)?c:$APP.q($APP.Xt));return tQa(d.call($APP.kk,a,$APP.W,c),
b)},$5=function(a,b){var c=$APP.vh(a),d=$APP.C.h(c,$APP.W),e=W5.g(c);try{var f=$APP.W.g(c),k=function(){var P=$APP.Mla.g(c);return $APP.l(P)?P:$APP.To.g(c)}(),n=function(){var P=$APP.l(d)?$APP.uX($APP.fy(),$APP.dl.g(d)):null;if($APP.l(P))return P;P=$APP.q(Z5);return $APP.l(P)?P:$APP.q($APP.Xt)}(),r=$APP.sh([$APP.Xt,n]);$APP.et(r);try{var p=$APP.Jx($APP.fy(),$APP.S5("\n(let [ns '%s\n      full-sym '%s]\n  (when-let [v (ns-resolve ns full-sym)]\n    (let [m (meta v)]\n      (assoc m :arglists (:arglists m)\n       :doc (:doc m)\n       :name (:name m)\n       :ns (some-\x3e m :ns ns-name)\n       :val @v))))",
f,k)),y=$APP.M.g(p),z=$APP.ao.g(p),E=$APP.bo.g(p),H=function(){var P=e instanceof $APP.F?e.ga:null;switch(P){case "eldoc":return P=new $APP.h(null,5,["ns",$APP.W.g(p),"name",$APP.O.g(p),"eldoc",$APP.Wp.h(function(V){return $APP.Wp.h($APP.m,V)},$APP.Z.g(p)),"type",$APP.qf($APP.Nx.g(p))?"function":"variable","status",new $APP.G(null,1,5,$APP.I,["done"],null)],null),$APP.l(y)?$APP.kk.j(P,"docstring",y):P;case "info":case "lookup":return P=new $APP.h(null,4,["ns",$APP.W.g(p),"name",$APP.O.g(p),"arglists-str",
$APP.Tp.h("\n",$APP.Wk.h($APP.tl,$APP.Z.g(p))),"status",new $APP.G(null,1,5,$APP.I,["done"],null)],null),P=$APP.l(y)?$APP.kk.j(P,"doc",y):P,P=$APP.l(z)?$APP.kk.j(P,"file",z):P,$APP.l(E)?$APP.kk.j(P,"line",E):P;default:throw Error(["No matching clause: ",$APP.m.g(P)].join(""));}}();return b.h?b.h(c,H):b.call(null,c,H)}finally{$APP.gt()}}catch(P){if(P instanceof Error)return a=P,f=function(){var V=new $APP.nk(null,new $APP.h(null,1,["done",null],null),null);return $APP.x.h(e,vQa)?$APP.Ng.h(V,"no-eldoc"):
V}(),a=new $APP.h(null,2,["status",f,"ex",$APP.m.g(a)],null),b.h?b.h(c,a):b.call(null,c,a);throw P;}},hQa=function(a,b){a=$APP.vh(a);var c=$APP.C.h(a,W5),d=$APP.C.h(wQa,c);if($APP.l(d))return d.h?d.h(a,b):d.call(null,a,b);console.warn($APP.Tp.h(" ",$APP.B(["Unhandled operation",c])));c=new $APP.h(null,1,["status",new $APP.G(null,3,5,$APP.I,["error","unknown-op","done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},xQa=function(a){return function(b,c){return a.write(a6(c))}},yQa=function(a,b){V5($APP.B(["Connection accepted"]));
b.setNoDelay(!0);var c=kQa(),d=gQa(lQa(xQa(b))),e=$APP.xl.g(null);b.on("data",function(f){var k=$APP.q(e);if($APP.l(k)){f=[$APP.m.g(k),$APP.m.g(f)].join("");$APP.Sh(e,null);var n=f}else n=f;a:for(f=$APP.B([$APP.gC,!0]),k=$APP.oi;;){var r=$APP.Oh.j(b6,n,f);n=$APP.A.j(r,0,null);r=$APP.A.j(r,1,null);if(null==n){k=new $APP.G(null,2,5,$APP.I,[k,r],null);break a}k=$APP.Ng.h(k,n);n=r}f=$APP.A.j(k,0,null);k=$APP.A.j(k,1,null);$APP.ln(k)||$APP.Sh(e,k);f=$APP.u(f);k=null;for(var p=r=0;;)if(p<r)n=k.U(null,p),
c(n,d),p+=1;else if(f=$APP.u(f))k=f,$APP.gf(k)?(f=$APP.yd(k),r=$APP.zd(k),k=f,n=$APP.Ge(f),f=r,r=n):(n=$APP.v(k),c(n,d),f=$APP.w(k),k=null,r=0),p=0;else return null});return b.on("close",function(f){return $APP.l(f)?V5($APP.B(["Connection lost"])):V5($APP.B(["Connection closed"]))})},c6=function(a){return Promise.resolve($APP.tX(esm_import$node_path.resolve("script.cljs"),null)).then(function(){function b(e){return $APP.DAa(new $APP.D(null,$APP.zm,new $APP.D(null,new $APP.D(null,$APP.zm,new $APP.D(null,
e,null,1,null),2,null),null,1,null),2,null))}var c=$APP.A.j($APP.tV,0,null),d=$APP.A.j($APP.tV,1,null);return b(c).then(function(){return b(d)})}).then(function(){var b=$APP.Tn.l($APP.B([$APP.q($APP.sV),a])),c=function(){var f=$APP.yK.g(b);return $APP.l(f)?f:0}(),d=function(){var f=$APP.PR.g(b);return $APP.l(f)?f:"127.0.0.1"}();(function(){var f=$APP.Rb(b)?b.Uk:zQa.g(b);return $APP.l(f)?f:"info"})();var e=esm_import$node_net.createServer($APP.Vn.h(yQa,$APP.th));e.listen(c,d,function(){var f=e.address(),
k=f.port;f=f.address;$APP.VB.l($APP.B([["nREPL server started on port ",$APP.m.g(k)," on host ",$APP.m.g(f)," - nrepl://",$APP.m.g(f),":",$APP.m.g(k)].join("")]));$APP.iV.h($APP.JT,$APP.Qh(!0));try{return esm_import$node_fs.writeFileSync(".nrepl-port",$APP.m.g(k))}catch(n){return console.warn($APP.Tp.h(" ",$APP.B(["Could not write .nrepl-port",n])))}});return $APP.Sh(AQa,e)})},BQa=new $APP.t("nbb.impl.nrepl-server","stop-server!","nbb.impl.nrepl-server/stop-server!",1628751782,null),sQa=new $APP.F("nrepl.middleware.print",
"options","nrepl.middleware.print/options",868480159),CQa=new $APP.t(null,"nbb.impl.nrepl-server","nbb.impl.nrepl-server",-1821079079,null),fQa=new $APP.F(null,"session","session",1008279103),DQa=new $APP.t("nbb.impl.nrepl-server","start-server!","nbb.impl.nrepl-server/start-server!",-2119141227,null),EQa=new $APP.F(null,"load-file","load-file",-424586670),Y5=new $APP.F(null,"code","code",1586293142),zQa=new $APP.F(null,"log_level","log_level",-1756736313),rQa=new $APP.F("nrepl.middleware.print",
"print","nrepl.middleware.print/print",-1616742548),FQa=new $APP.F(null,"clone","clone",711747572),GQa=new $APP.F(null,"close","close",1835149582),HQa=new $APP.F(null,"info","info",-317069002),IQa=new $APP.F(null,"macroexpand","macroexpand",-130598183),JQa=new $APP.F(null,"complete","complete",-500388775),qQa=new $APP.F(null,"_line","_line",232847719),d6=new $APP.t(null,"server","server",-1155245649,null),KQa=new $APP.F(null,"lookup","lookup",1225356838),LQa=new $APP.F(null,"expander","expander",
379138924),pQa=new $APP.F(null,"_load-file?","_load-file?",-1198848711),W5=new $APP.F(null,"op","op",-1882987955),MQa=new $APP.F(null,"describe","describe",1369790582),vQa=new $APP.F(null,"eldoc","eldoc",-1321421900),NQa=new $APP.t(null,"stop-server!","stop-server!",-410772185,null),OQa=new $APP.F(null,"load-file?","load-file?",1892536169);var e6=function e6(a,b){switch($APP.m.g(U5(a,1))){case "i":return a=T5(a,1),b=eQa(a,"e"),new $APP.G(null,2,5,$APP.I,[parseInt(U5(a,b)),T5(a,b+1)],null);case "l":var d=a=T5(a,1);for(a=$APP.od($APP.oi);;){if($APP.x.h($APP.m.g(U5(d,1)),"e"))return new $APP.G(null,2,5,$APP.I,[$APP.qd(a),T5(d,1)],null);var e=e6.h?e6.h(d,b):e6.call(null,d,b),f=$APP.A.j(e,0,null),k=$APP.A.j(e,1,null);e=k;a=$APP.ni.h(a,f);d=e}case "d":for(a=T5(a,1),f=$APP.vh(b),f=$APP.C.h(f,$APP.gC),d=a,e=$APP.od($APP.th);;){if($APP.x.h($APP.m.g(U5(d,
1)),"e"))return new $APP.G(null,2,5,$APP.I,[$APP.qd(e),T5(d,1)],null);a=e6.h?e6.h(d,b):e6.call(null,d,b);d=$APP.A.j(a,0,null);k=$APP.A.j(a,1,null);k=e6.h?e6.h(k,b):e6.call(null,k,b);a=$APP.A.j(k,0,null);k=$APP.A.j(k,1,null);d=$APP.l(f)?$APP.Xk.g(d):d;a=$APP.kj.j(e,d,a);d=k;e=a}default:return b=eQa(a,":"),f=parseInt(U5(a,b)),a=T5(a,b+1),new $APP.G(null,2,5,$APP.I,[$APP.m.g(U5(a,f)),T5(a,f)],null)}},b6=function b6(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;
return b6.l(arguments[0],1<c.length?new $APP.ce(c.slice(1),0,null):null)};b6.l=function(a,b){try{return e6(a,b)}catch(c){if(c instanceof Error)return new $APP.G(null,2,5,$APP.I,[null,a],null);throw c;}};b6.o=1;b6.A=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};
var a6=function a6(a){for(;;){if("string"===typeof a)return[$APP.m.g(Buffer.from(a).length),":",a].join("");if(a instanceof $APP.F||a instanceof $APP.t)a=[function(){var c=$APP.Ug(a);return $APP.l(c)?[c,"/"].join(""):null}(),$APP.xk(a)].join("");else return"number"===typeof a?["i",$APP.m.g(a),"e"].join(""):$APP.af(a)||$APP.ff(a)||null==a?["l",$APP.m.g($APP.Oh.h($APP.m,$APP.Wk.h(a6,a))),"e"].join(""):$APP.df(a)?["d",$APP.m.g($APP.Oh.h($APP.m,$APP.Wk.h(function(){return function(c){var d=$APP.A.j(c,
0,null);c=$APP.A.j(c,1,null);return[$APP.m.g(a6.g?a6.g(d):a6.call(null,d)),$APP.m.g(a6.g?a6.g(c):a6.call(null,c))].join("")}}(a),$APP.OA.h($APP.v,a)))),"e"].join(""):null}};var Z5=$APP.xl.g(null),X5=new $APP.h(null,1,["cider.nrepl.pprint/pprint",$APP.q_],null),wQa=$APP.Rj([$APP.AX,KQa,GQa,EQa,vQa,FQa,MQa,HQa,JQa,IQa,$APP.sra],[function(a,b){var c=new $APP.h(null,2,["status",new $APP.G(null,1,5,$APP.I,["done"],null),"classpath",$APP.hn.h($APP.Gs(),$APP.Pk(esm_import$node_path.delimiter))],null);return b.h?b.h(a,c):b.call(null,a,c)},$5,function(a,b){var c=new $APP.h(null,1,["status",new $APP.G(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},
function(a,b){a=$APP.vh(a);var c=$APP.C.h(a,$APP.ao);return tQa($APP.kk.l(a,Y5,c,$APP.B([OQa,!0,$APP.W,$APP.q($APP.Xt)])),b)},$5,function(a,b){var c=new $APP.h(null,2,["new-session",$APP.m.g($APP.dm()),"status",new $APP.G(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},function(a,b){var c=new $APP.h(null,4,["versions",new $APP.h(null,2,["nbb-nrepl",mQa("TODO"),"node",mQa(esm_import$node_process.version)],null),"aux",$APP.th,"ops",$APP.yk($APP.Wk.h($APP.xk,$APP.fk(wQa)),
$APP.Np.g($APP.th)),"status",new $APP.G(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},$5,function(a,b){var c=$APP.MAa(a);return b.h?b.h(a,c):b.call(null,a,c)},function(a,b){a=$APP.vh(a);var c=$APP.C.h(a,Y5),d=$APP.C.h(a,LQa);try{return uQa($APP.kk.j(a,Y5,["( ",$APP.m.g(d),"(quote ",$APP.m.g(c),"))"].join("")),function(e,f){var k=f.g?f.g("value"):f.call(null,"value");f=$APP.l(k)?$APP.kk.j(f,"expansion",k):f;return b.h?b.h(e,f):b.call(null,e,f)})}catch(e){if(e instanceof
Error)return c=new $APP.h(null,3,["ex",$APP.m.g(e),"ns",$APP.m.g($APP.q($APP.Xt)),"status",new $APP.G(null,1,5,$APP.I,["done"],null)],null),b.h?b.h(a,c):b.call(null,a,c);throw e;}},uQa]),AQa=$APP.xl.g(null),f6=function f6(a){switch(arguments.length){case 0:return f6.v();case 1:return f6.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};f6.v=function(){return f6.g($APP.q(AQa))};
f6.g=function(a){return a.close(function(){$APP.iV.h($APP.CT,$APP.Qh($APP.Gb));$APP.iV.h($APP.JT,$APP.Qh($APP.Fb));return $APP.l(esm_import$node_fs.existsSync(".nrepl-port"))?esm_import$node_fs.unlinkSync(".nrepl-port"):null})};f6.o=1;
var PQa=$APP.mV.h($APP.jD,null),QQa=new $APP.h(null,2,[$APP.zX,function(){var a=new $APP.ae(function(){return c6},DQa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.YC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.$I],[$APP.Ue(CQa,new $APP.h(null,1,[$APP.M,"Original implementation taken from https://github.com/viesti/nrepl-cljs-sci."],null)),$APP.zX,"nbb/impl/nrepl_server.cljs",20,1,327,327,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.JK],null)),"Start nRepl server. Accepts options either as JS object or Clojure map.",
$APP.l(c6)?c6.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,PQa,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),NQa,function(){var a=new $APP.ae(function(){return f6},BQa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.YC,$APP.AO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.$I],[$APP.Ue(CQa,new $APP.h(null,
1,[$APP.M,"Original implementation taken from https://github.com/viesti/nrepl-cljs-sci."],null)),NQa,"nbb/impl/nrepl_server.cljs",19,new $APP.h(null,6,[$APP.AD,!1,$APP.tw,1,$APP.UQ,1,$APP.lQ,new $APP.G(null,2,5,$APP.I,[$APP.oi,new $APP.G(null,1,5,$APP.I,[d6],null)],null),$APP.Z,$APP.J($APP.oi,new $APP.G(null,1,5,$APP.I,[d6],null)),$APP.UI,$APP.J(null,null)],null),1,398,398,$APP.J($APP.oi,new $APP.G(null,1,5,$APP.I,[d6],null)),null,$APP.l(f6)?f6.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:
$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,PQa,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}()],null);$APP.zy(new $APP.h(null,1,[$APP.Ut,new $APP.h(null,1,[$APP.jD,QQa],null)],null));