import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_api.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_net from"node:net";import*as esm_import$node_process from"node:process";import*as esm_import$node_readline from"node:readline";import*as esm_import$node_vm from"node:vm";
var x3=function(a){var b=function(){var e=$APP.fv.h(a,"(");return $APP.l(e)?new $APP.G(null,2,5,$APP.I,[$APP.Ok.j(a,0,e+1),$APP.Ok.h(a,e+1)],null):new $APP.G(null,2,5,$APP.I,[null,a],null)}(),c=$APP.A.j(b,0,null),d=$APP.A.j(b,1,null);b=$APP.C.h(function(){try{return $APP.NAa(new $APP.h(null,2,[$APP.W,$APP.m.g($APP.q(w3)),$APP.oM,d],null))}catch(f){var e=f;console.warn($APP.m.g($APP.Zra),$APP.hm(e));return null}}(),"completions");return $APP.Wk.h(function(e){return[$APP.m.g(c),$APP.m.g(e)].join("")},
$APP.pi(function(e){return $APP.Ha(e,d)},$APP.Wk.h(function(e){return $APP.C.h(e,"candidate")},b)))},rKa=function(a){return[$APP.bw.g(x3(a)),a]},B3=function(a,b){$APP.Sh(y3,!1);a.setPrompt([$APP.m.g($APP.q(w3)),"\x3d\x3e "].join(""));a.prompt();return $APP.ln($APP.q(z3))?null:A3.h?A3.h(b,a):A3.call(null,b,a)},sKa=function(a){var b=$APP.yn(a);a=$APP.zn(a);var c=$APP.jn($APP.q(z3));b=$APP.ei.h(b-1,c);c=$APP.u(b);b=$APP.v(c);c=$APP.w(c);a=$APP.l(b)?$APP.Ok.h(b,a):null;$APP.Sh(z3,$APP.Tp.h("\n",$APP.Rg(a,
c)))},tKa=function(a,b){b={f:b};esm_import$node_vm.createContext(b);try{return $APP.l($APP.l(C3)?$APP.Ob(a):C3)&&esm_import$node_process.stdin.setRawMode(!1),esm_import$node_vm.runInContext("f()",b,{displayErrors:!0,breakOnSigint:!0,microtaskMode:"afterEvaluate"}).then(function(c){var d={f:$APP.l(a)?function(){return c}:function(){var e=$APP.v(c);$APP.by.l($APP.B([e]));return c}};esm_import$node_vm.createContext(d);return esm_import$node_vm.runInContext("f()",d,{displayErrors:!0,breakOnSigint:!0,
microtaskMode:"afterEvaluate"})}).finally(function(){return $APP.l($APP.l(C3)?$APP.Ob(a):C3)?esm_import$node_process.stdin.setRawMode(!0):null})}catch(c){return b=c,$APP.l($APP.l(C3)?$APP.Ob(a):C3)&&esm_import$node_process.stdin.setRawMode(!0),Promise.reject(b)}},A3=function(a,b){if($APP.l(function(){var e=$APP.q(y3);return $APP.l(e)?e:$APP.ln($APP.q(z3))}()))return null;$APP.Sh(y3,!0);var c=$APP.Ds($APP.q(z3)),d=function(){try{var e=$APP.sh([$APP.Xt,$APP.q(w3)]);$APP.et(e);try{return $APP.Xfa(c)}finally{$APP.gt()}}catch(f){e=
f;if($APP.Ka($APP.hm(e),"EOF while reading"))return uKa;sKa(c);$APP.by.l($APP.B([$APP.m.g(e)]));return vKa}}();if($APP.x.h(vKa,d))return B3(b,a);if($APP.x.h(uKa,d))return $APP.Sh(y3,!1);sKa(c);if($APP.x.h($APP.hL,d))return $APP.Sh(y3,!1);$APP.et($APP.sh([$APP.Xt,$APP.q(w3)]));return tKa(a,function(){return $APP.GAa(d,new $APP.h(null,3,[$APP.W,$APP.q(w3),$APP.ao,$APP.q($APP.Gt),$APP.cP,$APP.jA],null))}).then(function(e){var f=$APP.A.j(e,0,null);e=$APP.A.j(e,1,null);e=$APP.vh(e);e=$APP.C.h(e,$APP.W);
$APP.Sh(w3,e);$APP.iV.h($APP.QU,$APP.Qh($APP.q($APP.PU)));$APP.iV.h($APP.PU,$APP.Qh($APP.q($APP.OU)));$APP.iV.h($APP.OU,$APP.Qh(f));$APP.l(a)&&a.write($APP.SB.l($APP.B([f])));return B3(b,a)}).catch(function(e){$APP.by.l($APP.B([$APP.m.g(e)]));$APP.iV.h($APP.RU,$APP.Qh(e));return B3(b,a)}).finally(function(){return $APP.gt()})},wKa=function(a,b){a.on("line",function(c){$APP.yl.B(z3,$APP.m,c,"\n");return A3(b,a)})},xKa=function(a){return esm_import$node_readline.createInterface({input:a,output:a,completer:rKa})},
yKa=function(a){var b=xKa(a);wKa(b,a);a.setNoDelay(!0);return a.on("close",function(){return $APP.VB.l($APP.B(["Client closed connection."]))})},D3=new $APP.t(null,"nbb.impl.repl","nbb.impl.repl",-339140484,null),uKa=new $APP.F("nbb.impl.repl","eof-while-reading","nbb.impl.repl/eof-while-reading",1743626215),zKa=new $APP.t("nbb.impl.repl","completer*","nbb.impl.repl/completer*",455172317,null),AKa=new $APP.t("nbb.impl.repl","repl","nbb.impl.repl/repl",-1645296655,null),BKa=new $APP.t(null,"completer*",
"completer*",-648150376,null),CKa=new $APP.t("nbb.impl.repl","socket-repl","nbb.impl.repl/socket-repl",1509490200,null),DKa=new $APP.F(null,"init","init",-1875481434),EKa=new $APP.t(null,"get-completions","get-completions",1933789168,null),vKa=new $APP.F("nbb.impl.repl","continue","nbb.impl.repl/continue",-1326808644);var w3=$APP.xl.g($APP.q($APP.Xt)),z3=$APP.xl.g(""),y3=$APP.xl.g(!1),C3,FKa=esm_import$node_process.stdout.isTTY;C3=$APP.l(FKa)?esm_import$node_process.stdin.setRawMode:FKa;var E3=$APP.mV.h($APP.pC,null),F3=function F3(a){switch(arguments.length){case 0:return F3.v();case 1:return F3.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};F3.v=function(){return F3.g(null)};
F3.g=function(a){var b=function(){var d=$APP.wK.g(a);return $APP.l(d)?d:0}(),c=esm_import$node_net.createServer(yKa);return c.listen(b,"127.0.0.1",function(){var d=c.address(),e=d.address;return $APP.VB.l($APP.B([["Socket REPL listening on port ",$APP.m.g(d.port)," on host ",$APP.m.g(e)].join("")]))})};F3.o=1;var G3=function G3(a){switch(arguments.length){case 0:return G3.v();case 1:return G3.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};G3.v=function(){return G3.g(null)};
G3.g=function(a){function b(e){return $APP.EAa(new $APP.D(null,$APP.zm,new $APP.D(null,new $APP.D(null,$APP.zm,new $APP.D(null,e,null,1,null),2,null),null,1,null),2,null))}$APP.l(C3)&&esm_import$node_process.stdin.setRawMode(!0);var c=$APP.A.j($APP.tV,0,null),d=$APP.A.j($APP.tV,1,null);$APP.VB.l($APP.B([["Welcome to nbb v",$APP.Ky(),"!"].join("")]));return b(c).then(function(){return b(d)}).then(DKa.h(a,$APP.Mf)).then(function(){return new Promise(function(e){var f=$APP.l(null)?xKa(null):esm_import$node_readline.createInterface({input:esm_import$node_process.stdin,
output:esm_import$node_process.stdout,completer:rKa});wKa(f,null);f.setPrompt([$APP.m.g($APP.q(w3)),"\x3d\x3e "].join(""));f.on("close",e);return f.prompt()})})};G3.o=1;
var GKa=new $APP.h(null,3,[$APP.yX,function(){var a=new $APP.ae(function(){return G3},AKa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.WC,$APP.xO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[D3,$APP.yX,"nbb/impl/repl.cljs",11,new $APP.h(null,6,[$APP.AD,!1,$APP.tw,1,$APP.UQ,1,$APP.kQ,new $APP.G(null,2,5,$APP.I,[$APP.oi,new $APP.G(null,1,5,$APP.I,[$APP.GK],null)],null),$APP.Z,$APP.J($APP.oi,new $APP.G(null,1,5,$APP.I,[$APP.GK],null)),$APP.QI,$APP.J(null,null)],null),1,187,187,$APP.J($APP.oi,new $APP.G(null,
1,5,$APP.I,[$APP.GK],null)),null,$APP.l(G3)?G3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,E3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),EKa,function(){var a=new $APP.ae(function(){return x3},zKa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.WC,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],
[D3,BKa,"nbb/impl/repl.cljs",17,1,16,16,$APP.J(new $APP.G(null,1,5,$APP.I,[$APP.zka],null)),"Given a line, returns a flat vector of completions",$APP.l(x3)?x3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,E3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}(),$APP.xX,function(){var a=new $APP.ae(function(){return F3},
CKa,$APP.Rj([$APP.W,$APP.O,$APP.ao,$APP.WC,$APP.xO,$APP.hp,$APP.bo,$APP.yS,$APP.Z,$APP.M,$APP.WI],[D3,$APP.xX,"nbb/impl/repl.cljs",18,new $APP.h(null,6,[$APP.AD,!1,$APP.tw,1,$APP.UQ,1,$APP.kQ,new $APP.G(null,2,5,$APP.I,[$APP.oi,new $APP.G(null,1,5,$APP.I,[$APP.GK],null)],null),$APP.Z,$APP.J($APP.oi,new $APP.G(null,1,5,$APP.I,[$APP.GK],null)),$APP.QI,$APP.J(null,null)],null),1,172,172,$APP.J($APP.oi,new $APP.G(null,1,5,$APP.I,[$APP.GK],null)),null,$APP.l(F3)?F3.D:null])),b=$APP.q(a),c=$APP.Ve(a);a=
$APP.l(null)?null:$APP.O.g(c);var d=new $APP.h(null,4,[$APP.W,E3,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.gu.g(c))?$APP.gV.j(a,b,d):$APP.l(function(){var e=$APP.st.g(c);return $APP.l(e)?e:$APP.It.g(c)}())?$APP.hV.j(a,b,d):$APP.Mx.j(a,b,d)}()],null);$APP.zy(new $APP.h(null,1,[$APP.Ut,new $APP.h(null,1,[$APP.pC,GKa],null)],null));